### ISSUE TITLE
Formatting code throws error

### ISSUE THREAD

**Issue by ccancellieri** [TypeStrong/atom-typescript#1008]
Hi,
 when I try to run format code on Atom I get:

`
Error: Debug Failure. False expression: 
    at Object.assert (/home/carlo/.atom/packages/atom-typescript/node_modules/ntypescript/bin/ntypescript.js:1715)
    at Object.getFormattingScanner (/home/carlo/.atom/packages/atom-typescript/node_modules/ntypescript/bin/ntypescript.js:47656)
    at formatSpan (/home/carlo/.atom/packages/atom-typescript/node_modules/ntypescript/bin/ntypescript.js:49236)
    at Object.formatDocument (/home/carlo/.atom/packages/atom-typescript/node_modules/ntypescript/bin/ntypescript.js:49051)
    at Object.getFormattingEditsForDocument (/home/carlo/.atom/packages/atom-typescript/node_modules/ntypescript/bin/ntypescript.js:56149)
    at Object.formatDocument (/home/carlo/.atom/packages/atom-typescript/dist/main/lang/modules/formatting.js:3)
    at Object.formatDocument (/home/carlo/.atom/packages/atom-typescript/dist/main/lang/projectService.js:192)
    at Child.RequesterResponder.processRequest (/home/carlo/.atom/packages/atom-typescript/dist/worker/lib/workerLib.js:50)
    at process.<anonymous> (/home/carlo/.atom/packages/atom-typescript/dist/worker/lib/workerLib.js:229)
    at emitTwo (events.js:87)
    at process.emit (events.js:172)
`

`
Uncaught (in promise) Object {method: "formatDocument", message: "Debug Failure. False expression: ", stack: "Error: Debug Failure. False expression: ↵    at Ob…s.js:87:13)↵    at process.emit (events.js:172:7)", details: Object}details: Objectmessage: "Debug Failure. False expression: "method: "formatDocument"stack: "Error: Debug Failure. False expression: ↵    at Object.assert (/home/carlo/.atom/packages/atom-typescript/node_modules/ntypescript/bin/ntypescript.js:1715:23)↵    at Object.getFormattingScanner (/home/carlo/.atom/packages/atom-typescript/node_modules/ntypescript/bin/ntypescript.js:47656:22)↵    at formatSpan (/home/carlo/.atom/packages/atom-typescript/node_modules/ntypescript/bin/ntypescript.js:49236:48)↵    at Object.formatDocument (/home/carlo/.atom/packages/atom-typescript/node_modules/ntypescript/bin/ntypescript.js:49051:20)↵    at Object.getFormattingEditsForDocument (/home/carlo/.atom/packages/atom-typescript/node_modules/ntypescript/bin/ntypescript.js:56149:34)↵    at Object.formatDocument (/home/carlo/.atom/packages/atom-typescript/dist/main/lang/modules/formatting.js:3:44)↵    at Object.formatDocument (/home/carlo/.atom/packages/atom-typescript/dist/main/lang/projectService.js:192:40)↵    at Child.RequesterResponder.processRequest (/home/carlo/.atom/packages/atom-typescript/dist/worker/lib/workerLib.js:50:60)↵    at process.<anonymous> (/home/carlo/.atom/packages/atom-typescript/dist/worker/lib/workerLib.js:229:23)↵    at emitTwo (events.js:87:13)↵    at process.emit (events.js:172:7)"__proto__: Object__defineGetter__: __defineGetter__()__defineSetter__: __defineSetter__()__lookupGetter__: __lookupGetter__()__lookupSetter__: __lookupSetter__()constructor: Object()hasOwnProperty: hasOwnProperty()isPrototypeOf: isPrototypeOf()propertyIsEnumerable: propertyIsEnumerable()toLocaleString: toLocaleString()toString: toString()valueOf: valueOf()get __proto__: get __proto__()set __proto__: set __proto__()
`

Is this report useful for you?

**Comment by ccancellieri** [comment]
Running the app with sudo 'solves' the problem, but this is not acceptable.
How to solve in a better way? What's the real problem?
Thanks
