### ISSUE TITLE
Failed to load the atom-typescript package: Cannot find module '../lang/utils'

### ISSUE THREAD

**Issue by valepu** [TypeStrong/atom-typescript#1071]
Hello,
I am having an issue when loading atom-typescript:

```
Cannot find module '../lang/utils'
Hide Stack Trace
Error: Cannot find module '../lang/utils'
    at Module._resolveFilename (module.js:339:15)
    at Function.Module._resolveFilename (C:\...\AppData\Local\atom\app-1.10.2\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (C:\...\AppData\Local\atom\app-1.10.2\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\...\.atom\packages\atom-typescript\dist\main\atom\atomConfig.js:2:15)
    at Module._compile (C:\...\AppData\Local\atom\app-1.10.2\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\...\AppData\Local\atom\app-1.10.2\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (C:\...\AppData\Local\atom\app-1.10.2\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\...\.atom\packages\atom-typescript\dist\main\atomts.js:2:18)
    at Module._compile (C:\...\AppData\Local\atom\app-1.10.2\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (C:\...\AppData\Local\atom\app-1.10.2\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (C:\...\AppData\Local\atom\app-1.10.2\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\...\AppData\Local\atom\app-1.10.2\resources\app.asar\src\package.js:718:27)
    at C:\...\AppData\Local\atom\app-1.10.2\resources\app.asar\src\package.js:117:28
    at Package.module.exports.Package.measure (C:\...\AppData\Local\atom\app-1.10.2\resources\app.asar\src\package.js:92:15)
    at Package.module.exports.Package.load (C:\...\AppData\Local\atom\app-1.10.2\resources\app.asar\src\package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (C:\...\AppData\Local\atom\app-1.10.2\resources\app.asar\src\package-manager.js:457:14)
    at C:\...\AppData\Local\atom\app-1.10.2\resources\app.asar\src\package-manager.js:402:19
    at Config.module.exports.Config.transact (C:\...\AppData\Local\atom\app-1.10.2\resources\app.asar\src\config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (C:\...\AppData\Local\atom\app-1.10.2\resources\app.asar\src\package-manager.js:397:19)
    at C:\...\AppData\Local\atom\app-1.10.2\resources\app.asar\src\atom-environment.js:754:28
```

When atom shows me this issue it says that it's already been reported and sends me here: https://github.com/TypeStrong/atom-typescript/issues/1007 but it looks like a different issue to me.

OS: Windows 10
Atom: 1.10.2
Atom-Typescript: 10.1.6

**Comment by daniel65dj** [comment]
I have this on ubuntu
and I cant figure it out!

**Comment by valepu** [comment]
Oh, i forgot: Uninstalling and reinstalling the package did the job for me

**Comment by daniel65dj** [comment]
oh

**Comment by daniel65dj** [comment]
# That did not fixit for me.

**Comment by boynedmaster** [comment]
Sorry it did not work for you, but to anyone coming from Atom uninstalling and reinstalling worked for me as well.

**Comment by starstuffharvestingstarlight** [comment]
Hi all, reinstalling the package (and atom) didn't work, still getting this error.

```
$ atom -v
Atom    : 1.11.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
```

**Comment by phil-cap** [comment]
Same here. Reinstallation did not help.

**Comment by marcusmalmberg** [comment]
Updating to `atom-typescript 10.1.13` solved this for me

**Comment by daniel65dj** [comment]
I had a linux system and a sync-settings package which downloaded windows settings so thats why it did not work for me.

**Comment by erkie** [comment]
I have atom-typescript 10.1.13 and still get the error.

**Comment by ithreshTop** [comment]
Error: Cannot find module 'typescript'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.makeTsGlobal (/Users/user/.atom/packages/atom-typescript/dist/typescript/makeTypeScriptGlobal.js:16:17)
    at Object.<anonymous> (/Users/user/.atom/packages/atom-typescript/dist/main/atomts.js:4:24)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:201:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:747:27)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:118:28
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:468:14)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:412:19
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:407:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:772:28

**Comment by j0nimost** [comment]
Has anyone found a solution for this problem

**Comment by FernandoBoza** [comment]
i had to update this and my jshint linter and ran into this issue
