### ISSUE TITLE
Uncaught TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by nathanb1397** [TypeStrong/atom-typescript#1215]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 ia32
**Electron**: 1.3.13
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [atom-typescript](https://github.com/TypeStrong/atom-typescript) package 11.0.0

### Stack Trace

Uncaught TypeError: Cannot read property 'replace' of undefined

```
At C:\Users\natha\.atom\packages\atom-typescript\dist\main\atom\utils\fs.js:13

TypeError: Cannot read property 'replace' of undefined
    at /packages/atom-typescript/dist/main/atom/utils/fs.js:13:62)
    at ErrorPusher.pushErrors.lodash_1.debounce (/packages/atom-typescript/dist/main/errorPusher.js:13:47)
    at invokeFunc (/packages/atom-typescript/node_modules/lodash/lodash.js:10350:23)
    at trailingEdge (/packages/atom-typescript/node_modules/lodash/lodash.js:10397:18)
    at timerExpired (/packages/atom-typescript/node_modules/lodash/lodash.js:10385:18)
```

### Commands

```
```

### Non-Core Packages

```
atom-typescript 11.0.0 
busy-signal 1.3.0 
intentions 1.1.2 
linter 2.1.0 
linter-ui-default 1.2.1 
open-on-bitbucket 0.4.0 
```

**Comment by guncha** [comment]
Anything special you did to trigger this? Tried it on Windows and it seemed to work fine.

**Comment by rainstormza** [comment]
same issues
