### ISSUE TITLE
can't start atom-typescrip

### ISSUE THREAD

**Issue by SeniorWhite** [TypeStrong/atom-typescript#1220]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.6.0
**System**: Ubuntu 16.04.2
**Thrown From**: [atom-typescript](https://github.com/TypeStrong/atom-typescript) package, v11.0.1

### Stack Trace

Failed to activate the atom-typescript package

```
At Unexpected token {

SyntaxError: Unexpected token {
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:77:42)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app.asar/src/package.js:720:27)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:172:16)
    at /usr/share/atom/resources/app.asar/src/package.js:846:28
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at PackageManager.module.exports.PackageManager.triggerDeferredActivationHooks (/usr/share/atom/resources/app.asar/src/package-manager.js:549:36)
    at /usr/share/atom/resources/app.asar/src/package-manager.js:489:17
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v1.1.0
atom-typescript, v11.0.1
linter, v1.11.18

# Dev
No dev packages
```

**Comment by romeupalos** [comment]
Hi SeniorWhite, 

I had the same problem... try to update you atom to the last version: https://github.com/atom/atom/releases/latest

It happened to me in version:
Atom    : 1.7.4
Electron: 0.36.8
Chrome  : 47.0.2526.110
Node    : 5.1.1

But when I updated Atom, everything worked fine:
Atom    : 1.15.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

Please, let me know if it works for you.

**Comment by cvonz** [comment]
The solution of @romeupalos works for me, thanks! ...The interesting thing is that it asks me to install many dependencies starting with 'linter'.

info:
previous atom version : 1.8.0
new atom version: 1.16.0
system: ubuntu 16.04
