### ISSUE TITLE
Uncaught Error: This socket has been ended by the other party

### ISSUE THREAD

**Issue by guiterra** [TypeStrong/atom-typescript#1232]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Unknown Windows version
**Thrown From**: [atom-typescript](https://github.com/TypeStrong/atom-typescript) package 11.0.1

### Stack Trace

Uncaught Error: This socket has been ended by the other party

```
At events.js:160

Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:286:12)
    at Immediate.setImmediate (/packages/atom-typescript/dist/client/client.js:139:22)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
```

### Commands

```
  2x -2:52.9.0 editor:newline (input.hidden-input)
     -2:51.8.0 core:paste (input.hidden-input)
     -2:44.9.0 core:save (input.hidden-input)
     -2:28.4.0 core:backspace (input.hidden-input)
     -2:23.8.0 core:save (input.hidden-input)
  2x -1:53.7.0 core:backspace (input.hidden-input)
  4x -1:45 core:save (input.hidden-input)
 12x -0:49.1.0 core:backspace (input.hidden-input)
  2x -0:46.7.0 core:undo (input.hidden-input)
  4x -0:43.2.0 core:backspace (input.hidden-input)
     -0:40.2.0 core:save (input.hidden-input)
  2x -0:39.2.0 editor:newline (input.hidden-input)
     -0:36.8.0 core:backspace (input.hidden-input)
     -0:36 editor:newline (input.hidden-input)
  3x -0:35.3.0 core:backspace (input.hidden-input)
     -0:33.8.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.29.17 
atom-typescript 11.0.1 
autoclose-html 0.23.0 
autocomplete-java 1.2.5 
autocomplete-paths 1.0.5 
emmet 2.4.3 
linter 2.1.2 
monokai-dark 1.3.0 
```

**Comment by centrinav** [comment]
I have the same issue, any solution?

**Comment by guncha** [comment]
Restarting Atom usually fixes this, at least until `tsserver` crashes again. I have a fix in the works to handle this sort of thing gracefully, but it might be some time until I can publish it.
