### ISSUE TITLE
Uncaught Error: This socket is closed

### ISSUE THREAD

**Issue by havelessbemore** [TypeStrong/atom-typescript#1235]
[Enter steps to reproduce:]

1. Open .ts file
2. Move cursor around / modify file

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [atom-typescript](https://github.com/TypeStrong/atom-typescript) package 11.0.1

### Stack Trace

Uncaught Error: This socket is closed

```
At events.js:160

Error: This socket is closed
    at Socket._writeGeneric (net.js:673:19)
    at Socket._write (net.js:725:8)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at Socket.Writable.write (_stream_writable.js:220:11)
    at Socket.write (net.js:651:40)
    at Immediate.setImmediate (/packages/atom-typescript/dist/client/client.js:139:22)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
```

### Commands

```
     -7:34.9.0 editor:newline (input.hidden-input)
  2x -6:34.3.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
.bin undefined 
atom-jade 0.3.0 
atom-typescript 11.0.1 
busy-signal 1.3.0 
intentions 1.1.2 
linter 2.1.2 
linter-ui-default 1.2.2 
script 3.14.1 
```

**Comment by GerryFudd** [comment]
I am encountering this same problem.

**Comment by guncha** [comment]
Do either of your have any console output right before you got this error? I suspect `tsserver` crashed for some reason and the plugin tried to send a command not being being aware of that.

**Comment by GerryFudd** [comment]
I just went to check the logs after uninstalling and reinstalling.  I don't see the error anymore.

**Comment by havelessbemore** [comment]
I also don't see the error anymore after completely closing and restarting
the application.

**Comment by firstthumb** [comment]
I got the same error
