### ISSUE TITLE
Compile on save not working

### ISSUE THREAD

**Issue by Parziphal** [TypeStrong/atom-typescript#1242]
I just uninstalled completely and reinstalled Atom, then installed Atom-Typescript and its dependencies, so I'm using latest versions. The `tsconfig.json` file has the `compileOnSave` option set to `true`, however the feature simply doesn't work. 

If I press F6 to run "build", all I see is a red box on the bottom side that says "Emit Failed" without any more information.

It was working before (over a month ago), before this plugin required "lint".

**Comment by guncha** [comment]
Do you have any output in the console? You might be using a little older version of Typescript, say, 1.8? Right now it fails silently if the compiler API doesn't support the right command.

**Comment by Parziphal** [comment]
How do I know which version of Typescript is Atom using? According to the [FAQ](https://github.com/TypeStrong/atom-typescript/blob/master/docs/faq.md#which-version-of-typescript-does-atom-typescript-use) it uses the one in `node_modules`? It was 1.8, I updated it to the latest which is 2.2.2, but it still doesn't work.

An error is logged upon file save:

![image](https://cloud.githubusercontent.com/assets/5176023/25055093/725369fa-2126-11e7-9840-aed206b383e9.png)

**Comment by guncha** [comment]
It should show up next to the selected grammar on the bottom right:

![image](https://cloud.githubusercontent.com/assets/679632/25056281/dcd82810-2135-11e7-9709-431a2151d8e6.png)

This is something different, though. If you click on the little `(...)`, it'll show you where actually the error was thrown which would help diagnose this.

![image](https://cloud.githubusercontent.com/assets/679632/25056363/56a74f36-2136-11e7-9203-68d32d5a5ce4.png)

**Comment by Parziphal** [comment]
Oh, I didn't realize the dots show the rest of the error message while the arrow is for the stack trace, I'll paste the message below. As for the version, it says `2.2.2`.

This is unrelated, but everytime I open any file that isn't a ts file, an error saying `Missing filePath or not a Typescript file` appears. Shouldn't the extension try to deal only with `.ts` files?

```
TypeError: Cannot read property 'name' of undefined
    at mergeSymbol ({...}\node_modules\typescript\lib\tsserver.js:21546:46)
    at {...}\node_modules\typescript\lib\tsserver.js:21570:21
    at Map.forEach (native)
    at mergeSymbolTable ({...}\node_modules\typescript\lib\tsserver.js:21560:20)
    at initializeTypeChecker ({...}\node_modules\typescript\lib\tsserver.js:37494:21)
    at Object.createTypeChecker ({...}\node_modules\typescript\lib\tsserver.js:21430:9)
    at Object.getTypeChecker ({...}\node_modules\typescript\lib\tsserver.js:52546:79)
    at ConfiguredProject.Project.getReferencedFiles ({...}\node_modules\typescript\lib\tsserver.js:70333:48)
    at ModuleBuilder.getReferencedFileInfos ({...}\node_modules\typescript\lib\tsserver.js:69693:56)
    at ModuleBuilder.updateFileReferences ({...}\node_modules\typescript\lib\tsserver.js:69724:42)
    at mergeSymbol ({...}\node_modules\typescript\lib\tsserver.js:21546:46)
    at {...}\node_modules\typescript\lib\tsserver.js:21570:21
    at Map.forEach (native)
    at mergeSymbolTable ({...}\node_modules\typescript\lib\tsserver.js:21560:20)
    at initializeTypeChecker ({...}\node_modules\typescript\lib\tsserver.js:37494:21)
    at Object.createTypeChecker ({...}\node_modules\typescript\lib\tsserver.js:21430:9)
    at Object.getTypeChecker ({...}\node_modules\typescript\lib\tsserver.js:52546:79)
    at ConfiguredProject.Project.getReferencedFiles ({...}\node_modules\typescript\lib\tsserver.js:70333:48)
    at ModuleBuilder.getReferencedFileInfos ({...}\node_modules\typescript\lib\tsserver.js:69693:56)
    at ModuleBuilder.updateFileReferences ({...}\node_modules\typescript\lib\tsserver.js:69724:42)
    at MessageStream.TypescriptServiceClient.onMessage (C:\Users\aster\.atom\packages\atom-typescript\dist\client\client.js:40:41)
    at emitOne (events.js:96:13)
    at MessageStream.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at MessageStream.Readable.push (_stream_readable.js:134:10)
    at MessageStream.Transform.push (_stream_transform.js:128:32)
    at MessageStream._transform (C:\Users\aster\.atom\packages\atom-typescript\dist\client\client.js:198:18)
    at MessageStream.Transform._read (_stream_transform.js:167:10)
    at MessageStream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at MessageStream.Writable.write (_stream_writable.js:220:11)
    at LineStream.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at LineStream.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at LineStream.Readable.push (_stream_readable.js:134:10)
    at LineStream.Transform.push (_stream_transform.js:128:32)
    at LineStream._pushBuffer (C:\Users\aster\.atom\packages\atom-typescript\node_modules\byline\lib\byline.js:126:17)
    at LineStream._transform (C:\Users\aster\.atom\packages\atom-typescript\node_modules\byline\lib\byline.js:117:8)
    at LineStream.Transform._read (_stream_transform.js:167:10)
    at LineStream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:307:12)
    at writeOrBuffer (_stream_writable.js:293:5)
    at LineStream.Writable.write (_stream_writable.js:220:11)
    at Socket.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:543:20)
```

**Comment by guncha** [comment]
That actually seems like an error in the compiler. This might be it: https://github.com/Microsoft/TypeScript/issues/15128

That `Missing filePath or not a Typescript file` error is completely normal though it's a little confusing so I'll get rid of it.

**Comment by Parziphal** [comment]
After looking the message I thought the error isn't related to this extension. But the linked issue shows no fixes. Is there a fix for this?

**Comment by guncha** [comment]
Unless you want to use a different Typescript version, you best bet is to wait for the Typescript team to fix it. There isn't anything `atom-typescript` could do except maybe provide a more useful error message.

**Comment by Parziphal** [comment]
Alright, thank you for your time and help.
