### ISSUE TITLE
Uncaught TypeError: Cannot read property 'stack' of null

### ISSUE THREAD

**Issue by byrondover** [TypeStrong/atom-typescript#1245]
Steps to reproduce:

1. Open .ts file (e.g. Angular app)
2. Move cursor around / modify file
3. Open multiple .ts files and make edits, tabbing between them

From a UX perspective, feels similar to #1235.

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [atom-typescript](https://github.com/TypeStrong/atom-typescript) package 11.0.2

### Stack Trace

Uncaught TypeError: Cannot read property 'stack' of null

```
At /Users/bdover/.atom/packages/atom-typescript/dist/client/client.js:174

TypeError: Cannot read property 'stack' of null
    at Immediate.setImmediate (/packages/atom-typescript/dist/client/client.js:174:37)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
```

### Commands

```
     -0:22.2.0 pane:show-previous-item (input.hidden-input)
     -0:18.8.0 core:cut (input.hidden-input)
  2x -0:18.4.0 core:backspace (input.hidden-input)
     -0:17.9.0 pane:show-next-item (input.hidden-input)
     -0:17.4.0 core:paste (input.hidden-input)
     -0:16.8.0 core:select-all (input.hidden-input)
     -0:16.6.0 core:move-up (input.hidden-input)
  2x -0:16.4.0 editor:newline (input.hidden-input)
  2x -0:16.1.0 core:move-up (input.hidden-input)
     -0:15.8.0 intentions:highlight (input.hidden-input)
     -0:15.2.0 pane:show-previous-item (input.hidden-input)
     -0:09.9.0 core:cut (input.hidden-input)
     -0:09.7.0 core:move-down (input.hidden-input)
     -0:09.3.0 core:backspace (input.hidden-input)
     -0:09.0 pane:show-next-item (input.hidden-input)
     -0:08.3.0 core:paste (input.hidden-input)
```

### Non-Core Packages

```
atom-typescript 11.0.2 
busy-signal 1.3.0 
go-debug 1.2.0 
go-plus 5.4.0 
go-signature-statusbar 1.2.0 
hyperclick 0.0.40 
intentions 1.1.2 
language-docker 1.1.7 
language-groovy 0.6.0 
language-puppet 0.22.0 
linter 2.1.4 
linter-ui-default 1.2.3 
markdown-toc 0.4.2 
pretty-json 1.6.3 
```

**Comment by skonx** [comment]
[Enter steps to reproduce:]

1. Open 2 different .ts file (e.g. Angular app)

**Atom**: 1.16.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.4
**Thrown From**: [atom-typescript](https://github.com/TypeStrong/atom-typescript) package 11.0.2


### Stack Trace

Uncaught TypeError: Cannot read property 'stack' of null

```
At /Users/jsie/.atom/packages/atom-typescript/dist/client/client.js:174

TypeError: Cannot read property 'stack' of null
    at Immediate.setImmediate (/packages/atom-typescript/dist/client/client.js:174:37)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.29.23 
atom-typescript 11.0.2 
busy-signal 1.3.0 
diagrams 0.26.4 
intentions 1.1.2 
linter 2.1.4 
linter-ui-default 1.2.3 
```
