### ISSUE TITLE
Typescript quit unexpectedly (ReferenceError: Invalid left-hand side in assignment)

### ISSUE THREAD

**Issue by Wandang** [TypeStrong/atom-typescript#1299]
After updating tyepscript via atom to the latest version tyepscript itself crashes.

OS: Linux Debian 64bit
Atom: v. 1.18

I get this crash output:
```
Last output from tsserver:
/home/username/path/to/project/node_modules/typescript/lib/tsserver.js:72820
            Session.prototype&isValidBraceCompletion = function (args) {
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ReferenceError: Invalid left-hand side in assignment
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/username/path/to/project/node_modules/typescript/bin/tsserver:2:1)
    at Module._compile (module.js:556:32)
 
Error: exited with code: 1
    at ChildProcess.exitHandler (/home/username/.atom/packages/atom-typescript/dist/client/client.js:175:58)
    at ChildProcess.g (events.js:286:16)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

**Comment by guncha** [comment]
What is your version of Typescript installed in your project?

**Comment by Wandang** [comment]
you mean via package.json?
- "typescript": "~2.2.0"
