### ISSUE TITLE
Uncaught Error: Cannot find module './atom/hyperclickProvider'

### ISSUE THREAD

**Issue by drewg2009** [TypeStrong/atom-typescript#1313]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.6
**Thrown From**: [atom-typescript](https://github.com/TypeStrong/atom-typescript) package 11.0.6

### Stack Trace

Uncaught Error: Cannot find module './atom/hyperclickProvider'

```
At /Applications/Atom.app/Contents/Resources/app/static/<embedded>:1

Error: Cannot find module './atom/hyperclickProvider'
  at Module._resolveFilename (module.js:455:15)
  at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
  at Function.get_Module._resolveFilename (<embedded>:8013:58)
  at Module.require (Applications/Atom.app/Contents/Resources/app/static/index.js:40:43)
  at require (<embedded>:7358:33)
  at /packages/atom-typescript/dist/main/atomts.js:9:30)
  at Module.get_Module._compile (<embedded>:7398:36)
  at Object.value [as .js] (<embedded>:7649:29)
  at Module.load (module.js:473:32)
  at tryModuleLoad (module.js:432:12)
  at Function.Module._load (module.js:424:3)
  at Module.require (Applications/Atom.app/Contents/Resources/app/static/index.js:47:45)
  at require (internal/module.js:20:19)
  at customRequire (<embedded>:96:26)
  at Package.module.exports.Package.requireMainModule (<embedded>:69750:35)
  at Package.module.exports.Package.activateConfig (<embedded>:69164:18)
  at PackageManager.module.exports.PackageManager.packageHasSettings (<embedded>:52955:20)
  at PackageCard.hasSettings (<embedded>:181200:40)
  at PackageCard.updateSettingsState (<embedded>:180845:22)
  at PackageCard.updateInterfaceState (<embedded>:180837:18)
  at <embedded>:181134:22
  at <embedded>:181217:17
  at Function.module.exports.Emitter.simpleDispatch (<embedded>:63093:20)
  at Emitter.module.exports.Emitter.emit (<embedded>:63209:34)
  at PackageManager.module.exports.PackageManager.emitPackageEvent (<embedded>:53574:33)
  at <embedded>:53413:32
  at exit (<embedded>:53015:22)
  at triggerExitCallback (<embedded>:116712:17)
  at ChildProcess.<anonymous> (<embedded>:116742:17)
  at emitTwo (events.js:106:13)
  at ChildProcess.emit (events.js:191:7)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

```

### Commands

```
     -2:01.1.0 core:confirm (input.hidden-input)
     -1:34.4.0 core:select-all (input.hidden-input)
 10x -1:34.2.0 core:backspace (input.hidden-input)
     -1:29 core:confirm (input.hidden-input)
  4x -1:14 core:backspace (input.hidden-input)
     -1:12.1.0 core:confirm (input.hidden-input)
     -0:53.7.0 core:backspace (input.hidden-input)
     -0:33.3.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-typescript 11.0.6 
autocomplete-ionic2-framework 0.3.2 
Quick-JavaScript 2.2.0 
react 0.16.2 
```

**Comment by lierdakil** [comment]
Sorry about the lack of response. Most likely something got borked during package installation, reinstalling usually helps.
