### ISSUE TITLE
Failed to activate the atom-typescript package

### ISSUE THREAD

**Issue by ralmarri12** [TypeStrong/atom-typescript#1323]
Many errors appears after last atom update. the Error i'm facing now is "Failed to activate the atom-typescript package"

Deprecated calls
atom core (1 deprecation)
The contents of atom-text-editor elements are no longer encapsulated within a shadow DOM boundary. Please, stop using rootElement and access the editor contents directly instead.
HTMLElement.rootElement - /Applications/Atom.app/Contents/Resources/app/src/text-editor-element.js:23:10
getFromShadowDom - /Users/rashidalmarri/.atom/packages/atom-typescript/dist/main/atom/tooltipManager.js:18:19
Object.attach - /Users/rashidalmarri/.atom/packages/atom-typescript/dist/main/atom/tooltipManager.js:38:18
TypescriptEditorPane.setupTooltipView - /Users/rashidalmarri/.atom/packages/atom-typescript/dist/main/typescriptEditorPane.js:187:24
new TypescriptEditorPane - /Users/rashidalmarri/.atom/packages/atom-typescript/dist/main/typescriptEditorPane.js:140:14
subscriptions.add.atom.workspace.observeTextEditors - /Users/rashidalmarri/.atom/packages/atom-typescript/dist/main/atomts.js:90:24

Unexpected Token <

SyntaxError: Unexpected token <
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:94:52)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (file:///Applications/Atom.app/Contents/Resources/app/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/Users/rashidalmarri/.atom/packages/atom-typescript/dist/main/typescriptEditorPane.js:9:24)
    at Object.<anonymous> (/Users/rashidalmarri/.atom/packages/atom-typescript/dist/main/typescriptEditorPane.js:192:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (file:///Applications/Atom.app/Contents/Resources/app/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/Users/rashidalmarri/.atom/packages/atom-typescript/dist/main/atomts.js:16:32)
    at Object.<anonymous> (/Users/rashidalmarri/.atom/packages/atom-typescript/dist/main/atomts.js:207:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (file:///Applications/Atom.app/Contents/Resources/app/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:887:35)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:242:22)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:1014:34
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PackageManager.module.exports.PackageManager.triggerDeferredActivationHooks (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:676:42)
    at /Applications/Atom.app/Contents/Resources/app/src/package-manager.js:607:23
 

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.0 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [atom-typescript](https://github.com/TypeStrong/atom-typescript) package 11.0.6

### Stack Trace

Failed to activate the atom-typescript package

```
At Unexpected token <

SyntaxError: Unexpected token <
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:94:52)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (Applications/Atom.app/Contents/Resources/app/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-typescript/dist/main/typescriptEditorPane.js:9:24)
    at /packages/atom-typescript/dist/main/typescriptEditorPane.js:192:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (Applications/Atom.app/Contents/Resources/app/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-typescript/dist/main/atomts.js:16:32)
    at /packages/atom-typescript/dist/main/atomts.js:207:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (Applications/Atom.app/Contents/Resources/app/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:887:35)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:242:22)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:1014:34
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PackageManager.module.exports.PackageManager.triggerDeferredActivationHooks (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:676:42)
    at /Applications/Atom.app/Contents/Resources/app/src/package-manager.js:607:23
```

### Commands

```
     -1:47.4.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
arduino-atom 0.1.0 
arduino-toolbelt 0.1.1 
arduino-upload 1.1.0 
atom-alignment 0.13.0 
atom-typescript 11.0.6 
busy-signal 1.4.3 
change-case 0.6.5 
dash 1.7.1 
emmet 2.4.3 
file-icons undefined 
highlight-selected 0.13.1 
intentions 1.1.5 
language-arduino 0.4.3 
language-blade 0.34.0 
language-vue 0.23.1 
linter 2.2.0 
linter-ui-default 1.6.4 
todo-show 1.11.0 
vue-autocomplete 0.1.1 
```

**Comment by ralmarri12** [comment]
Got the solution here:
https://github.com/TypeStrong/atom-typescript/issues/1317

**Comment by jcardenasp** [comment]
Hello @ralmarri12 how can I fix this issue?

Thanks.

**Comment by ralmarri12** [comment]
Hello @jcardenasp,

I uninstalled the tyepscript package,

and I installed this one,

https://github.com/lierdakil/atom-typescript
(Do not follow the read me just download the package and install it manually)

that how it works with me

**Comment by molayaias** [comment]
Hi I am having a similar error, but for another cause different:

Check the error here:

> Cannot find module 'strip-bom-buf'
> Hide Stack Trace
> Error: Cannot find module 'strip-bom-buf'
>     at Module._resolveFilename (module.js:470:15)
>     at Module._resolveFilename (C:\Users\User\AppData\Local\atom\app-1.19.2\resources\electron.asar\common\reset-search-paths.js:35:12)
>     at Function.get_Module._resolveFilename (C:\Users\User\AppData\Local\atom\app-1.19.2\resources\app\src\module-cache.js:354:58)
>     at Module.require (file:///C:/Users/User/AppData/Local/atom/app-1.19.2/resources/app/static/index.js:40:43)
>     at require (C:\Users\User\AppData\Local\atom\app-1.19.2\resources\app\src\native-compile-cache.js:66:33)
>     at Object.<anonymous> (C:\Users\User\.atom\packages\linter\node_modules\sb-fs\lib\index.js:11:20)
>     at Object.<anonymous> (C:\Users\User\.atom\packages\linter\node_modules\sb-fs\lib\index.js:57:3)
>     at Module.get_Module._compile (C:\Users\User\AppData\Local\atom\app-1.19.2\resources\app\src\native-compile-cache.js:106:36)
>     at Object.value [as .js] (C:\Users\User\AppData\Local\atom\app-1.19.2\resources\app\src\compile-cache.js:239:29)
>     at Module.load (module.js:488:32)
>     at tryModuleLoad (module.js:447:12)
>     at Function.Module._load (module.js:439:3)
>     at Module.require (file:///C:/Users/User/AppData/Local/atom/app-1.19.2/resources/app/static/index.js:47:45)
>     at require (C:\Users\User\AppData\Local\atom\app-1.19.2\resources\app\src\native-compile-cache.js:66:33)
>     at Object.<anonymous> (C:\Users\User\.atom\packages\linter\node_modules\atom-package-deps\lib\helpers.js:135:13)
>     at Object.<anonymous> (C:\Users\User\.atom\packages\linter\node_modules\atom-package-deps\lib\helpers.js:180:3)
>     at Module.get_Module._compile (C:\Users\User\AppData\Local\atom\app-1.19.2\resources\app\src\native-compile-cache.js:106:36)
>     at Object.value [as .js] (C:\Users\User\AppData\Local\atom\app-1.19.2\resources\app\src\compile-cache.js:239:29)
>     at Module.load (module.js:488:32)
>     at tryModuleLoad (module.js:447:12)
>     at Function.Module._load (module.js:439:3)
>     at Module.require (file:///C:/Users/User/AppData/Local/atom/app-1.19.2/resources/app/static/index.js:47:45)
>     at require (C:\Users\User\AppData\Local\atom\app-1.19.2\resources\app\src\native-compile-cache.js:66:33)
>     at Object.<anonymous> (C:\Users\User\.atom\packages\linter\node_modules\atom-package-deps\lib\index.js:55:16)
>     at Object.<anonymous> (C:\Users\User\.atom\packages\linter\node_modules\atom-package-deps\lib\index.js:84:3)
>     at Module.get_Module._compile (C:\Users\User\AppData\Local\atom\app-1.19.2\resources\app\src\native-compile-cache.js:106:36)
>     at Object.value [as .js] (C:\Users\User\AppData\Local\atom\app-1.19.2\resources\app\src\compile-cache.js:239:29)
>     at Module.load (module.js:488:32)
>     at tryModuleLoad (module.js:447:12)
>     at Function.Module._load (module.js:439:3)
>     at Module.require (file:///C:/Users/User/AppData/Local/atom/app-1.19.2/resources/app/static/index.js:47:45)
>     at require (C:\Users\User\AppData\Local\atom\app-1.19.2\resources\app\src\native-compile-cache.js:66:33)
>     at Object.activate (C:\Users\User\.atom\packages\atom-typescript\dist\main\atomts.js:29:5)
>     at Package.module.exports.Package.activateNow (C:\Users\User\AppData\Local\atom\app-1.19.2\resources\app\src\package.js:253:25)
>     at C:\Users\User\AppData\Local\atom\app-1.19.2\resources\app\src\package.js:1014:34
>     at Function.module.exports.Emitter.simpleDispatch (C:\Users\User\AppData\Local\atom\app-1.19.2\resources\app\node_modules\event-kit\lib\emitter.js:25:20)
>     at Emitter.module.exports.Emitter.emit (C:\Users\User\AppData\Local\atom\app-1.19.2\resources\app\node_modules\event-kit\lib\emitter.js:141:34)
>     at PackageManager.module.exports.PackageManager.triggerDeferredActivationHooks (C:\Users\User\AppData\Local\atom\app-1.19.2\resources\app\src\package-manager.js:676:42)
>     at C:\Users\User\AppData\Local\atom\app-1.19.2\resources\app\src\package-manager.js:607:23

**Comment by lierdakil** [comment]
Try uninstalling and reinstalling. This can happen from time to time I
believe. Also, please do not use lierdakil/atom-typescript anymore, it's
neither supported nor maintained.
