### ISSUE TITLE
Uncaught TypeError: Cannot read property 'classList' of undefined

### ISSUE THREAD

**Issue by ebds** [TypeStrong/atom-typescript#1336]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.19.5 x64
**Electron**: 1.6.9
**OS**: DESKTOP-EINVRVP
**Thrown From**: [atom-typescript](https://github.com/TypeStrong/atom-typescript) package 11.0.7

### Stack Trace

Uncaught TypeError: Cannot read property 'classList' of undefined

```
At C:\Users\Jenny\.atom\packages\atom-typescript\dist\main\atom\components\statusPanel.js:101

TypeError: Cannot read property 'classList' of undefined
    at HTMLElement._setPending (/packages/atom-typescript/dist/main/atom/components/statusPanel.js:101:34)
    at pendingTimeout.setTimeout (/packages/atom-typescript/dist/main/atom/components/statusPanel.js:107:53)
```

### Commands

```
     -0:56.2.0 editor:newline (input.hidden-input)
  2x -0:55 intentions:highlight (input.hidden-input)
 11x -0:44.7.0 core:move-left (input.hidden-input)
 12x -0:42.8.0 core:move-right (input.hidden-input)
     -0:38.9.0 core:backspace (input.hidden-input)
     -0:28.7.0 core:move-right (input.hidden-input)
     -0:27.7.0 intentions:highlight (input.hidden-input)
     -0:27.6.0 core:save (input.hidden-input)
     -0:22.4.0 core:backspace (input.hidden-input)
     -0:22 intentions:highlight (input.hidden-input)
     -0:21.9.0 core:save (input.hidden-input)
     -0:16.8.0 intentions:highlight (input.hidden-input)
     -0:16.6.0 core:save (input.hidden-input)
     -0:13.7.0 editor:newline (input.hidden-input)
     -0:07.5.0 intentions:highlight (input.hidden-input)
     -0:07.4.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-typescript 11.0.7 
atom-wordpress 0.3.0 
busy-signal 1.4.3 
intentions 1.1.5 
linter 2.2.0 
linter-ui-default 1.6.8 
seti-syntax 1.1.3 
seti-ui 1.9.0 
typescript-modules-helper 0.8.0 
wordpress-api 1.2.2 
wordpress-autocomplete 1.2.0 
wordpress-suite 1.1.1 
```

**Comment by douxsey** [comment]
+1
