### ISSUE TITLE
Uncaught SyntaxError: Invalid or unexpected token

### ISSUE THREAD

**Issue by FEAGRI** [TypeStrong/atom-typescript#1352]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.20.1 x64
**Electron**: 1.6.9
**OS**: Unknown Windows version
**Thrown From**: [atom-typescript](https://github.com/TypeStrong/atom-typescript) package 11.0.9

### Stack Trace

Uncaught SyntaxError: Invalid or unexpected token

```
At C:\Users\fernando\AppData\Local\atom\app-1.20.1\resources\app\src\native-compile-cache.js:97

SyntaxError: Invalid or unexpected token
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.20.1/resources/app/src/native-compile-cache.js:94:52)
    at Object.value [as .coffee] (~/AppData/Local/atom/app-1.20.1/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (~/AppData/Local/atom/app-1.20.1/resources/app/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.20.1/resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-typescript/dist/main/atom/views/renameView.js:5:12)
    at /packages/atom-typescript/dist/main/atom/views/renameView.js:95:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.20.1/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.20.1/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (~/AppData/Local/atom/app-1.20.1/resources/app/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.20.1/resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-typescript/dist/main/atomts.js:6:22)
    at /packages/atom-typescript/dist/main/atomts.js:207:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.20.1/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.20.1/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (~/AppData/Local/atom/app-1.20.1/resources/app/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.20.1/resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (~/AppData/Local/atom/app-1.20.1/resources/app/src/package.js:887:35)
    at Package.module.exports.Package.activateConfig (~/AppData/Local/atom/app-1.20.1/resources/app/src/package.js:301:18)
    at PackageManager.module.exports.PackageManager.packageHasSettings (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/settings-view/lib/package-manager.js:68:20)
    at PackageCard.hasSettings (~/AppData/Local/atom/app-1.20.1/resources/app/node_modules/settings-view/lib/package-card.js:793:40)
```

### Commands

```
     -1:11.9.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-clock 0.1.15 
atom-runner 2.7.1 
atom-typescript 11.0.9 
minimap-plus 4.29.2 
```

**Comment by lierdakil** [comment]
This is an issue with Atom's compilation cache that got corrupted for some reason. Reinstalling the package might help. If not, clearing the compilation cache manually should. Compilation cache is located in `$ATOM_USER_DIR/compile-cache/`. I have no idea where `$ATOM_USER_DIR` is on Windows, sorry.
