### ISSUE TITLE
Uncaught TypeError: editor.displayBuffer.getScrollTop is not a function

### ISSUE THREAD

**Issue by zhaozhanggg** [TypeStrong/atom-typescript#1377]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Microsoft Windows 10 Pro
**Thrown From**: [atom-typescript](https://github.com/TypeStrong/atom-typescript) package, v6.0.15

### Stack Trace

Uncaught TypeError: editor.displayBuffer.getScrollTop is not a function

```
At C:\Users\MM\.atom\packages\atom-typescript\dist\main\atom\tooltipManager.js:49

TypeError: editor.displayBuffer.getScrollTop is not a function
    at showExpressionType (C:\Users\MM\.atom\packages\atom-typescript\dist\main\atom\tooltipManager.js:49:45)
    at C:\Users\MM\.atom\packages\atom-typescript\dist\main\atom\tooltipManager.js:40:59
```

### Commands

```
     -1:35.5.0 core:save (atom-text-editor.editor.is-focused)
     -1:35.4.0 linter:lint (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "themes": [
      "one-dark-ui",
      "monokai"
    ],
    "disabledPackages": [
      "atom-terminal-panel"
    ]
  },
  "atom-typescript": {}
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
atom-beautify, v0.28.14
atom-typescript, v6.0.15
autocomplete-modules, v1.1.0
color-picker, v2.0.12
css-color-underline, v1.0.1
file-icons, v1.6.9
language-python-django-templates, v0.1.0
last-cursor-position, v0.9.0
linter, v1.6.0
linter-flake8, v1.6.1
minimap, v4.13.3
monokai, v0.18.0
python-isort, v0.0.7

# Dev
No dev packages
```

**Comment by lierdakil** [comment]
Both Atom and atom-typescript versions are horribly outdated. Please update Atom, then packages, then file a new issue if the problem persists.
