### ISSUE TITLE
Uncaught Error: Cannot find module 'lodash'

### ISSUE THREAD

**Issue by danielramirez-castor** [TypeStrong/atom-typescript#1383]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.22.1 x64
**Electron**: 1.6.15
**OS**: Unknown Windows version
**Thrown From**: [atom-typescript](https://github.com/TypeStrong/atom-typescript) package 11.0.10

### Stack Trace

Uncaught Error: Cannot find module 'lodash'

```
At module.js:472

Error: Cannot find module 'lodash'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.22.1/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.22.1/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.22.1/resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-typescript/dist/main/atomts.js:12:18)
    at /packages/atom-typescript/dist/main/atomts.js:209:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.22.1/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.22.1/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.22.1/resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (~/AppData/Local/atom/app-1.22.1/resources/app/src/package.js:903:35)
    at Package.module.exports.Package.activateConfig (~/AppData/Local/atom/app-1.22.1/resources/app/src/package.js:301:18)
    at PackageManager.module.exports.PackageManager.packageHasSettings (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/settings-view/lib/package-manager.js:68:20)
    at PackageCard.hasSettings (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/settings-view/lib/package-card.js:793:40)
    at PackageCard.updateSettingsState (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/settings-view/lib/package-card.js:438:22)
    at PackageCard.updateInterfaceState (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/settings-view/lib/package-card.js:430:18)
    at ~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/settings-view/lib/package-card.js:727:22
    at ~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/settings-view/lib/package-card.js:810:17
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at PackageManager.module.exports.PackageManager.emitPackageEvent (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/settings-view/lib/package-manager.js:703:33)
    at ~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/settings-view/lib/package-manager.js:542:32
    at exit (~/AppData/Local/atom/app-1.22.1/resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (~/AppData/Local/atom/app-1.22.1/resources/app/src/buffered-process.js:338:17)
    at ChildProcess.<anonymous> (~/AppData/Local/atom/app-1.22.1/resources/app/src/buffered-process.js:368:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

### Commands

```
     -7:51.3.0 settings-view:open (input.hidden-input)
     -5:38.6.0 core:backspace (input.hidden-input)
     -5:32.9.0 core:confirm (input.hidden-input)
     -2:32.7.0 tree-view:move (span.name.icon.icon-file-text)
  2x -2:31.3.0 core:move-left (input.hidden-input)
     -2:25.4.0 core:confirm (input.hidden-input)
     -2:20.7.0 tree-view:move (span.name.icon.icon-file-text)
     -2:19.6.0 core:move-left (input.hidden-input)
     -2:16 core:confirm (input.hidden-input)
     -2:04.2.0 find-and-replace:show (div.tool-panel.tree-view)
     -1:59 core:confirm (input.hidden-input)
     -1:57 core:move-left (input.hidden-input)
  2x -1:56.3.0 core:move-right (input.hidden-input)
  3x -1:55.3.0 core:confirm (input.hidden-input)
     -1:49.3.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-typescript 11.0.10 
highlight-selected 0.13.1 
minimap 4.29.7 
minimap-highlight-selected 4.6.1 
```

**Comment by lierdakil** [comment]
Well, it's in the dependencies, so I don't know why this happened. Try un-installing and re-installing the package, on occasion Atom just fails to install all dependencies for no apparent reason.

**Comment by danielramirez-castor** [comment]
It goes as it comes: out of nowhere... It just worked
