### ISSUE TITLE
Uncaught TypeError: Cannot read property 'classList' of undefined

### ISSUE THREAD

**Issue by pixelarbeit** [TypeStrong/atom-typescript#1388]
[Enter steps to reproduce:]

Not really sure. Just opened a TS file and scrolled through it.
Message keeps popping up.

Also pops up when saving a file.

**Atom**: 1.24.0-beta1 x64
**Electron**: 1.6.15
**OS**: Windows 10
**Thrown From**: [atom-typescript](https://github.com/TypeStrong/atom-typescript) package 11.0.10

### Stack Trace

Uncaught TypeError: Cannot read property 'classList' of undefined

```
At C:\Users\dekoc\.atom\packages\atom-typescript\dist\main\atom\components\statusPanel.js:101

TypeError: Cannot read property 'classList' of undefined
    at HTMLElement._setPending (/packages/atom-typescript/dist/main/atom/components/statusPanel.js:101:34)
    at pendingTimeout.setTimeout (/packages/atom-typescript/dist/main/atom/components/statusPanel.js:107:53)
```

### Commands

```
     -4:23.8.0 core:save (input.hidden-input)
 26x -4:22.7.0 core:move-left (input.hidden-input)
     -4:21.4.0 core:backspace (input.hidden-input)
  2x -4:20.8.0 core:move-right (input.hidden-input)
     -4:20.3.0 core:backspace (input.hidden-input)
     -4:19.7.0 core:save (input.hidden-input)
  4x -1:59 core:move-right (input.hidden-input)
  8x -1:57.9.0 core:backspace (input.hidden-input)
     -1:54.1.0 autocomplete-plus:cancel (input.hidden-input)
     -1:53.9.0 editor:consolidate-selections (input.hidden-input)
     -1:53.9.0 core:cancel (input.hidden-input)
     -1:53.7.0 core:move-down (input.hidden-input)
     -1:53.1.0 editor:move-to-end-of-screen-line (input.hidden-input)
 10x -1:52.8.0 core:move-left (input.hidden-input)
  2x -1:47.5.0 core:move-up (input.hidden-input)
     -1:44.1.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-autocomplete-php 0.25.6 
atom-beautify 0.30.9 
atom-ide-ui 0.7.0 
atom-sort-sass 0.2.1 
atom-typescript 11.0.10 
atom-wordpress 0.3.0 
autoclose-html 0.23.0 
autocomplete-paths 2.12.1 
autocomplete-wordpress-hooks 0.2.3 
busy 0.7.0 
color-picker 2.2.5 
docblockr 0.13.4 
emmet 2.4.3 
emmet-snippets-compatibility 1.0.6 
firewatch-syntax 1.1.1 
goto 1.8.3 
ide-php 0.7.4 
jquery-snippets 11.0.0 
language-blade 0.38.0 
language-log 1.9.0 
language-twig 1.6.3 
language-vue 0.23.1 
latex-plus 0.9.1 
linter 2.2.0 
livereload 0.4.4 
livestyle-atom 0.2.10 
markdown-themeable-pdf 1.2.0 
pdf-view 0.61.0 
php-getters-setters 0.5.5 
pigments 0.40.2 
platformio-ide-terminal 2.7.0 
qolor 0.4.2 
rest-client 1.3.1 
savey-wavey 0.3.0 
seti-icons 1.5.4 
snippets-package 0.0.0 
spacegray-dark-neue-syntax 1.4.2 
teletype 0.4.0 
wordpress-api 1.2.2 
wordpress-suite 1.2.0 
zentabs 0.8.9 
```

**Comment by lierdakil** [comment]
Pretty sure this is fixed with v12. Feel free to open new issues in case it's still happening on latest.
