### ISSUE TITLE
Intentions for certain lint code-fixes doesn't work anymore

### ISSUE THREAD

**Issue by noseglid** [TypeStrong/atom-typescript#1411]
I'm using [tslint-language-server](https://github.com/angelozerr/tslint-language-service) and it provides certain code fixes. One of them is for [ordered-imports](https://palantir.github.io/tslint/rules/ordered-imports/).

This used to work, but stopped at some point quite recently. Other code fixes (which is from `tslint-language-service` and `tsserver` itself still works).

Everytime I try `intentions:show` while on one of these I get this error in the devtools of atom:

```
Uncaught (in promise) Error: Error processing request. Debug Failure. False expression.
Error: Debug Failure. False expression.
    at getClass (/Users/noseglid/devel/storytel/storytel-bridge-web/node_modules/typescript/lib/tsserver.js:77705:22)
    at /Users/noseglid/devel/storytel/storytel-bridge-web/node_modules/typescript/lib/tsserver.js:77693:46
    at Function.ChangeTracker.with (/Users/noseglid/devel/storytel/storytel-bridge-web/node_modules/typescript/lib/tsserver.js:76585:17)
    at Object.getCodeActions (/Users/noseglid/devel/storytel/storytel-bridge-web/node_modules/typescript/lib/tsserver.js:77692:64)
    at /Users/noseglid/devel/storytel/storytel-bridge-web/node_modules/typescript/lib/tsserver.js:77219:33
    at Object.forEach (/Users/noseglid/devel/storytel/storytel-bridge-web/node_modules/typescript/lib/tsserver.js:1431:30)
    at Object.getFixes (/Users/noseglid/devel/storytel/storytel-bridge-web/node_modules/typescript/lib/tsserver.js:77218:16)
    at /Users/noseglid/devel/storytel/storytel-bridge-web/node_modules/typescript/lib/tsserver.js:83366:35
    at Object.flatMap (/Users/noseglid/devel/storytel/storytel-bridge-web/node_modules/typescript/lib/tsserver.js:1698:25)
    at Object.getCodeFixesAtPosition (/Users/noseglid/devel/storytel/storytel-bridge-web/node_modules/typescript/lib/tsserver.js:83364:23)
    at Object.proxy.getCodeFixesAtPosition (/Users/noseglid/devel/storytel/storytel-bridge-web/node_modules/tslint-language-service/out/src/index.js:334:31)
    at IOSession.Session.getCodeFixes (/Users/noseglid/devel/storytel/storytel-bridge-web/node_modules/typescript/lib/tsserver.js:90388:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/Users/noseglid/devel/storytel/storytel-bridge-web/node_modules/typescript/lib/tsserver.js:89292:61)
    at /Users/noseglid/devel/storytel/storytel-bridge-web/node_modules/typescript/lib/tsserver.js:90553:88
    at IOSession.Session.executeWithRequestId (/Users/noseglid/devel/storytel/storytel-bridge-web/node_modules/typescript/lib/tsserver.js:90544:28)
    at IOSession.Session.executeCommand (/Users/noseglid/devel/storytel/storytel-bridge-web/node_modules/typescript/lib/tsserver.js:90553:33)
    at IOSession.Session.onMessage (/Users/noseglid/devel/storytel/storytel-bridge-web/node_modules/typescript/lib/tsserver.js:90573:35)
    at Interface.<anonymous> (/Users/noseglid/devel/storytel/storytel-bridge-web/node_modules/typescript/lib/tsserver.js:91774:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:188:7)
    at Interface._onLine (readline.js:247:10)
    at Interface.<anonymous> (readline.js:384:12)
    at Array.forEach (native)
    at Interface._normalWrite (readline.js:383:11)
    at Socket.ondata (readline.js:107:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:551:20)
    at getClass (/Users/noseglid/devel/storytel/storytel-bridge-web/node_modules/typescript/lib/tsserver.js:77705:22)
    at /Users/noseglid/devel/storytel/storytel-bridge-web/node_modules/typescript/lib/tsserver.js:77693:46
    at Function.ChangeTracker.with (/Users/noseglid/devel/storytel/storytel-bridge-web/node_modules/typescript/lib/tsserver.js:76585:17)
    at Object.getCodeActions (/Users/noseglid/devel/storytel/storytel-bridge-web/node_modules/typescript/lib/tsserver.js:77692:64)
    at /Users/noseglid/devel/storytel/storytel-bridge-web/node_modules/typescript/lib/tsserver.js:77219:33
    at Object.forEach (/Users/noseglid/devel/storytel/storytel-bridge-web/node_modules/typescript/lib/tsserver.js:1431:30)
    at Object.getFixes (/Users/noseglid/devel/storytel/storytel-bridge-web/node_modules/typescript/lib/tsserver.js:77218:16)
    at /Users/noseglid/devel/storytel/storytel-bridge-web/node_modules/typescript/lib/tsserver.js:83366:35
    at Object.flatMap (/Users/noseglid/devel/storytel/storytel-bridge-web/node_modules/typescript/lib/tsserver.js:1698:25)
    at Object.getCodeFixesAtPosition (/Users/noseglid/devel/storytel/storytel-bridge-web/node_modules/typescript/lib/tsserver.js:83364:23)
    at Object.proxy.getCodeFixesAtPosition (/Users/noseglid/devel/storytel/storytel-bridge-web/node_modules/tslint-language-service/out/src/index.js:334:31)
    at IOSession.Session.getCodeFixes (/Users/noseglid/devel/storytel/storytel-bridge-web/node_modules/typescript/lib/tsserver.js:90388:64)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/Users/noseglid/devel/storytel/storytel-bridge-web/node_modules/typescript/lib/tsserver.js:89292:61)
    at /Users/noseglid/devel/storytel/storytel-bridge-web/node_modules/typescript/lib/tsserver.js:90553:88
    at IOSession.Session.executeWithRequestId (/Users/noseglid/devel/storytel/storytel-bridge-web/node_modules/typescript/lib/tsserver.js:90544:28)
    at IOSession.Session.executeCommand (/Users/noseglid/devel/storytel/storytel-bridge-web/node_modules/typescript/lib/tsserver.js:90553:33)
    at IOSession.Session.onMessage (/Users/noseglid/devel/storytel/storytel-bridge-web/node_modules/typescript/lib/tsserver.js:90573:35)
    at Interface.<anonymous> (/Users/noseglid/devel/storytel/storytel-bridge-web/node_modules/typescript/lib/tsserver.js:91774:27)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:188:7)
    at Interface._onLine (readline.js:247:10)
    at Interface.<anonymous> (readline.js:384:12)
    at Array.forEach (native)
    at Interface._normalWrite (readline.js:383:11)
    at Socket.ondata (readline.js:107:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:551:20)
    at MessageStream.TypescriptServiceClient.onMessage (/Users/noseglid/.atom/packages/atom-typescript/dist/client/client.js:49:36)
    at emitOne (events.js:96:13)
    at MessageStream.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at MessageStream.Readable.push (_stream_readable.js:134:10)
    at MessageStream.Transform.push (_stream_transform.js:128:32)
    at MessageStream._transform (/Users/noseglid/.atom/packages/atom-typescript/dist/client/client.js:182:22)
    at MessageStream.Transform._read (_stream_transform.js:167:10)
    at MessageStream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:332:12)
    at writeOrBuffer (_stream_writable.js:318:5)
    at MessageStream.Writable.write (_stream_writable.js:245:11)
    at LineStream.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at LineStream.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at LineStream.Readable.push (_stream_readable.js:134:10)
    at LineStream.Transform.push (_stream_transform.js:128:32)
    at LineStream._pushBuffer (/Users/noseglid/.atom/packages/atom-typescript/node_modules/byline/lib/byline.js:126:17)
    at LineStream._transform (/Users/noseglid/.atom/packages/atom-typescript/node_modules/byline/lib/byline.js:117:8)
    at LineStream.Transform._read (_stream_transform.js:167:10)
    at LineStream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:332:12)
    at writeOrBuffer (_stream_writable.js:318:5)
    at LineStream.Writable.write (_stream_writable.js:245:11)
    at Socket.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:551:20)
```

**Comment by lierdakil** [comment]
Sorry, but why are you reporting this issue here of all places? We don't provide support for tslint-language-service. See https://github.com/angelozerr/tslint-language-service/issues/60

**Comment by noseglid** [comment]
I see. I was unclear exactly which part of the chain was responsible.
Looks to be something in the `tslint-language-service` integration with tsserver. I'll monitor that issue you linked. Thanks for your reply!

**Comment by lierdakil** [comment]
You're welcome.

Just so you know, I found that issue [with a straightforward Google search of `tslint-language-service "Error processing request. Debug Failure. False expression."`](https://www.google.com/search?q=tslint-language-service+"Error+processing+request.+Debug+Failure.+False+expression."). FWIW, I would imagine you could've done the same in a fraction of the time it took you to file this issue. No offence.

**Comment by noseglid** [comment]
Oh yeah, certainly. I thought you wanted to know though as spewing errors in the console can't be behaviour you're aiming for.

**Comment by lierdakil** [comment]
I would imagine spewing errors in the console is way better than failing silently. And when third-party code misbehaves, it's either one or the other I'm afraid.

Anyway, thanks for taking time to report the issue. Sorry we can't do anything about it on our side.
