### ISSUE TITLE
Uncaught TypeError: Cannot read property 'includes' of undefined

### ISSUE THREAD

**Issue by MaximBatanov** [TypeStrong/atom-typescript#1437]
[Enter steps to reproduce:]

1. It happens when you type something or save

**Atom**: 1.28.0 x64
**Electron**: 2.0.3
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [atom-typescript](https://github.com/TypeStrong/atom-typescript) package 12.6.0

### Stack Trace

Uncaught TypeError: Cannot read property 'includes' of undefined

```
At C:\Users\admin\.atom\packages\atom-typescript\dist\main\errorPusher.js:60

TypeError: Cannot read property 'includes' of undefined
    at ErrorPusher.pushErrors (/packages/atom-typescript/dist/main/errorPusher.js:60:59)
    at invokeFunc (/packages/atom-typescript/node_modules/lodash/lodash.js:10333:23)
    at trailingEdge (/packages/atom-typescript/node_modules/lodash/lodash.js:10382:18)
    at timerExpired (/packages/atom-typescript/node_modules/lodash/lodash.js:10370:18)
```

### Commands

```
  2x -5:08.5.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -2:22.3.0 intentions:highlight (input.hidden-input)
     -2:22.2.0 core:save (input.hidden-input)
     -1:38.1.0 editor:select-to-first-character-of-line (input.hidden-input)
     -1:37.9.0 intentions:highlight (input.hidden-input)
     -1:37.8.0 core:copy (input.hidden-input)
     -1:37.3.0 core:move-right (input.hidden-input)
     -1:36.9.0 editor:newline (input.hidden-input)
     -1:28.6.0 intentions:highlight (input.hidden-input)
     -1:28.4.0 core:save (input.hidden-input)
     -1:21 intentions:highlight (input.hidden-input)
     -1:20.9.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-typescript 12.6.0 
busy-signal 1.4.3 
git-history 3.3.0 
git-plus 7.11.0 
intentions 1.1.5 
linter 2.2.0 
linter-tslint 1.9.1 
linter-ui-default 1.7.1 
split-diff 1.5.2 
```

**Comment by lierdakil** [comment]
Does the problem persist after restarting Atom?

**Comment by Senne** [comment]
Yes

**Comment by MaximBatanov** [comment]
Yes

**Comment by roberto-naharro** [comment]
It happens even only typing something in the editor

**Comment by lierdakil** [comment]
Thanks for reporting, working on a fix now.

**Comment by roberto-naharro** [comment]
It's solved, thank you for the rush!
