### ISSUE TITLE
Something went wrong, see details below.

### ISSUE THREAD

**Issue by binoysarker** [TypeStrong/atom-typescript#1448]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.30.0 x64
**Electron**: 2.0.5
**OS**: Linux Mint
**Thrown From**: [atom-typescript](https://github.com/TypeStrong/atom-typescript) package 12.6.3

### Stack Trace

Something went wrong, see details below.

```
At Unrecognized JSON command: organizeImports

Error: Unrecognized JSON command: organizeImports
    at TypescriptServiceClient.onResponse (/packages/atom-typescript/dist/client/client.js:117:28)
    at MessageStream.TypescriptServiceClient.onMessage (/packages/atom-typescript/dist/client/client.js:64:22)
    at emitOne (events.js:116:13)
    at MessageStream.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at MessageStream.Readable.push (_stream_readable.js:208:10)
    at MessageStream.Transform.push (_stream_transform.js:147:32)
    at MessageStream._transform (/packages/atom-typescript/dist/client/client.js:193:22)
    at MessageStream.Transform._read (_stream_transform.js:186:10)
    at MessageStream.Transform._write (_stream_transform.js:174:12)
    at doWrite (_stream_writable.js:387:12)
    at writeOrBuffer (_stream_writable.js:373:5)
    at MessageStream.Writable.write (_stream_writable.js:290:11)
    at LineStream.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at LineStream.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at LineStream.Readable.push (_stream_readable.js:208:10)
    at LineStream.Transform.push (_stream_transform.js:147:32)
    at LineStream._pushBuffer (/packages/atom-typescript/node_modules/byline/lib/byline.js:126:17)
    at LineStream._transform (/packages/atom-typescript/node_modules/byline/lib/byline.js:117:8)
    at LineStream.Transform._read (_stream_transform.js:186:10)
    at LineStream.Transform._write (_stream_transform.js:174:12)
    at doWrite (_stream_writable.js:387:12)
    at writeOrBuffer (_stream_writable.js:373:5)
    at LineStream.Writable.write (_stream_writable.js:290:11)
    at Socket.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
```

### Commands

```
     -0:55.8.0 autocomplete-plus:activate (input.hidden-input)
     -0:44.6.0 autocomplete-plus:confirm (input.hidden-input)
     -0:44.5.0 editor:newline (input.hidden-input)
     -0:33.9.0 intentions:highlight (input.hidden-input)
     -0:33.6.0 core:undo (input.hidden-input)
     -0:32.7.0 editor:select-to-beginning-of-word (input.hidden-input)
     -0:31.9.0 core:backspace (input.hidden-input)
     -0:31.6.0 intentions:highlight (input.hidden-input)
     -0:31.4.0 autocomplete-plus:activate (input.hidden-input)
     -0:14.5.0 core:move-right (input.hidden-input)
     -0:14 intentions:highlight (input.hidden-input)
     -0:13.5.0 core:cut (input.hidden-input)
     -0:08.4.0 intentions:highlight (input.hidden-input)
     -0:07.8.0 command-palette:toggle (input.hidden-input)
     -0:06.0 core:confirm (input.hidden-input)
     -0:06.0 typescript:organize-imports (input.hidden-input)
```

### Non-Core Packages

```
atom-autocomplete-php 0.25.6 
atom-beautify 0.33.0 
atom-save-all 0.4.1 
atom-typescript 12.6.3 
autocomplete-modules 2.2.0 
autocomplete-paths 2.12.2 
busy-signal 1.4.3 
emmet 2.4.3 
file-icons 2.1.24 
highlight-selected 0.14.0 
intentions 1.1.5 
linter 2.2.0 
linter-ui-default 1.7.1 
minimap 4.29.8 
open-recent 5.0.0 
pigments 0.40.2 
platformio-ide-terminal 2.8.4 
seti-syntax 1.2.0 
seti-ui 1.11.0 
sync-settings 0.8.6 
```

**Comment by lierdakil** [comment]
If I had to guess, probably an older TypeScript version which doesn't have 'organize imports' feature.

**Comment by senyaak** [comment]
Have this problem with ts 1.8.9 when try to f12. The `reference` directive only is used for import.
It seems that `reference` can't be properly resolved. This also causes a lot of warnings in linter

**Comment by lierdakil** [comment]
@senyaak, pretty sure you've got a different issue. Atom is at times quite silly at finding the relevant issues and points to the wrong place entirely. Please copy the error report and open a new issue (there's a small clipboard-looking icon near the "view issue" button, which copies the complete report into the clipboard when clicked on)
