### ISSUE TITLE
Error: Cannot find module '../lib/tsserver.js'

### ISSUE THREAD

**Issue by DaveClissold** [TypeStrong/atom-typescript#1449]
Am getting the following error after installing the package. I am using TypeScript 2.8.3 via create-react-native-app

```
Last output from tsserver:
module.js:545
    throw err;
    ^
Error: Cannot find module '../lib/tsserver.js'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Fleyver/app/front-ts/node_modules/typescript/bin/tsserver:2:1)
    at Object.<anonymous> (/Fleyver/app/front-ts/node_modules/typescript/bin/tsserver:4:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
exited with code: 1
```

**Comment by lierdakil** [comment]
Hi. Sorry, it seems your installation is broken somewhat. At least the error is apparently thrown from tsserver itself, and not from anywhere in Atom-TypeScript. Try reinstalling typescript manually (via `npm install typescript` for example)
