### ISSUE TITLE
Uncaught RangeError: Array buffer allocation failed

### ISSUE THREAD

**Issue by droseb** [TypeStrong/atom-typescript#1452]
Hello!

this is my issues

**Atom**: 1.31.1 x64
**Electron**: 2.0.7
**OS**: Unknown Windows version
**Thrown From**: [atom-typescript](https://github.com/TypeStrong/atom-typescript) package 12.6.3

### Stack Trace

Uncaught RangeError: Array buffer allocation failed

```
At buffer.js:38

RangeError: Array buffer allocation failed
    at new ArrayBuffer (<anonymous>)
    at typedArrayConstructByLength (<anonymous>)
    at new Uint8Array (native)
    at new FastBuffer (buffer.js:38:5)
    at Function.Buffer.alloc (buffer.js:245:10)
    at fs.readFile (ELECTRON_ASAR.js:530:29)
    at /packages/atom-typescript/node_modules/resolve/lib/async.js:125:13
    at /packages/atom-typescript/node_modules/resolve/lib/async.js:10:20
    at ELECTRON_ASAR.js:294:9
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

### Commands

```
     -6:52.5.0 core:move-down (input.hidden-input)
  2x -6:51.9.0 core:backspace (input.hidden-input)
 19x -6:49.3.0 core:move-down (input.hidden-input)
 27x -6:47.9.0 core:move-up (input.hidden-input)
 10x -6:45.8.0 core:move-down (input.hidden-input)
     -6:37.7.0 core:move-up (input.hidden-input)
 12x -6:36.5.0 core:move-down (input.hidden-input)
 25x -6:34 editor:select-to-beginning-of-word (input.hidden-input)
undefined -6:32.7.0 core:select-left (input.hidden-input)
     -6:26 editor:toggle-line-comments (input.hidden-input)
     -6:25.3.0 core:save (input.hidden-input)
     -4:48.8.0 autocomplete-plus:confirm (input.hidden-input)
     -4:48.7.0 autocomplete-plus:activate (atom-text-editor.editor.is-focused)
     -0:27.1.0 pane:show-next-recently-used-item (input.hidden-input)
     -0:27 pane:move-active-item-to-top-of-stack (input.hidden-input)
     -0:17.2.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
an-old-hope-syntax 1.0.4 
atom-css-comb 3.3.1 
atom-ide-ui 0.13.0 
atom-ternjs 0.18.3 
atom-typescript 12.6.3 
autocomplete-java 1.2.7 
css-color-name 0.4.0 
file-icons 2.1.25 
ide-typescript 0.7.6 
indent-guide-improved 1.4.13 
javascript-snippets 1.2.1 
styri-syntax 0.2.0 
```

**Comment by lierdakil** [comment]
This seems to be thrown from the depths of Atom's internals (or, more precisely, Node's), and it seems to complain about being unable to allocate memory. My guess would be either your system memory was low at the moment, your Atom setup is somehow corrupted, or your system is completely unstable due to hardware problems. None of which sounds like a problem with the package. Please feel free to correct me if I'm wrong.
