### ISSUE TITLE
Type errors from lib.*.d.ts not always detected

### ISSUE THREAD

**Issue by trusktr** [TypeStrong/atom-typescript#1460]
I've got some type errors from `lib.*.d.ts` files (f.e. `lib.dom.d.ts`). When I run `tsc` to typecheck from command line, I get the type errors. However `atom-typescript` will not show any errors unless I open the lib.*.d.ts file in Atom, at which point `atom-typescript` will notice and begin showing me the type errors now that I have the lib file.

tsconfig:

```json
{
  "compilerOptions": {
    "target": "es2017",
    "lib": ["es6", "es7", "es2016", "es2017", "dom"],
    "module": "commonjs",
    "moduleResolution": "node",
    "declaration": true,
    "emitDecoratorMetadata": true,
    "jsx": "react",
    "experimentalDecorators": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "noImplicitReturns": true,
    "noImplicitAny": false,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "preserveConstEnums": true,
    "pretty": true,
    "strictNullChecks": true,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "sourceMap": true,
    "outDir": "./dist/out",
    "paths": {
      "*": ["*"]
    },
    "baseUrl": "./src"
  },
  "compileOnSave": true,
  "include": ["src/**/*"]
}
```

Any ideas why this happens?

**Comment by lierdakil** [comment]
A couple things to check for:
* Are your `*.d.ts` files part of your project (via `include` or `files`)? If not, TypeScript won't check those as part of your project, obviously.
* Do you have `skipLibCheck: true` in tsconfig.json? This will prevent TypeScript from checking `*.d.ts` files
* Do you expect TypeScript to always check your whole project? This won't happen for performance reasons. With Atom-Typescript, you can force a complete typecheck of the project by running `typescript:check-all-files` command  (bound to F7 by default) -- it might take a while depending on the size of your project and whether you're using any language service plugins.

**Comment by trusktr** [comment]
> Are your *.d.ts files part of your project (via include or files)

Oh, that may be it. My tsconfig has only `"include": ["src/**/*"]`, but I figured it would be able to follow imports (f.e. fine `@types/react` when importing React). I wasn't thinking about globals like DOM APIs though.

So I should list `node_modules/**/*.d.ts` in the `include` as well?

**Comment by trusktr** [comment]
If I include `node_modules/**/*.d.ts`, that might include dependencies of dependencies that I may not be using. What do you recommend.

Another question is, I already have `"lib": ["es6", "es7", "es2016", "es2017", "dom"],` in my `tsconfig`, so shouldn't that be enough to tell TypeScript which `.d.ts` files it should look at in `node_modules` without me adding `node_modules/**/*.d.ts`?

Here's my tsconfig:

```json
{
  "compilerOptions": {
    "target": "es2017",
    "lib": ["es6", "es7", "es2016", "es2017", "dom"],
    "module": "commonjs",
    "moduleResolution": "node",
    "declaration": true,
    "emitDecoratorMetadata": true,
    "jsx": "react",
    "experimentalDecorators": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "noImplicitReturns": true,
    "noImplicitAny": false,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "preserveConstEnums": true,
    "pretty": true,
    "strictNullChecks": true,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "sourceMap": true,
    "outDir": "./dist/out",
    "paths": {
      "*": ["*"]
    },
    "baseUrl": "./src"
  },
  "compileOnSave": true,
  "include": ["src/**/*"]
}
```

I would think that's enough for TypeScript (and atom-typescript) to detect all type as needed?

**Comment by lierdakil** [comment]
Okay... I might be misunderstanding the issue? Where do you expect to see type errors exactly? I've understood your OP as "atom-typescript doesn't find type errors in d.ts files unless I open those", is that wrong?

No, you do not need to add any files from `node_modules` to your project. In fact, this is strongly discouraged for obvious reasons.

Yes, TypeScript should automatically bring it's own lib definitions into scope, no additional manipulations necessary (apart from adding relevant libraries to `lib`).

One note though, you *do not* usually want to add *everything* to `lib`. `es2017` already includes `es2016`, `es6` already includes `dom`, and there's no `es7`. Here are all the lib definitions available in TypeScript 3.1.6: https://github.com/Microsoft/TypeScript/tree/v3.1.6/lib

Also, I'm a bit confused about `paths` and `baseUrl`, are you sure you need those? Because it messes a fair bit with module resolution and hence shouldn't be used unless really necessary.

**Comment by trusktr** [comment]
> I've understood your OP as "atom-typescript doesn't find type errors in d.ts files unless I open those", is that wrong?

Atom was reporting errors in _my own_ project files related to the lib files (as if I was not writing my code properly based on what the the lib file declarations dictate), but the errors went away when I opened the lib files and it Atom seed to realize that my code was correct. It is as if it had a wrong definition of lib.dom, until I opened the file.

> Yes, TypeScript should automatically bring it's own lib definitions into scope

I think the problem is related to that.

Every time I ran `tsc` at the command line, I didn't get any errors in my own code, while I did see errors inside Atom in my own code (until I opened up the lib.dom.d.ts file).

Tsc runs only on saved content of my files, while atom-typescript is able to typecheck files that I have not saved yet, so the type checking mechanism is not quite the same between atom-typescript and tsc.

Interestingly, I've noticed this behavior with ide-typescript too (it also does things tsc can not do like check the whole project with files in unsaved state), though it happens much much more with ide-typescript than with atom-typescript. It has only happened a couple times with atom-typescript, and overall my experience with atom-typescript has been much muuuch more solid.

I'll try to post back if it happens again, and try to think of what I may have done to trigger it.

**Comment by trusktr** [comment]
I think I may have found myself in a broken situation again.

The following is what I see, and you'll notice in the command line there's no errors (`npm run typecheck` runs `tsc -p ./tsconfig.json --noEmit && :`), but the UI shows a whole bunch of errors:

![screen shot 2018-11-13 at 5 04 29 pm](https://user-images.githubusercontent.com/297678/48453051-ad00ee80-e766-11e8-9449-d9c3f6f7bbfe.png)

The one that says `Block-scoped variable 'nextContinuationTokenNode' used before its declaration` is definitely wrong.

What can I do while I'm in this state to debug? Is there some way to gather some info that you'd find useful?

**Comment by trusktr** [comment]
I do see the following TypeScript-related error in the console:

```
Error: Error processing request. length < 0
Error: length < 0
    at Object.createTextSpan (/Users/trusktr/src/my-project/node_modules/typescript/lib/tsserver.js:12220:19)
    at TextChange.getTextChangeRange (/Users/trusktr/src/my-project/node_modules/typescript/lib/tsserver.js:123373:52)
    at ScriptVersionCache.getTextChangesBetweenVersions (/Users/trusktr/src/my-project/node_modules/typescript/lib/tsserver.js:123446:66)
    at LineIndexSnapshot.getChangeRange (/Users/trusktr/src/my-project/node_modules/typescript/lib/tsserver.js:123493:43)
    at SyntaxTreeCache.getCurrentSourceFile (/Users/trusktr/src/my-project/node_modules/typescript/lib/tsserver.js:114402:48)
    at Object.getNavigationTree (/Users/trusktr/src/my-project/node_modules/typescript/lib/tsserver.js:114986:71)
    at IOSession.Session.getNavigationTree (/Users/trusktr/src/my-project/node_modules/typescript/lib/tsserver.js:122762:44)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/Users/trusktr/src/my-project/node_modules/typescript/lib/tsserver.js:121729:61)
    at /Users/trusktr/src/my-project/node_modules/typescript/lib/tsserver.js:123062:88
    at IOSession.Session.executeWithRequestId (/Users/trusktr/src/my-project/node_modules/typescript/lib/tsserver.js:123053:28)
    at IOSession.Session.executeCommand (/Users/trusktr/src/my-project/node_modules/typescript/lib/tsserver.js:123062:33)
    at IOSession.Session.onMessage (/Users/trusktr/src/my-project/node_modules/typescript/lib/tsserver.js:123082:35)
    at Interface.<anonymous> (/Users/trusktr/src/my-project/node_modules/typescript/lib/tsserver.js:124345:27)
    at emitOne (events.js:116:13)
    at Interface.emit (events.js:211:7)
    at Interface._onLine (readline.js:282:10)
    at Interface._normalWrite (readline.js:424:12)
    at Socket.ondata (readline.js:141:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
    at Object.createTextSpan (/Users/trusktr/src/my-project/node_modules/typescript/lib/tsserver.js:12220:19)
    at TextChange.getTextChangeRange (/Users/trusktr/src/my-project/node_modules/typescript/lib/tsserver.js:123373:52)
    at ScriptVersionCache.getTextChangesBetweenVersions (/Users/trusktr/src/my-project/node_modules/typescript/lib/tsserver.js:123446:66)
    at LineIndexSnapshot.getChangeRange (/Users/trusktr/src/my-project/node_modules/typescript/lib/tsserver.js:123493:43)
    at SyntaxTreeCache.getCurrentSourceFile (/Users/trusktr/src/my-project/node_modules/typescript/lib/tsserver.js:114402:48)
    at Object.getNavigationTree (/Users/trusktr/src/my-project/node_modules/typescript/lib/tsserver.js:114986:71)
    at IOSession.Session.getNavigationTree (/Users/trusktr/src/my-project/node_modules/typescript/lib/tsserver.js:122762:44)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/Users/trusktr/src/my-project/node_modules/typescript/lib/tsserver.js:121729:61)
    at /Users/trusktr/src/my-project/node_modules/typescript/lib/tsserver.js:123062:88
    at IOSession.Session.executeWithRequestId (/Users/trusktr/src/my-project/node_modules/typescript/lib/tsserver.js:123053:28)
    at IOSession.Session.executeCommand (/Users/trusktr/src/my-project/node_modules/typescript/lib/tsserver.js:123062:33)
    at IOSession.Session.onMessage (/Users/trusktr/src/my-project/node_modules/typescript/lib/tsserver.js:123082:35)
    at Interface.<anonymous> (/Users/trusktr/src/my-project/node_modules/typescript/lib/tsserver.js:124345:27)
    at emitOne (events.js:116:13)
    at Interface.emit (events.js:211:7)
    at Interface._onLine (readline.js:282:10)
    at Interface._normalWrite (readline.js:424:12)
    at Socket.ondata (readline.js:141:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
    at TypescriptServiceClient.onResponse (/Users/trusktr/src/trusktr+dotfiles/.atom/packages/atom-typescript/dist/client/client.js:117:28)
    at MessageStream.TypescriptServiceClient.onMessage (/Users/trusktr/src/trusktr+dotfiles/.atom/packages/atom-typescript/dist/client/client.js:64:22)
    at emitOne (events.js:116:13)
    at MessageStream.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at MessageStream.Readable.push (_stream_readable.js:208:10)
    at MessageStream.Transform.push (_stream_transform.js:147:32)
    at MessageStream._transform (/Users/trusktr/src/trusktr+dotfiles/.atom/packages/atom-typescript/dist/client/client.js:193:22)
    at MessageStream.Transform._read (_stream_transform.js:186:10)
    at MessageStream.Transform._write (_stream_transform.js:174:12)
    at doWrite (_stream_writable.js:387:12)
    at writeOrBuffer (_stream_writable.js:373:5)
    at MessageStream.Writable.write (_stream_writable.js:290:11)
    at LineStream.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at LineStream.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at LineStream.Readable.push (_stream_readable.js:208:10)
    at LineStream.Transform.push (_stream_transform.js:147:32)
    at LineStream._pushBuffer (/Users/trusktr/src/trusktr+dotfiles/.atom/packages/atom-typescript/node_modules/byline/lib/byline.js:126:17)
    at LineStream._transform (/Users/trusktr/src/trusktr+dotfiles/.atom/packages/atom-typescript/node_modules/byline/lib/byline.js:117:8)
    at LineStream.Transform._read (_stream_transform.js:186:10)
    at LineStream.Transform._write (_stream_transform.js:174:12)
    at doWrite (_stream_writable.js:387:12)
    at writeOrBuffer (_stream_writable.js:373:5)
    at LineStream.Writable.write (_stream_writable.js:290:11)
    at Socket.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20) "/Users/trusktr/src/my-project/src/tiles/S3TileServiceClient.worker.ts"
```

where `my-project` is not the actual name of the project, to keep privacy. The `trusktr+dotfiles/.atom` folder is where my `.atom` folder is symlinked to.

**Comment by trusktr** [comment]
Seems the only way to recover was to restart the Atom window.

**Comment by lierdakil** [comment]
Yes, that's how it is currently. The last PR on this repo adds a dedicated
"restart typescript language server" command, but that is as of right now
still unreleased (some major architectural changes were required, still
finding subtle bugs occasionally after almost completely rewriting some
critical components)

ср, 14 нояб. 2018 г., 4:17 Joe Pea <notifications@github.com>:

**Comment by trusktr** [comment]
Cool, I'll wait for that to see how things change.

I encountered this again. I can reproduce it consistently at the moment, by running "clear errors" then "check all files". Soon as I open the file in node_modules, it goes away.

**Comment by trusktr** [comment]
I think there may be a few issues that I've been experiencing. This time, a type definition of an `npm link`ed module was outdated, and although I opened and the file (`cmd+click` to take me there) and I saw the type definition was correct, I still kept getting the type error in my project. Of course a restart fixed it.

**Comment by cwohlman** [comment]
@lierdakil I'm running into a similar issue and not quite clear on something: Is there any way to get atom-typescript to parse `.d.ts` files without opening them (and also without parsing all typescript files in my project)?

**Comment by lierdakil** [comment]
@cwohlman -- it *really* should do it automatically. I have no idea what goes wrong for you. A detailed reproduction guide might help, but tbh, I'm suspecting a subtle configuration error somewhere. I use atom-typescript myself quite extensively and I didn't run into anything like described here (although tsserver might need an occasional encouragement in the form of `typescript:check-all-files` to pull in changes)

**Comment by cwohlman** [comment]
Adding `typescript:check-all-files` seems to do the trick.

**Comment by trusktr** [comment]
I've been having these issues sometimes lately (switching between branches for example). What I do to work around it is run the following sequence of commands:

```
typescript:clear-errors
typescript:reload-projects
typescript:check-all-files
```

Sometimes running

```
typescript:clear-errors
typescript:check-all-files
```

isn't enough it seems.

**Comment by lierdakil** [comment]
`typescript:restart-all-servers` should also do the trick in most cases.

**Comment by theangular** [comment]
+1 https://typescripter.space/questions/atom-typescript-does-not-always-successfully-compile-all-typescript-files-to-javascript
