### ISSUE TITLE
Atom-Typescript error: Unexpected token } in JSON at position 713

### ISSUE THREAD

**Issue by DrNecromant** [TypeStrong/atom-typescript#1468]
[Enter steps to reproduce:]

1. Open any typescript file in Atom

**Atom**: 1.32.2 x64
**Electron**: 2.0.9
**OS**: Mac OS X 10.14.1
**Thrown From**: [atom-typescript](https://github.com/TypeStrong/atom-typescript) package 12.7.0

### Stack Trace

Atom-Typescript error: Unexpected token } in JSON at position 713

```
At SyntaxError: Unexpected token } in JSON at position 713

SyntaxError: Unexpected token } in JSON at position 713
    at JSON.parse (<anonymous>)
    at parse (/packages/atom-typescript/node_modules/tsconfig/dist/tsconfig.js:135:17)
    at /packages/atom-typescript/node_modules/tsconfig/dist/tsconfig.js:116:32
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
```

### Commands

```
```

### Non-Core Packages

```
atom-typescript 12.7.0 
autocomplete-python 1.11.0 
busy-signal 1.4.3 
intentions 1.1.5 
linter 2.2.0 
linter-sass-lint 1.8.3 
linter-ui-default 1.7.1 
python-indent 1.1.6 
script 3.18.1 
```

**Comment by DrNecromant** [comment]
Not reproduced after re-installed npm packages

**Comment by pierreglibert** [comment]
Reinstall it solve this problem :)
