### ISSUE TITLE
Atom-Typescript error: Unexpected token } in JSON at position 365

### ISSUE THREAD

**Issue by pierreglibert** [TypeStrong/atom-typescript#1469]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.32.2 x64
**Electron**: 2.0.9
**OS**: Mac OS X 10.14.1
**Thrown From**: [atom-typescript](https://github.com/TypeStrong/atom-typescript) package 12.7.0

### Stack Trace

Atom-Typescript error: Unexpected token } in JSON at position 365

```
At SyntaxError: Unexpected token } in JSON at position 365

SyntaxError: Unexpected token } in JSON at position 365
    at JSON.parse (<anonymous>)
    at parse (/packages/atom-typescript/node_modules/tsconfig/dist/tsconfig.js:135:17)
    at /packages/atom-typescript/node_modules/tsconfig/dist/tsconfig.js:116:32
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
```

### Commands

```
     -9:35.4.0 core:save (input.hidden-input)
     -9:29.1.0 core:backspace (input.hidden-input)
     -9:26.8.0 core:save (input.hidden-input)
  4x -5:24.8.0 find-and-replace:show (input.hidden-input)
```

### Non-Core Packages

```
atom-alignment 0.13.0 
atom-material-ui 2.1.3 
atom-monokai-soda 3.0.1 
atom-ternjs 0.18.3 
atom-typescript 12.7.0 
autocomplete-clang 0.11.5 
build 0.70.0 
busy 0.7.0 
busy-signal 1.4.3 
docblockr 0.13.7 
emmet 2.4.3 
file-icons 2.1.26 
git-control 0.9.0 
highlight-line 0.12.0 
intentions 1.1.5 
javascript-snippets 1.2.1 
jshint 1.8.6 
language-glsl 2.0.4 
linter 2.2.0 
linter-gcc 0.7.1 
linter-ui-default 1.7.1 
Stylus 3.2.0 
todo-show 2.3.2 
```

**Comment by pierreglibert** [comment]
Reinstall it solve this problem :)
