### ISSUE TITLE
Atom-Typescript error: Error processing request. Debug Failure. False expression: FailedLookup

### ISSUE THREAD

**Issue by ZuBB** [TypeStrong/atom-typescript#1485]
[Enter steps to reproduce:]

1. ... (sorry no good STR as for now)

**Atom**: 1.33.1 x64
**Electron**: 2.0.16
**OS**: Mac OS X 10.13.6
**Thrown From**: [atom-typescript](https://github.com/TypeStrong/atom-typescript) package 12.7.3

### Error tooltip title from Atom (see screen)

```
Atom-Typescript error: Error processing request. Debug Failure. False expression: FailedLookup: /Users/vzuzyak/work/cad/ui-advanced-tv/src/app/common/abstract-controllers/tactic/tactic-actions/node_modules/@../../package.json failedLookupLocationPath: /users/vzuzyak/work/cad/ui-advanced-tv/src/app/common/abstract-controllers/tactic/tactic-actions/node_modules/package.json Error: Debug Failure. False expression: FailedLookup: /Users/vzuzyak/work/cad/ui-advanced-tv/src/app/common/abstract-controllers/tactic/tactic-actions/node_modules/@../../package.json failedLookupLocationPath: /users/vzuzyak/work/cad/ui-advanced-tv/src/app/common/abstract-controllers/tactic/tactic-actions/node_modules/package.json at getDirectoryToWatchFailedLookupLocation (/Users/vzuzyak/.atom/packages/atom-typescript/node_modules/typescript/lib/tsserver.js:87517:26) at watchFailedLookupLocationOfResolution (/Users/vzuzyak/.atom/packages/atom-typescript/node_modules/typescript/lib/tsserver.js:87585:26) at Array.forEach () at watchFailedLookupLocationOfNonRelativeModuleResolutions (/Users/vzuzyak/.atom/packages/atom-typescript/node_modules/typescript/lib/tsserver.js:87614:25) at Map.forEach () at Object.clearPerDirectoryResolutions [as startCachingPerDirectoryResolution] (/Users/vzuzyak/.atom/packages/atom-typescript/node_modules/typescript/lib/tsserver.js:87356:50) at ConfiguredProject.Project.updateGraphWorker (/Users/vzuzyak/.atom/packages/atom-typescript/node_modules/typescript/lib/tsserver.js:118767:38) at ConfiguredProject.Project.updateGraph (/Users/vzuzyak/.atom/packages/atom-typescript/node_modules/typescript/lib/tsserver.js:118716:42) at ConfiguredProject.updateGraph (/Users/vzuzyak/.atom/packages/atom-typescript/node_modules/typescript/lib/tsserver.js:119102:63) at Object.updateProjectIfDirty (/Users/vzuzyak/.atom/packages/atom-typescript/node_modules/typescript/lib/tsserver.js:119413:45) at IOSession.Session.getProjectInfoWorker (/Users/vzuzyak/.atom/packages/atom-typescript/node_modules/typescript/lib/tsserver.js:122288:24) at IOSession.Session.getProjectInfo (/Users/vzuzyak/.atom/packages/atom-typescript/node_modules/typescript/lib/tsserver.js:122284:29) at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/Users/vzuzyak/.atom/packages/atom-typescript/node_modules/typescript/lib/tsserver.js:121748:61) at /Users/vzuzyak/.atom/packages/atom-typescript/node_modules/typescript/lib/tsserver.js:123062:88 at IOSession.Session.executeWithRequestId (/Users/vzuzyak/.atom/packages/atom-typescript/node_modules/typescript/lib/tsserver.js:123053:28) at IOSession.Session.executeCommand (/Users/vzuzyak/.atom/packages/atom-typescript/node_modules/typescript/lib/tsserver.js:123062:33) at IOSession.Session.onMessage (/Users/vzuzyak/.atom/packages/atom-typescript/node_modules/typescript/lib/tsserver.js:123082:35) at Interface. (/Users/vzuzyak/.atom/packages/atom-typescript/node_modules/typescript/lib/tsserver.js:124345:27) at emitOne (events.js:116:13) at Interface.emit (events.js:211:7) at Interface._onLine (readline.js:282:10) at Interface._normalWrite (readline.js:424:12) at Socket.ondata (readline.js:141:10) at emitOne (events.js:116:13) at Socket.emit (events.js:211:7) at addChunk (_stream_readable.js:263:12) at readableAddChunk (_stream_readable.js:250:11) at Socket.Readable.push (_stream_readable.js:208:10) at Pipe.onread (net.js:594:20)
```

### Stack Trace

Atom-Typescript error: Error processing request. Debug Failure. False expression: FailedLookup: /Users/vzuzyak/work/cad/ui-advanced-tv/src/app/common/abstract-controllers/tactic/tactic-actions/node_modules/@../../package.json failedLookupLocationPath: /users/vzuzyak/work/cad/ui-advanced-tv/src/app/common/abstract-controllers/tactic/tactic-actions/node_modules/package.json
Error: Debug Failure. False expression: FailedLookup: /Users/vzuzyak/work/cad/ui-advanced-tv/src/app/common/abstract-controllers/tactic/tactic-actions/node_modules/@../../package.json failedLookupLocationPath: /users/vzuzyak/work/cad/ui-advanced-tv/src/app/common/abstract-controllers/tactic/tactic-actions/node_modules/package.json
    at getDirectoryToWatchFailedLookupLocation (/Users/vzuzyak/.atom/packages/atom-typescript/node_modules/typescript/lib/tsserver.js:87517:26)
    at watchFailedLookupLocationOfResolution (/Users/vzuzyak/.atom/packages/atom-typescript/node_modules/typescript/lib/tsserver.js:87585:26)
    at Array.forEach (<anonymous>)
    at watchFailedLookupLocationOfNonRelativeModuleResolutions (/Users/vzuzyak/.atom/packages/atom-typescript/node_modules/typescript/lib/tsserver.js:87614:25)
    at Map.forEach (<anonymous>)
    at Object.clearPerDirectoryResolutions [as startCachingPerDirectoryResolution] (/Users/vzuzyak/.atom/packages/atom-typescript/node_modules/typescript/lib/tsserver.js:87356:50)
    at ConfiguredProject.Project.updateGraphWorker (/Users/vzuzyak/.atom/packages/atom-typescript/node_modules/typescript/lib/tsserver.js:118767:38)
    at ConfiguredProject.Project.updateGraph (/Users/vzuzyak/.atom/packages/atom-typescript/node_modules/typescript/lib/tsserver.js:118716:42)
    at ConfiguredProject.updateGraph (/Users/vzuzyak/.atom/packages/atom-typescript/node_modules/typescript/lib/tsserver.js:119102:63)
    at Object.updateProjectIfDirty (/Users/vzuzyak/.atom/packages/atom-typescript/node_modules/typescript/lib/tsserver.js:119413:45)
    at IOSession.Session.getProjectInfoWorker (/Users/vzuzyak/.atom/packages/atom-typescript/node_modules/typescript/lib/tsserver.js:122288:24)
    at IOSession.Session.getProjectInfo (/Users/vzuzyak/.atom/packages/atom-typescript/node_modules/typescript/lib/tsserver.js:122284:29)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/Users/vzuzyak/.atom/packages/atom-typescript/node_modules/typescript/lib/tsserver.js:121748:61)
    at /Users/vzuzyak/.atom/packages/atom-typescript/node_modules/typescript/lib/tsserver.js:123062:88
    at IOSession.Session.executeWithRequestId (/Users/vzuzyak/.atom/packages/atom-typescript/node_modules/typescript/lib/tsserver.js:123053:28)
    at IOSession.Session.executeCommand (/Users/vzuzyak/.atom/packages/atom-typescript/node_modules/typescript/lib/tsserver.js:123062:33)
    at IOSession.Session.onMessage (/Users/vzuzyak/.atom/packages/atom-typescript/node_modules/typescript/lib/tsserver.js:123082:35)
    at Interface.<anonymous> (/Users/vzuzyak/.atom/packages/atom-typescript/node_modules/typescript/lib/tsserver.js:124345:27)
    at emitOne (events.js:116:13)
    at Interface.emit (events.js:211:7)
    at Interface._onLine (readline.js:282:10)
    at Interface._normalWrite (readline.js:424:12)
    at Socket.ondata (readline.js:141:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)

```
At Error: Error processing request. Debug Failure. False expression: FailedLookup: /Users/vzuzyak/work/cad/ui-advanced-tv/src/app/common/abstract-controllers/tactic/tactic-actions/node_modules/@../../package.json failedLookupLocationPath: /users/vzuzyak/work/cad/ui-advanced-tv/src/app/common/abstract-controllers/tactic/tactic-actions/node_modules/package.json
Error: Debug Failure. False expression: FailedLookup: /Users/vzuzyak/work/cad/ui-advanced-tv/src/app/common/abstract-controllers/tactic/tactic-actions/node_modules/@../../package.json failedLookupLocationPath: /users/vzuzyak/work/cad/ui-advanced-tv/src/app/common/abstract-controllers/tactic/tactic-actions/node_modules/package.json
    at getDirectoryToWatchFailedLookupLocation (/Users/vzuzyak/.atom/packages/atom-typescript/node_modules/typescript/lib/tsserver.js:87517:26)
    at watchFailedLookupLocationOfResolution (/Users/vzuzyak/.atom/packages/atom-typescript/node_modules/typescript/lib/tsserver.js:87585:26)
    at Array.forEach (<anonymous>)
    at watchFailedLookupLocationOfNonRelativeModuleResolutions (/Users/vzuzyak/.atom/packages/atom-typescript/node_modules/typescript/lib/tsserver.js:87614:25)
    at Map.forEach (<anonymous>)
    at Object.clearPerDirectoryResolutions [as startCachingPerDirectoryResolution] (/Users/vzuzyak/.atom/packages/atom-typescript/node_modules/typescript/lib/tsserver.js:87356:50)
    at ConfiguredProject.Project.updateGraphWorker (/Users/vzuzyak/.atom/packages/atom-typescript/node_modules/typescript/lib/tsserver.js:118767:38)
    at ConfiguredProject.Project.updateGraph (/Users/vzuzyak/.atom/packages/atom-typescript/node_modules/typescript/lib/tsserver.js:118716:42)
    at ConfiguredProject.updateGraph (/Users/vzuzyak/.atom/packages/atom-typescript/node_modules/typescript/lib/tsserver.js:119102:63)
    at Object.updateProjectIfDirty (/Users/vzuzyak/.atom/packages/atom-typescript/node_modules/typescript/lib/tsserver.js:119413:45)
    at IOSession.Session.getProjectInfoWorker (/Users/vzuzyak/.atom/packages/atom-typescript/node_modules/typescript/lib/tsserver.js:122288:24)
    at IOSession.Session.getProjectInfo (/Users/vzuzyak/.atom/packages/atom-typescript/node_modules/typescript/lib/tsserver.js:122284:29)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (/Users/vzuzyak/.atom/packages/atom-typescript/node_modules/typescript/lib/tsserver.js:121748:61)
    at /Users/vzuzyak/.atom/packages/atom-typescript/node_modules/typescript/lib/tsserver.js:123062:88
    at IOSession.Session.executeWithRequestId (/Users/vzuzyak/.atom/packages/atom-typescript/node_modules/typescript/lib/tsserver.js:123053:28)
    at IOSession.Session.executeCommand (/Users/vzuzyak/.atom/packages/atom-typescript/node_modules/typescript/lib/tsserver.js:123062:33)
    at IOSession.Session.onMessage (/Users/vzuzyak/.atom/packages/atom-typescript/node_modules/typescript/lib/tsserver.js:123082:35)
    at Interface.<anonymous> (/Users/vzuzyak/.atom/packages/atom-typescript/node_modules/typescript/lib/tsserver.js:124345:27)
    at emitOne (events.js:116:13)
    at Interface.emit (events.js:211:7)
    at Interface._onLine (readline.js:282:10)
    at Interface._normalWrite (readline.js:424:12)
    at Socket.ondata (readline.js:141:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)

Error: Error processing request. Debug Failure. False expression: FailedLookup: /Users/vzuzyak/work/cad/ui-advanced-tv/src/app/common/abstract-controllers/tactic/tactic-actions/node_modules/@../../package.json failedLookupLocationPath: /users/vzuzyak/work/cad/ui-advanced-tv/src/app/common/abstract-controllers/tactic/tactic-actions/node_modules/package.json
Error: Debug Failure. False expression: FailedLookup: /Users/vzuzyak/work/cad/ui-advanced-tv/src/app/common/abstract-controllers/tactic/tactic-actions/node_modules/@../../package.json failedLookupLocationPath: /users/vzuzyak/work/cad/ui-advanced-tv/src/app/common/abstract-controllers/tactic/tactic-actions/node_modules/package.json
    at getDirectoryToWatchFailedLookupLocation (/packages/atom-typescript/node_modules/typescript/lib/tsserver.js:87517:26)
    at watchFailedLookupLocationOfResolution (/packages/atom-typescript/node_modules/typescript/lib/tsserver.js:87585:26)
    at Array.forEach (<anonymous>)
    at watchFailedLookupLocationOfNonRelativeModuleResolutions (/packages/atom-typescript/node_modules/typescript/lib/tsserver.js:87614:25)
    at Map.forEach (<anonymous>)
    at /packages/atom-typescript/node_modules/typescript/lib/tsserver.js:87356:50)
    at ConfiguredProject.Project.updateGraphWorker (/packages/atom-typescript/node_modules/typescript/lib/tsserver.js:118767:38)
    at ConfiguredProject.Project.updateGraph (/packages/atom-typescript/node_modules/typescript/lib/tsserver.js:118716:42)
    at ConfiguredProject.updateGraph (/packages/atom-typescript/node_modules/typescript/lib/tsserver.js:119102:63)
    at Object.updateProjectIfDirty (/packages/atom-typescript/node_modules/typescript/lib/tsserver.js:119413:45)
    at IOSession.Session.getProjectInfoWorker (/packages/atom-typescript/node_modules/typescript/lib/tsserver.js:122288:24)
    at IOSession.Session.getProjectInfo (/packages/atom-typescript/node_modules/typescript/lib/tsserver.js:122284:29)
    at /packages/atom-typescript/node_modules/typescript/lib/tsserver.js:121748:61)
    at /packages/atom-typescript/node_modules/typescript/lib/tsserver.js:123062:88
    at IOSession.Session.executeWithRequestId (/packages/atom-typescript/node_modules/typescript/lib/tsserver.js:123053:28)
    at IOSession.Session.executeCommand (/packages/atom-typescript/node_modules/typescript/lib/tsserver.js:123062:33)
    at IOSession.Session.onMessage (/packages/atom-typescript/node_modules/typescript/lib/tsserver.js:123082:35)
    at /packages/atom-typescript/node_modules/typescript/lib/tsserver.js:124345:27)
    at emitOne (events.js:116:13)
    at Interface.emit (events.js:211:7)
    at Interface._onLine (readline.js:282:10)
    at Interface._normalWrite (readline.js:424:12)
    at Socket.ondata (readline.js:141:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
    at Callbacks.resolve (/packages/atom-typescript/dist/client/callbacks.js:39:28)
    at TypescriptServiceClient.onResponse (/packages/atom-typescript/dist/client/client.js:144:24)
    at MessageStream.TypescriptServiceClient.onMessage (/packages/atom-typescript/dist/client/client.js:75:22)
    at emitOne (events.js:116:13)
    at MessageStream.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at MessageStream.Readable.push (_stream_readable.js:208:10)
    at MessageStream.Transform.push (_stream_transform.js:147:32)
    at MessageStream._transform (/packages/atom-typescript/dist/client/client.js:184:22)
    at MessageStream.Transform._read (_stream_transform.js:186:10)
    at MessageStream.Transform._write (_stream_transform.js:174:12)
    at doWrite (_stream_writable.js:387:12)
    at writeOrBuffer (_stream_writable.js:373:5)
    at MessageStream.Writable.write (_stream_writable.js:290:11)
    at LineStream.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at LineStream.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at LineStream.Readable.push (_stream_readable.js:208:10)
    at LineStream.Transform.push (_stream_transform.js:147:32)
    at LineStream._pushBuffer (/packages/atom-typescript/node_modules/byline/lib/byline.js:126:17)
    at LineStream._transform (/packages/atom-typescript/node_modules/byline/lib/byline.js:117:8)
    at LineStream.Transform._read (_stream_transform.js:186:10)
    at LineStream.Transform._write (_stream_transform.js:174:12)
    at doWrite (_stream_writable.js:387:12)
    at writeOrBuffer (_stream_writable.js:373:5)
    at LineStream.Writable.write (_stream_writable.js:290:11)
    at Socket.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
```

### Commands

```
     -1:01.3.0 vim-mode-plus:move-up (input.hidden-input)
     -1:00.8.0 vim-mode-plus:move-left (input.hidden-input)
     -1:00.5.0 vim-mode-plus:put-after (input.hidden-input)
     -1:00.0 vim-mode-plus:move-right (input.hidden-input)
     -0:59.5.0 vim-mode-plus:activate-characterwise-visual-mode (input.hidden-input)
     -0:58.5.0 vim-mode-plus:activate-normal-mode (input.hidden-input)
     -0:57 vim-mode-plus:replace-character (input.hidden-input)
  6x -0:57 blur (input.hidden-input)
  2x -0:56.6.0 vim-mode-plus:move-to-next-word (input.hidden-input)
     -0:55.7.0 vim-mode-plus:delete-right (input.hidden-input)
     -0:45.1.0 vim-mode-plus:move-to-beginning-of-line (input.hidden-input)
  8x -0:45 vim-mode-plus:move-to-next-word (input.hidden-input)
     -0:43.1.0 vim-mode-plus:search-current-word-backwards (input.hidden-input)
  8x -0:42.7.0 vim-mode-plus:repeat-search (input.hidden-input)
     -0:40.4.0 core:save (input.hidden-input)
 15x -0:31.3.0 blur (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-clock 0.1.16 
atom-live-server 2.3.0 
atom-typescript 12.7.3 
busy-signal 2.0.0 
compare-files 0.8.1 
editor-stats 0.17.0 
editorconfig 2.2.2 
emmet 2.4.3 
ex-mode 0.18.0 
git-control 0.9.0 
git-plus 8.3.0 
go-plus 6.0.2 
goto-definition 1.3.4 
intentions 1.1.5 
language-scala 1.1.9 
linter 2.2.0 
linter-ui-default 1.7.1 
minimap 4.29.9 
open-recent 5.0.0 
pretty-json 2.0.3 
pull-request 0.2.1 
show-invisibles-plus 0.3.1 
svg-preview 0.14.0 
sync-settings 0.8.6 
todo-show 2.3.2 
vim-mode-plus 1.36.0 
```

<img width="1680" alt="screen shot 2019-01-07 at 16 48 10" src="https://user-images.githubusercontent.com/597016/50774502-47c80600-129c-11e9-903d-7ae769aae40f.png">

**Comment by lierdakil** [comment]
The stacktrace looks like this upstream issue: https://github.com/Microsoft/TypeScript/issues/27405

Check if you can reproduce this on TypeScript 3.2.2.
