### ISSUE TITLE
Uncaught TypeError: grammar.tokenizeLines is not a function

### ISSUE THREAD

**Issue by akonwi** [TypeStrong/atom-typescript#1503]
[Enter steps to reproduce:]

1. Invoke `Typescript: Find References` command

**Atom**: 1.40.0-nightly4 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.14.5
**Thrown From**: [atom-typescript](https://github.com/TypeStrong/atom-typescript) package 13.2.1

### Stack Trace

Uncaught TypeError: grammar.tokenizeLines is not a function

```
At /Users/akonwi/.atom/packages/atom-typescript/node_modules/atom-highlight/lib/highlight.js:64

TypeError: grammar.tokenizeLines is not a function
    at highlightSync (/packages/atom-typescript/node_modules/atom-highlight/lib/highlight.js:64:32)
    at TsView.render (/packages/atom-typescript/dist/main/atom/components/tsView.js:15:22)
    at Object.initialize (/packages/atom-ide-datatip/node_modules/etch/lib/component-helpers.js:42:31)
    at /packages/atom-typescript/dist/main/atom/components/tsView.js:8:14)
    at render (/packages/atom-ide-datatip/node_modules/etch/lib/render.js:21:25)
    at addChildren (/packages/atom-ide-datatip/node_modules/etch/lib/render.js:45:24)
    at Object.render (/packages/atom-ide-datatip/node_modules/etch/lib/render.js:35:21)
    at Object.elementForItem (/packages/atom-typescript/dist/main/atom/views/simpleSelectionView.js:36:48)
    at listItems.items.map (/packages/git-plus/node_modules/atom-select-list/src/select-list-view.js:219:31)
    at Array.map (<anonymous>)
    at SelectListView.renderItems (/packages/git-plus/node_modules/atom-select-list/src/select-list-view.js:215:35)
    at SelectListView.render (/packages/git-plus/node_modules/atom-select-list/src/select-list-view.js:199:12)
    at updateSync (/packages/git-plus/node_modules/etch/lib/component-helpers.js:107:34)
    at /packages/git-plus/node_modules/etch/lib/component-helpers.js:72:7
    at DefaultScheduler.performUpdates (/packages/atom-ide-datatip/node_modules/etch/lib/default-scheduler.js:48:34)
```

### Commands

```
     -0:37.3.0 vim-mode-plus:move-to-first-line (input.hidden-input)
  4x -0:35.8.0 vim-mode-plus:move-down (input.hidden-input)
  2x -0:32 vim-mode-plus:delete (input.hidden-input)
     -0:31.3.0 core:save (input.hidden-input)
     -0:31.3.0 linter:lint (atom-text-editor.editor.linter-tslint-compatible-editor.vim-mode-plus.typescript-editor.is-focused.normal-mode)
     -0:24.1.0 vim-mode-plus:search (input.hidden-input)
     -0:23.3.0 editor:consolidate-selections (input.hidden-input)
     -0:23.3.0 core:cancel (input.hidden-input)
     -0:22.9.0 command-palette:toggle (input.hidden-input)
     -0:22.2.0 core:confirm (input.hidden-input)
     -0:22.2.0 typescript:find-references (input.hidden-input)
     -0:20.8.0 editor:consolidate-selections (input.hidden-input)
     -0:20.8.0 core:cancel (input.hidden-input)
     -0:13.8.0 typescript:find-references (input.hidden-input)
     -0:12.1.0 editor:consolidate-selections (input.hidden-input)
     -0:12.1.0 core:cancel (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.8 
apm-publish 0.3.2 
atom-beautify 0.33.4 
atom-ide-datatip 0.10.4 
atom-ide-definitions 0.3.0 
atom-ide-diagnostics 0.0.0 
atom-ide-markdown-service 1.2.0 
atom-ide-signature-help 0.6.3 
atom-material-syntax-light 0.4.6 
atom-material-ui 2.1.3 
atom-typescript 13.2.1 
better-git-blame 0.4.7 
busy-signal 2.0.1 
city-lights-syntax 1.1.8 
city-lights-ui 1.5.3 
codestream 1.2.0 
codestream-atom-toolbar 0.0.1 
git-menu 3.0.1 
git-plus 8.7.0 
hyperclick 0.1.5 
ide-json 0.2.1 
ide-rust 0.20.3 
intentions 1.1.5 
lame-sauce-syntax-light 1.0.0 
lame-sauce-ui 0.2.0 
language-babel 2.85.0 
language-docker 1.1.8 
language-kotlin 0.5.0 
language-rust 0.4.12 
linter 2.3.0 
linter-eslint 8.5.5 
linter-tslint 1.10.27 
linter-ui-plus 0.3.2 
notifications-plus 0.69.15 
one-black-syntax 1.14.0 
platformio-ide-terminal 2.9.1 
prettier-atom 0.56.6 
project-manager 3.3.7 
recent-files-fuzzy-finder 1.0.0 
relative-numbers 0.9.0 
split-diff 1.6.0 
sync-settings 0.8.6 
tool-bar 1.1.11 
vim-mode-plus 1.36.0 
```

**Comment by mininek** [comment]
I get this error, too. Would downgrading atom help or is this a node issue? I am not sure how atom and the nodes work together, I am a newbie. Would some input from me help to solve this issue? I would like to help if I can.

**Comment by akonwi** [comment]
I don't recall when I first noticed this issue but it occurs with the nightly releases. There's no problem while using the stable build though.

**Comment by mininek** [comment]
Thank you for replying, akonwi. I don't think mine is a nightly release, here are my system features:
Atom: 1.39.1 x64
Electron: 3.1.10
Chrome: 66.0.3359.181
Node: v10.2.0
OS: Ubuntu 18.04.2 LTS
My atom typescript is v13.2.1 and I still have this issue :-(

Here is the stack trace:
```
TypeError: grammar.tokenizeLines is not a function
    at highlightSync (/packages/atom-typescript/node_modules/atom-highlight/lib/highlight.js:64:32)
    at TsView.render (/packages/atom-typescript/dist/main/atom/components/tsView.js:15:22)
    at Object.initialize (/packages/atom-typescript/node_modules/etch/lib/component-helpers.js:42:31)
    at new TsView (/packages/atom-typescript/dist/main/atom/components/tsView.js:8:14)
    at render (/packages/atom-typescript/node_modules/etch/lib/render.js:21:25)
    at addChildren (/packages/atom-typescript/node_modules/etch/lib/render.js:45:24)
    at Object.render (/packages/atom-typescript/node_modules/etch/lib/render.js:35:21)
    at Object.elementForItem (/packages/atom-typescript/dist/main/atom/views/simpleSelectionView.js:36:48)
    at listItems.items.map (/packages/atom-typescript/node_modules/atom-select-list/src/select-list-view.js:219:31)
    at Array.map (<anonymous>)
    at SelectListView.renderItems (/packages/atom-typescript/node_modules/atom-select-list/src/select-list-view.js:215:35)
    at SelectListView.render (/packages/atom-typescript/node_modules/atom-select-list/src/select-list-view.js:199:12)
    at updateSync (/packages/atom-typescript/node_modules/atom-select-list/node_modules/etch/lib/component-helpers.js:107:34)
    at /packages/atom-typescript/node_modules/atom-select-list/node_modules/etch/lib/component-helpers.js:72:7
    at DefaultScheduler.performUpdates (/packages/atom-typescript/node_modules/etch/lib/default-scheduler.js:48:34)
```

**Comment by akonwi** [comment]
Ok, I lied. Somehow the `Find References` command worked for me earlier in Atom v1.39.1 but I just tried it again and saw the error. I wonder if it's related to the file it's invoked in because when it worked earlier it was with a different repo than what I just tried it with.

**Comment by mininek** [comment]
I have multiple repos and what it does is ```Find References``` throws the error when it is first invoked (any repo) then when you try again it loads infinitely and doesn't  show the error anymore. But it doesn't work in any of my repos.

**Comment by ocoka** [comment]
Same for me of course, since I think it's related to API changes in Atom, I linked it to issue in atom-highlight package

**Comment by lierdakil** [comment]
Sorry about the long silence.

This is related to tree-sitter grammar being added for tsx. The workaround for now is disabling tree-sitter grammars (Settings → Core → Use Tree Sitter Parsers). I'll try to fix this for sooner rather than later, but it's not exactly trivial.

**Comment by lierdakil** [comment]
Nevermind that, a quick fix is released as v13.3.0. It's not a "real" fix though, but it should work for the time being.

**Comment by ocoka** [comment]
Cool, thank's a lot

**Comment by ocoka** [comment]
Yes, it work's. Thank's again

**Comment by mininek** [comment]
Thanks a lot! It works for me, too.
