### ISSUE TITLE
Atom-Typescript error: terminated on signal: SIGABRT

### ISSUE THREAD

**Issue by chaffeqa** [TypeStrong/atom-typescript#1508]
```
Last output from tsserver:
11: 0x109266708 v8::internal::interpreter::Interpreter::GetDispatchCountersObject() [/Applications/Atom Beta.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
12: 0x10939c608 v8::internal::RegisterConfiguration::AreAliases(v8::internal::MachineRepresentation, int, v8::internal::MachineRepresentation, int) const [/Applications/Atom Beta.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
13: 0x1097ecc0e v8::internal::Parser::BuildIteratorCloseForCompletion(v8::internal::ZoneList<v8::internal::Statement*>*, v8::internal::Variable*, v8::internal::Expression*, v8::internal::IteratorType) [/Applications/Atom Beta.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
14: 0x1098022ee v8::internal::Parser::BuildIteratorCloseForCompletion(v8::internal::ZoneList<v8::internal::Statement*>*, v8::internal::Variable*, v8::internal::Expression*, v8::internal::IteratorType) [/Applications/Atom Beta.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework]
15: 0x35b96e9e4a8f 
terminated on signal: SIGABRT
```

**Atom**: 1.41.0-beta0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.14.6
**Thrown From**: [atom-typescript](https://github.com/TypeStrong/atom-typescript) package 13.3.0

### Stack Trace

Atom-Typescript error: terminated on signal: SIGABRT

```
At Error: terminated on signal: SIGABRT

Error: terminated on signal: SIGABRT
    at ChildProcess.cp.once (/packages/atom-typescript/dist/client/client.js:137:19)
    at Object.onceWrapper (events.js:273:13)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
```

### Commands

```
     -0:43 core:copy (input.hidden-input)
     -0:42.7.0 core:undo (input.hidden-input)
     -0:40.5.0 find-and-replace:show (input.hidden-input)
     -0:40.3.0 core:paste (input.hidden-input)
     -0:40.1.0 core:confirm (input.hidden-input)
     -0:32.2.0 editor:newline (input.hidden-input)
     -0:28.9.0 core:paste (input.hidden-input)
     -0:28.1.0 intentions:highlight (input.hidden-input)
     -0:27.9.0 editor:move-to-beginning-of-word (input.hidden-input)
     -0:26.6.0 editor:move-to-end-of-screen-line (input.hidden-input)
     -0:24 core:copy (input.hidden-input)
     -0:23.1.0 core:paste (input.hidden-input)
     -0:21.9.0 core:save (input.hidden-input)
     -0:16 core:copy (input.hidden-input)
     -0:15.7.0 pane:show-item-2 (input.hidden-input)
     -0:11.8.0 core:paste (input.hidden-input)
```

### Non-Core Packages

```
atom-typescript 13.3.0 
busy-signal 2.0.1 
hyperclick 0.1.5 
intentions 1.1.5 
language-docker 1.1.8 
language-graphql 1.0.0 
language-haml 0.32.1 
language-jenkinsfile 0.1.1 
linter 2.3.1 
linter-csslint 2.0.6 
linter-docker 0.3.2 
linter-eslint 8.5.5 
linter-tslint 1.10.28 
linter-ui-default 1.7.1 
prettier-atom 0.57.2 
react 0.18.0 
regex-railroad-diagram 0.19.4 
teletype 0.13.4 
```

**Comment by lierdakil** [comment]
Hi. Sorry for the late reply, this managed to slip through.

The issue is that, apparently, tsserver process aborted due to a bug in node. Does this still reproduce, or was this a one-off thing?
