### ISSUE TITLE
Atom-Typescript error: Cannot read property 'NaN' of undefined

### ISSUE THREAD

**Issue by mininek** [TypeStrong/atom-typescript#1509]
Error is displayed when I pop the latest stash (```git stash pop```). Then when I save the stash I think I get a different stack trace, I will add that as a comment.  I am on Ubuntu 18.04, atom 1.40.1, atom-typescript 13.3.0.This is the error stack trace following ```git stash pop```:
``` bash
TypeError: Cannot read property 'NaN' of undefined
    at TextEditorComponent.renderedScreenLineForRow (/snap/atom/238/usr/share/atom/resources/app/static/<embedded>:11:81417)
    at TextEditorComponent.pixelLeftForRowAndColumn (/snap/atom/238/usr/share/atom/resources/app/static/<embedded>:11:107405)
    at TextEditorComponent.pixelPositionForScreenPosition (/snap/atom/238/usr/share/atom/resources/app/static/<embedded>:11:66571)
    at HTMLElement.pixelPositionForBufferPosition (/snap/atom/238/usr/share/atom/resources/app.asar/src/text-editor-element.js:238:32)
    at TooltipController.computeTooltipPosition (~/.atom/packages/atom-typescript/dist/main/atom/sigHelp/controller.js:59:34)
    at TooltipController.updateTooltip (~/.atom/packages/atom-typescript/dist/main/atom/sigHelp/controller.js:41:34)
    at new TooltipController (~/.atom/packages/atom-typescript/dist/main/atom/sigHelp/controller.js:26:36)
    at SigHelpManager.showTooltip (~/.atom/packages/atom-typescript/dist/main/atom/sigHelp/manager.js:60:40)
    at ~/.atom/packages/atom-typescript/dist/main/atom/sigHelp/manager.js:20:44
    at Function.simpleDispatch (/snap/atom/238/usr/share/atom/resources/app/static/<embedded>:11:1209208)
    at Emitter.emit (/snap/atom/238/usr/share/atom/resources/app/static/<embedded>:11:1210649)
    at TextBuffer.emitDidStopChangingEvent (/snap/atom/238/usr/share/atom/resources/app/static/<embedded>:11:504867)
    at later (/snap/atom/238/usr/share/atom/resources/app/static/<embedded>:14:104393)
```

**Comment by mininek** [comment]
This is the stack trace after ```git stash save```:
``` bash
TypeError: Cannot read property 'NaN' of undefined
    at TextEditorComponent.renderedScreenLineForRow (/snap/atom/238/usr/share/atom/resources/app/static/<embedded>:11:81417)
    at TextEditorComponent.pixelLeftForRowAndColumn (/snap/atom/238/usr/share/atom/resources/app/static/<embedded>:11:107405)
    at TextEditorComponent.pixelPositionForScreenPosition (/snap/atom/238/usr/share/atom/resources/app/static/<embedded>:11:66571)
    at HTMLElement.pixelPositionForBufferPosition (/snap/atom/238/usr/share/atom/resources/app.asar/src/text-editor-element.js:238:32)
    at TooltipController.computeTooltipPosition (~/.atom/packages/atom-typescript/dist/main/atom/sigHelp/controller.js:59:34)
    at TooltipController.updateTooltip (~/.atom/packages/atom-typescript/dist/main/atom/sigHelp/controller.js:41:34)
    at invokeFunc (~/.atom/packages/atom-typescript/node_modules/lodash/lodash.js:10333:23)
    at leadingEdge (~/.atom/packages/atom-typescript/node_modules/lodash/lodash.js:10343:26)
    at debounced (~/.atom/packages/atom-typescript/node_modules/lodash/lodash.js:10410:20)
    at TooltipController.disposables.add.editor.onDidChangeCursorPosition.evt (~/.atom/packages/atom-typescript/dist/main/atom/sigHelp/controller.js:20:35)
    at Function.simpleDispatch (/snap/atom/238/usr/share/atom/resources/app/static/<embedded>:11:1209208)
    at Emitter.emit (/snap/atom/238/usr/share/atom/resources/app/static/<embedded>:11:1210649)
    at TextEditor.cursorMoved (/snap/atom/238/usr/share/atom/resources/app/static/<embedded>:11:33212)
    at Selection.markerDidChange (/snap/atom/238/usr/share/atom/resources/app/static/<embedded>:11:547080)
    at Selection.marker.onDidChange.e (/snap/atom/238/usr/share/atom/resources/app/static/<embedded>:11:532223)
    at Function.simpleDispatch (/snap/atom/238/usr/share/atom/resources/app/static/<embedded>:11:1209208)
    at Emitter.emit (/snap/atom/238/usr/share/atom/resources/app/static/<embedded>:11:1210649)
    at DisplayMarker.notifyObservers (/snap/atom/238/usr/share/atom/resources/app/static/<embedded>:14:2855767)
    at /snap/atom/238/usr/share/atom/resources/app/static/<embedded>:14:2851269
    at Function.simpleDispatch (/snap/atom/238/usr/share/atom/resources/app/static/<embedded>:11:1209208)
    at Emitter.emit (/snap/atom/238/usr/share/atom/resources/app/static/<embedded>:11:1210649)
    at Marker.emitChangeEvent (/snap/atom/238/usr/share/atom/resources/app/static/<embedded>:14:73563)
    at /snap/atom/238/usr/share/atom/resources/app/static/<embedded>:14:80000
    at Set.forEach (<anonymous>)
    at MarkerLayer.emitChangeEvents (/snap/atom/238/usr/share/atom/resources/app/static/<embedded>:14:79945)
    at TextBuffer.emitMarkerChangeEvents (/snap/atom/238/usr/share/atom/resources/app/static/<embedded>:11:503916)
    at TextBuffer.finishLoading (/snap/atom/238/usr/share/atom/resources/app/static/<embedded>:11:501023)
    at TextBuffer.load (/snap/atom/238/usr/share/atom/resources/app/static/<embedded>:11:499942)
```
