### ISSUE TITLE
Atom-Typescript error: terminated on signal: SIGKILL

### ISSUE THREAD

**Issue by micazoyolli** [TypeStrong/atom-typescript#1520]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Unknown macOS version
**Thrown From**: [atom-typescript](https://github.com/TypeStrong/atom-typescript) package 13.3.0

### Stack Trace

Atom-Typescript error: terminated on signal: SIGKILL

```
At Error: terminated on signal: SIGKILL

Error: terminated on signal: SIGKILL
    at ChildProcess.cp.once (/packages/atom-typescript/dist/client/client.js:137:19)
    at Object.onceWrapper (events.js:273:13)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
```

### Commands

```
     -2:33.1.0 project-find:show-in-current-directory (span.name.icon.icon-file-directory)
     -2:29.5.0 core:confirm (input.hidden-input)
     -2:07.3.0 project-find:show-in-current-directory (span.name.icon.icon-repo)
     -2:06.4.0 core:paste (input.hidden-input)
     -2:05.8.0 core:confirm (input.hidden-input)
     -0:37.8.0 core:cancel (div.results-view.focusable-panel)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-ternjs 0.20.0 
atom-typescript 13.3.0 
atom-wrap-in-tag 0.6.0 
busy-signal 2.0.1 
color-picker 2.3.0 
editorconfig 2.5.0 
emmet 2.4.3 
file-icons 2.1.36 
git-blame 1.8.0 
git-plus 8.7.1 
git-time-machine 2.1.0 
highlight-selected 0.16.0 
intentions 1.1.5 
javascript-snippets 1.2.1 
jsformat 0.9.3 
language-nunjucks 4.2.1 
language-pug 0.0.22 
linter 2.3.1 
linter-jshint 3.1.17 
linter-markdown 5.2.10 
linter-pug 2.0.9 
linter-sass-lint 1.9.0 
linter-stylelint 4.4.9 
linter-stylint 2.3.0 
linter-ui-default 1.8.0 
merge-conflicts 1.4.5 
minimap 4.29.9 
minimap-bookmarks 0.4.2 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-linter 2.2.1 
minimap-pigments 0.2.2 
minimap-selection 4.5.0 
pigments 0.40.2 
teletype 0.13.4 
todo-show 2.3.2 
```

**Comment by lierdakil** [comment]
As far as I can gather, tsserver process was killed by something (likely task manager or something like that). That's not an issue with the package as far as I can tell.
