### ISSUE TITLE
Atom-Typescript error: Cannot read property 'subscriptions' of undefined

### ISSUE THREAD

**Issue by penslz** [TypeStrong/atom-typescript#1522]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.41.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.15.1
**Thrown From**: [atom-typescript](https://github.com/TypeStrong/atom-typescript) package 13.3.0

### Stack Trace

Atom-Typescript error: Cannot read property 'subscriptions' of undefined

```
At TypeError: Cannot read property 'subscriptions' of undefined

TypeError: Cannot read property 'subscriptions' of undefined
    at TypescriptBuffer.close (/packages/atom-typescript/dist/main/typescriptBuffer.js:36:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

### Commands

```
     -1:12.4.0 core:save (input.hidden-input)
     -1:09.0 core:copy (input.hidden-input)
     -1:07.7.0 fuzzy-finder:toggle-file-finder (input.hidden-input)
     -1:07.5.0 core:paste (input.hidden-input)
     -1:05.2.0 core:select-all (input.hidden-input)
  2x -1:04.9.0 core:copy (input.hidden-input)
     -0:54.6.0 tree-view:add-file (span.name.icon.icon-file-directory)
     -0:49.6.0 core:confirm (input.hidden-input)
     -0:49.1.0 core:paste (input.hidden-input)
     -0:47.5.0 core:save (input.hidden-input)
     -0:39.3.0 core:copy (input.hidden-input)
     -0:38.4.0 fuzzy-finder:toggle-file-finder (input.hidden-input)
     -0:38.3.0 core:paste (input.hidden-input)
     -0:24.9.0 fuzzy-finder:toggle-file-finder (input.hidden-input)
     -0:24.7.0 core:paste (input.hidden-input)
     -0:13.8.0 editor:move-to-first-character-of-line (input.hidden-input)
```

### Non-Core Packages

```
atom-typescript 13.3.0 
busy-signal 2.0.1 
intentions 1.1.5 
linter 2.3.1 
linter-eslint 8.5.5 
linter-ui-default 1.8.0 
prettier-atom 0.57.3 
```

**Comment by lierdakil** [comment]
Thanks for reporting!
