### ISSUE TITLE
Outline error when opening a single file

### ISSUE THREAD

**Issue by aminya** [TypeStrong/atom-typescript#1550]
Outline error when opening a single file without a project:

```js

Error: Error processing request. No Project.
Error: No Project.
    at Object.ThrowNoProject (C:\Users\yahyaaba\node_modules\typescript\lib\tsserver.js:137981:23)
    at IOSession.Session.getFileAndLanguageServiceForSyntacticOperation (C:\Users\yahyaaba\node_modules\typescript\lib\tsserver.js:145263:42)
    at IOSession.Session.getNavigationTree (C:\Users\yahyaaba\node_modules\typescript\lib\tsserver.js:145614:31)
    at Session.handlers.ts.createMapFromTemplate._a.(anonymous function) (C:\Users\yahyaaba\node_modules\typescript\lib\tsserver.js:144481:61)
    at C:\Users\yahyaaba\node_modules\typescript\lib\tsserver.js:146003:88
    at IOSession.Session.executeWithRequestId (C:\Users\yahyaaba\node_modules\typescript\lib\tsserver.js:145994:28)
    at IOSession.Session.executeCommand (C:\Users\yahyaaba\node_modules\typescript\lib\tsserver.js:146003:33)
    at IOSession.Session.onMessage (C:\Users\yahyaaba\node_modules\typescript\lib\tsserver.js:146027:35)
    at Interface.<anonymous> (C:\Users\yahyaaba\node_modules\typescript\lib\tsserver.js:147342:27)
    at Interface.emit (events.js:194:13)
    at Interface._onLine (readline.js:312:10)
    at Interface._normalWrite (readline.js:457:12)
    at Socket.ondata (readline.js:168:10)
    at Socket.emit (events.js:194:13)
    at addChunk (_stream_readable.js:296:12)
    at readableAddChunk (_stream_readable.js:277:11)
    at Socket.Readable.push (_stream_readable.js:232:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:165:17)
    at Callbacks.resolve (C:\Users\yahyaaba\.atom\packages\atom-typescript\dist\client\callbacks.js:40:28)
    at MessageStream.TypescriptServiceClient.onMessage (C:\Users\yahyaaba\.atom\packages\atom-typescript\dist\client\client.js:87:32)
    at MessageStream.emit (events.js:194:13)
    at addChunk (_stream_readable.js:296:12)
    at readableAddChunk (_stream_readable.js:277:11)
    at MessageStream.Readable.push (_stream_readable.js:232:10)
    at MessageStream.Transform.push (_stream_transform.js:148:32)
    at MessageStream._transform (C:\Users\yahyaaba\.atom\packages\atom-typescript\dist\client\client.js:212:22)
    at MessageStream.Transform._read (_stream_transform.js:187:10)
    at MessageStream.Transform._write (_stream_transform.js:175:12)
    at doWrite (_stream_writable.js:415:12)
    at writeOrBuffer (_stream_writable.js:399:5)
    at MessageStream.Writable.write (_stream_writable.js:299:11)
    at LineStream.ondata (_stream_readable.js:706:22)
    at LineStream.emit (events.js:194:13)
    at addChunk (_stream_readable.js:296:12)
    at readableAddChunk (_stream_readable.js:277:11)
    at LineStream.Readable.push (_stream_readable.js:232:10)
    at LineStream.Transform.push (_stream_transform.js:148:32)
    at LineStream._pushBuffer (C:\Users\yahyaaba\.atom\packages\atom-typescript\node_modules\byline\lib\byline.js:126:17)
    at LineStream._transform (C:\Users\yahyaaba\.atom\packages\atom-typescript\node_modules\byline\lib\byline.js:117:8)
    at LineStream.Transform._read (_stream_transform.js:187:10)
    at LineStream.Transform._write (_stream_transform.js:175:12)
    at doWrite (_stream_writable.js:415:12)
    at writeOrBuffer (_stream_writable.js:399:5)
    at LineStream.Writable.write (_stream_writable.js:299:11)
    at Socket.ondata (_stream_readable.js:706:22)
    at Socket.emit (events.js:194:13)
    at addChunk (_stream_readable.js:296:12)
    at readableAddChunk (_stream_readable.js:277:11)
    at Socket.Readable.push (_stream_readable.js:232:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:165:17) "C:\Users\yahyaaba\Documents\GitHub\JavaScript\atom-ide-datatip\typings\atom-ide.d.ts"
```

**Comment by lierdakil** [comment]
I can't reproduce locally. This might be an issue with the custom TypeScript version you're using (apparently located in `C:\Users\yahyaaba\node_modules\typescript\`)

**Comment by aminya** [comment]
Try opening a TS file from another project in the current project.

**Comment by lierdakil** [comment]
Still can't reproduce. You'll have to write a detailed reproduction guide I'm afraid. But the error is thrown by TypeScript server, not the package itself, it's only re-repored via console. So I still suspect the issue is your local TypeScript installation.

**Comment by aminya** [comment]
This is still an issue

**Comment by lierdakil** [comment]
Well I still can't reproduce.

**Comment by aminya** [comment]
I am not lying though 😄. I try to provide you a reproduction. Could you open the issue again?

**Comment by aminya** [comment]
Still an issue as I remember

**Comment by aminya** [comment]
Probably related to https://github.com/atom-community/atom-languageclient/pull/11

**Comment by lierdakil** [comment]
> Probably related to [atom-community/atom-languageclient#11](https://github.com/atom-community/atom-languageclient/pull/11)

Likely not, since atom-ts doesn't use atom-languageclient (can't, tsserver isn't LSP-compliant)
