### ISSUE TITLE
Error:  "Failed to activate the atom-typescript package"

### ISSUE THREAD

**Issue by whiny-nil** [TypeStrong/atom-typescript#1553]
1. Install atom-typescript (and possibly the stuff below?)
2.Open a typescript file

**Atom**: 1.38.2 x64
**Electron**: 2.0.18
**OS**: Mac OS X 10.14.6
**Thrown From**: [atom-typescript](https://github.com/TypeStrong/atom-typescript) package 13.9.1

### Stack Trace

Failed to activate the atom-typescript package

```
At Invalid regular expression: /(?:(?![\u{10000}-\u{10FFFF}])[\$_\p{Lu}\p{Ll}\p{Lt}\p{Lm}\p{Lo}\p{Nl}])(?:(?![\u{10000}-\u{10FFFF}])[\$_\p{Lu}\p{Ll}\p{Lt}\p{Lm}\p{Lo}\p{Nl}\u200C\u200D\p{Mn}\p{Mc}\p{Nd}\p{Pc}])*$/: Invalid escape

SyntaxError: Invalid regular expression: /(?:(?![\u{10000}-\u{10FFFF}])[\$_\p{Lu}\p{Ll}\p{Lt}\p{Lm}\p{Lo}\p{Nl}])(?:(?![\u{10000}-\u{10FFFF}])[\$_\p{Lu}\p{Ll}\p{Lt}\p{Lm}\p{Lo}\p{Nl}\u200C\u200D\p{Mn}\p{Mc}\p{Nd}\p{Pc}])*$/: Invalid escape
    at /packages/atom-typescript/dist/main/atom/autoCompleteProvider.js:107:25)
    at /packages/atom-typescript/dist/main/atom/autoCompleteProvider.js:217:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147172)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150720)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:60:45)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146462)
    at /packages/atom-typescript/dist/main/pluginManager.js:18:32)
    at /packages/atom-typescript/dist/main/pluginManager.js:314:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:147172)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:150720)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:60:45)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146462)
    at Object.activate (/packages/atom-typescript/dist/main/atomts.js:10:31)
    at Package.activateNow (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3418998)
    at string.e.trim.length.activationHookSubscriptions.add.packageManager.onDidTriggerActivationHook (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:2445)
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1206583)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1208024)
    at PackageManager.triggerDeferredActivationHooks (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:381556)
    at Promise.all.then (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:380354)
    at <anonymous>
```

### Commands

```
```

### Non-Core Packages

```
after-dark-syntax 0.1.0 
atom-material-syntax-dark 1.0.0 
atom-material-syntax-light 0.4.6 
atom-material-ui 2.1.3 
atom-monokai 0.10.9 
atom-monokai-dark 0.4.0 
atom-oceanic-next-italic 0.1.1 
atom-typescript 13.9.1 
autoclose-html 0.23.0 
bracket-colorizer 1.4.0 
busy-signal 2.0.1 
chester-atom-syntax 0.3.2 
cursor-history 0.14.0 
fonts 3.11.0 
goto-definition 1.3.4 
gruvbox-plus-syntax 1.3.1 
ide-haskell 2.4.1 
intentions 1.1.5 
isotope-light-ui 2.3.0 
jsx-comment 0.2.0 
kecleon-ui 0.1.1 
language-haml 0.32.1 
language-haskell 1.20.0 
language-javascript-jsx 0.3.7 
language-vue 0.26.0 
linter 2.3.1 
linter-eslint 8.5.5 
linter-rubocop 2.5.7 
linter-stylelint 4.5.1 
linter-tslint 1.10.43 
linter-ui-default 1.8.1 
markdown-preview-plus 3.9.2 
markdown-scroll-sync 2.1.2 
oceanic-next-italic-white 0.1.3 
one-dark-italic-syntax 1.1.0 
prettier-atom 0.60.1 
rainbow-tree 1.0.1 
seti-syntax 1.2.0 
seti-ui 1.11.0 
Sublime-Style-Column-Selection 1.7.5 
tester 1.4.0 
tester-jest 1.2.4 
theme-for-a-summers-day-syntax 0.0.0 
theme-switch 0.6.0 
tomorrow-night-eighties-syntax 1.1.0 
uuidgen 1.4.0 
warn-before-quitting 0.1.7 
```

**Comment by lierdakil** [comment]
Ouch. Sorry, apparently I forgot to bump the lower Atom version in v13.5.1. Can't really do much about that now. v13.5.0 or earlier should work with your Atom version. I would suggest you upgrade Atom instead of downgrading Atom-TypeScript though.

**Comment by whiny-nil** [comment]
I'll give that a try, thanks!

**Comment by whiny-nil** [comment]
All good after updating Atom.  Thank you very much for your quick response, I appreciate it!

**Comment by tvallois** [comment]
Idk if this is the same issue but i still have the issue with `atom.1.55.0-nightly` only on dev mode.

**Comment by lierdakil** [comment]
We don't support nightly builds. But if you want to help, post the complete report in a new issue. To copy the complete error report to clipboard, click on the small clipboard-looking icon when the error pops up:
![atom-report](https://user-images.githubusercontent.com/7275622/98469566-7cd37580-21f1-11eb-809c-5168a48eecfc.png)

**Comment by rjousse18** [comment]
I have the same error with atom 1.54

**Comment by ThatXliner** [comment]
This happens on stable only on dev mode

**Comment by lierdakil** [comment]
@ThatXliner for the love of God, it's not that hard to open a new issue, is it?

I'll fix the issue shortly.

**Comment by lierdakil** [comment]
Aw, fudge. That's a bug in parcel. Hold on.

**Comment by aminya** [comment]
Try `parcel 2 beta-3.1` or `beta-2`

**Comment by lierdakil** [comment]
v14.3.1 should be fine. Or at least it seems to be on my end.

parcel 2.0 beta-2 was exactly the version that manifested this particular issue prior, while beta-1 was fine. now it's vice versa. pretty annoying heisenbug if you ask me. upstream issue: https://github.com/parcel-bundler/parcel/issues/5091
