### ISSUE TITLE
Atom-Typescript error: Cannot read property 'install' of undefined

### ISSUE THREAD

**Issue by hasenbalg** [TypeStrong/atom-typescript#1563]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.51.0 x64
**Electron**: 5.0.13
**OS**: Ubuntu 18.04.5
**Thrown From**: [atom-typescript](https://github.com/TypeStrong/atom-typescript) package 14.0.0

### Stack Trace

Atom-Typescript error: Cannot read property 'install' of undefined

```
At TypeError: Cannot read property 'install' of undefined

TypeError: Cannot read property 'install' of undefined
    at /packages/atom-typescript/dist/main.js:9:294452
    at /packages/atom-typescript/dist/main.js:9:294482)
    at processImmediate (internal/timers.js:443:21)
```

### Commands

```
     -0:52.1.0 application:add-project-folder (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:35.9.0 application:open-folder (div.panels-item)
```

### Non-Core Packages

```
atom-typescript 14.0.0 
ide-typescript 0.9.1 
```

**Comment by lierdakil** [comment]
Thanks for the report! Should be fixed in v14.0.1.
