### ISSUE TITLE
Atom-Typescript error: Debug Failure. Expected C:/spring5/angular/clientes-app/tsconfig.json === ...

### ISSUE THREAD

**Issue by Stalyn19** [TypeStrong/atom-typescript#1577]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.54.0 x64
**Electron**: 6.1.12
**OS**: Unknown Windows version
**Thrown From**: [atom-typescript](https://github.com/TypeStrong/atom-typescript) package 14.1.2

### Stack Trace

Atom-Typescript error: Debug Failure. Expected C:/spring5/angular/clientes-app/tsconfig.json === C:\spring5\angular\clientes-app\tsconfig.json. 

```
At Error: Debug Failure. Expected C:/spring5/angular/clientes-app/tsconfig.json === C:\spring5\angular\clientes-app\tsconfig.json. 

Error: Debug Failure. Expected C:/spring5/angular/clientes-app/tsconfig.json === C:\spring5\angular\clientes-app\tsconfig.json. 
    at attachFileToDiagnostic (/packages/atom-typescript/node_modules/typescript/lib/typescript.js:18645:18)
    at Object.attachFileToDiagnostics (/packages/atom-typescript/node_modules/typescript/lib/typescript.js:18677:42)
    at Object.parseJsonText (/packages/atom-typescript/node_modules/typescript/lib/typescript.js:28704:46)
    at Object.parseJsonText (/packages/atom-typescript/node_modules/typescript/lib/typescript.js:28450:23)
    at parseConfigFileTextToJson (/packages/atom-typescript/node_modules/typescript/lib/typescript.js:37181:33)
    at Object.readConfigFile (/packages/atom-typescript/node_modules/typescript/lib/typescript.js:37172:48)
    at Ae (/packages/atom-typescript/dist/main.js:1:102508)
    at Ie (/packages/atom-typescript/dist/main.js:1:102213)
    at hu.readConfigFile (/packages/atom-typescript/dist/main.js:1:294469)
    at /packages/atom-typescript/dist/main.js:1:294342
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:1190181)
    at Emitter.emit (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:1191622)
    at File.handleNativeChangeEvent (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:14:1136627)
    at PathWatcher.<anonymous> (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:14:1137320)
    at PathWatcher.onChange (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:14:11411)
    at PathWatcher.onChange (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:14:11867)
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:1190181)
    at Emitter.emit (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:11:1191622)
    at HandleWatcher.onEvent (~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:14:10119)
    at ~/AppData/Local/atom/app-1.54.0/resources/app/static/<embedded>:14:12613
```

### Commands

```
     -4:49.4.0 core:move-down (input.hidden-input)
  2x -4:49.1.0 core:move-left (input.hidden-input)
     -4:47.6.0 core:move-right (input.hidden-input)
     -4:47.2.0 core:move-down (input.hidden-input)
  2x -4:46.9.0 core:move-left (input.hidden-input)
     -4:45.9.0 core:move-right (input.hidden-input)
     -4:45.5.0 core:move-down (input.hidden-input)
  2x -4:45.2.0 core:move-left (input.hidden-input)
     -4:43.3.0 core:move-right (input.hidden-input)
     -4:41.7.0 intentions:highlight (input.hidden-input)
     -4:41.2.0 core:save (input.hidden-input)
     -0:20.1.0 editor:newline (input.hidden-input)
     -0:19.8.0 intentions:highlight (input.hidden-input)
     -0:19.5.0 core:paste (input.hidden-input)
     -0:16.6.0 intentions:highlight (input.hidden-input)
     -0:16.1.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
angular-2-typeScript-snippets 0.7.0 
atom-bootstrap3 1.2.12 
atom-bootstrap4 1.4.0 
atom-typescript 14.1.2 
autocomplete-clang 0.13.1 
bootstrap3-snips 0.1.1 
build 0.70.0 
busy-signal 2.0.1 
emmet 2.4.3 
file-icons 2.1.46 
intentions 1.1.5 
language-ini 1.23.0 
linter 3.3.0 
linter-gcc2 0.8.8 
linter-ui-default 3.2.0 
minimap 4.39.7 
platformio-ide-terminal 2.10.1 
tool-bar 1.4.2 
v-bootstrap4 0.2.2 
```

**Comment by lierdakil** [comment]
This error is thrown from tsserver. Apparently this is a bug in tsc, but it generally signals "bad" (i.e. invalid) `tsconfig.json`. Try another TypeScript version. If this happens with the bundled version (v4.0.3 I think at the moment of writing), I will treat it as a request to update it.

**Comment by lierdakil** [comment]
I've released v14.2.0 which updates the bundled typescript version. Hopefully this issue is fixed there.

**Comment by lislon** [comment]
I had same error and the reason was the incorrect JSON format in `tsconfig.json` (mising comma)

**Comment by mlaksi** [comment]
> I had same error and the reason was the incorrect JSON format in `tsconfig.json` (mising comma)

This solved my issue, too (06/2023)
