### ISSUE TITLE
Failed to load the atom-typescript package

### ISSUE THREAD

**Issue by chai2010** [TypeStrong/atom-typescript#211]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.187.0
**System**: Mac OS X 10.10.2
**Thrown From**: [atom-typescript](https://github.com/TypeStrong/atom-typescript) package, v1.12.0

### Stack Trace

Failed to load the atom-typescript package

```
At Cannot find module 'lru-cache'

Error: Cannot find module 'lru-cache'
    at Module._resolveFilename (module.js:351:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:383:52)
    at Function.Module._load (module.js:293:25)
    at Module.require (module.js:380:17)
    at require (module.js:399:17)
    at /Users/chaishushan/.atom/packages/atom-typescript/node_modules/glob-expand/node_modules/glob/node_modules/minimatch/minimatch.js:35:11
    at Object.<anonymous> (/Users/chaishushan/.atom/packages/atom-typescript/node_modules/glob-expand/node_modules/glob/node_modules/minimatch/minimatch.js:1051:3)
    at Module._compile (module.js:475:26)
    at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app/src/babel.js:162:21)
    at Module.load (module.js:370:32)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "go-plus",
      "filetype-color",
      "color-picker",
      "git-log",
      "autocomplete-html",
      "autocomplete-plus"
    ],
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-typescript, v1.12.0
file-icons, v1.5.1
language-cmake, v0.1.1
linter, v0.12.0
minimap, v4.6.0
symbols-tree-view, v0.6.1

# Dev
No dev packages
```

**Comment by chai2010** [comment]
It is OK. sorry.

**Comment by tagazok** [comment]
It doesn't work for me. I have this error :

$> apm install atom-typescript
Installing atom-typescript to /Users/olivier/.atom/packages
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: ENOSPC, write

**Comment by basarat** [comment]
@tagazok need more info please. Also try : https://github.com/TypeStrong/atom-typescript/blob/master/docs/faq.md#failed-to-update

**Comment by petrsimon** [comment]
Hi
I'm getting this stacktrace:
```
**Atom Version**: 0.210.0
**System**: Mac OS X 10.10.3
**Thrown From**: [atom-typescript](https://github.com/TypeStrong/atom-typescript) package, v4.5.16


### Stack Trace

Failed to load the atom-typescript package

At EISDIR: illegal operation on a directory, read

Error: EISDIR: illegal operation on a directory, read
    at Error (native)
    at Object.fs.readSync (fs.js:596:19)
    at Object.fs.readFileSync (fs.js:428:28)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:369:29)
    at Object.makeTsGlobal (/Users/petr/.atom/packages/atom-typescript/dist/typescript/makeTypeScriptGlobal.js:47:28)
    at Object.<anonymous> (/Users/petr/.atom/packages/atom-typescript/dist/main/atomts.js:3:24)
    at Module._compile (module.js:452:26)
    at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:162:21)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
```
Have tried reinstalling using `apm` as suggested in the faq, but problem remains. I tried this in a clean install.

**Comment by basarat** [comment]
@petrsimon It seems *your atom instance* doesn't have read writes to `/Users/petr/.atom/packages`:

* Which user is *atom* running as?
* Can that user access `/Users/petr/.atom/packages/atom-typescript`?

**Comment by petrsimon** [comment]
That's what I thought, but that all seems fine. The user is correct. Permissions are fine and other packages work fine. Only atom-typescript throws like this. It suddenly started throwing like this with version around 4.5.13 or 14.

**Comment by basarat** [comment]
Ahh sorry the line : https://github.com/TypeStrong/atom-typescript/blob/master/dist/typescript/makeTypeScriptGlobal.js#L47 is pointing to a *custom typescriptServices* < are you using this option?

**Comment by petrsimon** [comment]
That's it!

**Comment by petrsimon** [comment]
My bad. Got confused by the settings in Webstorm and forgot to include the filename.
