### ISSUE TITLE
Uncaught TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by maolion** [TypeStrong/atom-typescript#295]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.194.0
**System**: Mac OS X 10.10.3
**Thrown From**: [atom-typescript](https://github.com/TypeStrong/atom-typescript) package, v3.2.0

### Stack Trace

Uncaught TypeError: Cannot read property 'name' of undefined

```
At /Users/joye/.atom/packages/atom-typescript/dist/worker/lib/workerLib.js:89

TypeError: Cannot read property 'name' of undefined
  at /Users/joye/.atom/packages/atom-typescript/dist/worker/lib/workerLib.js:89:31
  at Object.build (/Users/joye/.atom/packages/atom-typescript/dist/worker/parent.js:38:34)
  at atom-workspace.<anonymous> (/Users/joye/.atom/packages/atom-typescript/dist/main/atom/commands/commands.js:53:16)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:519:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:354:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:178:20)

```

### Commands

```
     -0:00.7.0 typescript:build (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "brackets-dark"
    ],
    "disabledPackages": [
      "autocomplete-paths",
      "color-picker",
      "l-paths"
    ]
  },
  "atom-typescript": {
    "preferredQuoteCharacter": "'"
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
atom-typescript, v3.2.0
autocomplete-plus, v2.12.0
brackets-dark, v0.4.0
linter, v0.12.1
minimap, v4.7.6
react, v0.11.7
set-syntax, v0.2.1
seti-ui, v0.6.3

# Dev
No dev packages
```

**Comment by vilic** [comment]
https://github.com/TypeStrong/atom-typescript/blob/master/dist/main/lang/projectService.js

`projectService.build` is missing from the compiled file, I noticed it's there in source code. Unsuccessfully compiled?

**Comment by busbina** [comment]
I got this too on Windows with just the basic TypeScript tutorial.

**Comment by basarat** [comment]
Sorry about this. I'll write up a test framework soon to prevent this from happening again.
