### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getPath' of undefined

### ISSUE THREAD

**Issue by patrickjtoy** [TypeStrong/atom-typescript#310]
[Enter steps to reproduce below:]

1. No steps, just re-focused the editor after having it unfocused and the editor crashed.

**Atom Version**: 0.194.0
**System**: Microsoft Windows 8.1 Pro
**Thrown From**: [atom-typescript](https://github.com/TypeStrong/atom-typescript) package, v4.0.11

### Stack Trace

Uncaught TypeError: Cannot read property 'getPath' of undefined

```
At C:\Users\Patrick\.atom\packages\atom-typescript\dist\main\atom\atomUtils.js:33

TypeError: Cannot read property 'getPath' of undefined
  at Object.getFilePathPosition (C:\Users\Patrick\.atom\packages\atom-typescript\dist\main\atom\atomUtils.js:33:26)
  at C:\Users\Patrick\.atom\packages\atom-typescript\dist\main\atom\editorSetup.js:18:40
  at later (C:\Users\Patrick\.atom\packages\atom-typescript\dist\main\lang\utils.js:186:31)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "base16-ocean-dark-syntax"
    ],
    "projectHome": "C:\\Users\\Patrick\\Workspace\\APS2\\src"
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
atom-typescript, v4.0.11
autocomplete-plus, v2.12.0
base16-ocean-dark-syntax, v1.0.1
emmet, v2.3.8
language-cshtml, v0.1.1
last-cursor-position, v0.8.0
linter, v0.12.1
minimap, v4.7.6
open-last-project, v0.4.1
pain-split, v1.3.1
project-manager, v1.15.5

# Dev
No dev packages
```

**Comment by lazutkin** [comment]
Just got it

```
**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.4
**Thrown From**: [atom-typescript](https://github.com/TypeStrong/atom-typescript) package, v4.8.4


### Stack Trace

Uncaught TypeError: Cannot read property 'getPath' of undefined

```
At /Users/dimka/.atom/packages/atom-typescript/dist/main/atomts.js:88

TypeError: Cannot read property 'getPath' of undefined
  at /Users/dimka/.atom/packages/atom-typescript/dist/main/atomts.js:88:69
  at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:379:3)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "projectHome": "~/Projects",
    "audioBeep": false,
    "disabledPackages": [
      "vim-mode",
      "compare-files",
      "go-plus",
      "npm-docs",
      "npm-docs",
      "linter-tslint"
    ]
  },
  "atom-typescript": {}
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
atom-typescript, v4.8.4
atom-yamljson, v0.2.3
autocomplete-emojis, v2.2.2
coffee-compile, v0.16.1
docblockr, v0.7.2
file-icons, v1.5.8
git-tab-status, v1.9.2
language-cypher, v0.3.0
language-json, v0.15.0
language-pegjs, v0.5.0
last-cursor-position, v0.9.0
linter, v1.1.0
minimap, v4.10.1
minimap-git-diff, v4.1.3
pretty-json, v0.4.1
raml, v0.1.0
tasks, v2.1.0

# Dev
No dev packages
```


```
