### ISSUE TITLE
Uncaught TypeError: Cannot read property 'toggle' of undefined

### ISSUE THREAD

**Issue by umurgdk** [TypeStrong/atom-typescript#311]
1. Open Command Panel
2. Open Typescript Context Actions
3. Toggle Typescript Panel

**Atom Version**: 0.194.0
**System**: Mac OS X 10.10.3
**Thrown From**: [atom-typescript](https://github.com/TypeStrong/atom-typescript) package, v4.0.11

### Stack Trace

Uncaught TypeError: Cannot read property 'toggle' of undefined

```
At /Users/umurgedik/.atom/packages/atom-typescript/dist/main/atom/views/contextView.js:35

TypeError: Cannot read property 'toggle' of undefined
  at ContextView.confirmed (/Users/umurgedik/.atom/packages/atom-typescript/dist/main/atom/views/contextView.js:35:36)
  at ContextView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at HTMLLIElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:139:19)
  at HTMLOListElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4430:9)
  at HTMLOListElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4116:28)

```

### Commands

```
  2x -0:42 core:backspace (atom-text-editor.editor)
     -0:37.8.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor)
     -0:37.8.0 editor:newline (atom-text-editor.editor)
     -0:33.6.0 core:backspace (atom-text-editor.editor)
     -0:28.7.0 core:save (atom-text-editor.editor)
     -0:26.6.0 command-palette:toggle (atom-text-editor.editor)
  2x -0:24.9.0 core:backspace (atom-text-editor.editor.mini)
     -0:21.8.0 editor:consolidate-selections (atom-text-editor.editor.mini)
     -0:21.8.0 core:cancel (atom-text-editor.editor.mini)
     -0:21.3.0 markdown-writer:toggle-code-text (atom-text-editor.editor)
     -0:21.3.0 emmet:remove-tag (atom-text-editor.editor)
     -0:17.9.0 markdown-writer:toggle-code-text (atom-text-editor.editor)
     -0:17.9.0 emmet:remove-tag (atom-text-editor.editor)
     -0:16.4.0 core:save (atom-text-editor.editor)
     -0:14.7.0 command-palette:toggle (atom-text-editor.editor)
     -0:04.0 typescript:context-actions (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-light-ui",
      "monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
Stylus, v1.0.0
angularjs, v0.1.0
atom-typescript, v4.0.11
autocomplete-paths, v1.0.2
autocomplete-plus, v2.12.0
emmet, v2.3.8
language-jade, v0.4.0
language-rust, v0.4.3
linter, v0.12.1
markdown-writer, v1.1.2
monokai, v0.14.0
racer, v0.10.1
react, v0.11.7
typewriter, v0.3.2

# Dev
No dev packages
```

**Comment by basarat** [comment]
Don't see how this can happen. Closing for now till we get a repro, the following did not reproduce:

1. Open Command Panel
2. Open Typescript Context Actions
3. Toggle Typescript Panel

Hopefully its fixed in recent versions :rose:
