### ISSUE TITLE
Failed to activate the vim-mode package

### ISSUE THREAD

**Issue by lazutkin** [TypeStrong/atom-typescript#325]
[Enter steps to reproduce below:]

1. install `vim-mode` plugin
2. disable `vim-mode`
3. enable `vim-mode`

**Atom Version**: 0.196.0
**System**: Mac OS X 10.10.2
**Thrown From**: [atom-typescript](https://github.com/TypeStrong/atom-typescript) package, v4.1.0

### Stack Trace

Failed to activate the vim-mode package

```
At Cannot read property 'getPath' of undefined

TypeError: Cannot read property 'getPath' of undefined
  at Object.getFilePathPosition (/Users/dimka/.atom/packages/atom-typescript/dist/main/atom/atomUtils.js:33:26)
  at /Users/dimka/.atom/packages/atom-typescript/dist/main/atom/editorSetup.js:27:36
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at TextEditor.module.exports.TextEditor.cursorMoved (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1565:27)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:56:31
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Marker.module.exports.Marker.notifyObservers (/Applications/Atom.app/Contents/Resources/app.asar/src/marker.js:265:22)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/marker.js:47:24
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Marker.module.exports.Marker.update (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:514:22)
  at Marker.module.exports.Marker.setHeadPosition (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/marker.js:184:19)
  at Marker.module.exports.Marker.setHeadBufferPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/marker.js:172:32)
  at Marker.module.exports.Marker.setHeadScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/marker.js:182:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:121:31
  at Cursor.module.exports.Cursor.changePosition (/Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:683:7)
  at Cursor.module.exports.Cursor.setScreenPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:119:19)
  at Cursor.module.exports.Cursor.moveLeft (/Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:311:21)
  at VimState.module.exports.VimState.deactivateInsertMode (/Users/dimka/.atom/packages/vim-mode/lib/vim-state.coffee:405:14)
  at VimState.module.exports.VimState.activateCommandMode (/Users/dimka/.atom/packages/vim-mode/lib/vim-state.coffee:368:6)
  at new VimState (/Users/dimka/.atom/packages/vim-mode/lib/vim-state.coffee:42:8)
  at /Users/dimka/.atom/packages/vim-mode/lib/vim-mode.coffee:22:24
  at Workspace.module.exports.Workspace.observeTextEditors (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:267:9)
  at Object.module.exports.activate (/Users/dimka/.atom/packages/vim-mode/lib/vim-mode.coffee:16:37)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:222:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:203:30
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:147:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:195:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:434:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:303:19
  at /Applications/Atom.app/Contents/Resources/app.asar/src/config.js:574:20
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Config.module.exports.Config.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:736:29)
  at Config.module.exports.Config.setRawValue (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:551:19)
  at Config.module.exports.Config.set (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:233:14)
  at Config.module.exports.Config.removeAtKeyPath (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:343:12)
  at Package.module.exports.Package.enable (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:132:26)
  at PackageManager.module.exports.PackageManager.enablePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:132:14)
  at HTMLButtonElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:252:27)
  at HTMLButtonElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at HTMLButtonElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "projectHome": "~/Projects",
    "audioBeep": false
  },
  "atom-typescript": {}
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
atom-typescript, v4.1.0
autocomplete-plus, v2.12.1
coffee-compile, v0.13.0
language-pegjs, v0.5.0
linter, v0.12.1
linter-tslint, v0.2.1
minimap, v4.8.0
pretty-json, v0.3.3
vim-mode, v0.45.0

# Dev
No dev packages
```

**Comment by basarat** [comment]
refs : https://github.com/TypeStrong/atom-typescript/issues/310 Will be tracked there. Thanks for the report :heart:
