### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by Aedaeum** [TypeStrong/atom-typescript#339]
I simply highlighted an area of code, deleted it, then undid those changes with `ctrl+z`.

Below is the range I deleted:
https://github.com/Aedaeum/amenaeble/blob/master/controllers/router.ts#L36-L97

I can reproduce this every time. I even tried restarting Atom, still crashes.
I deleted/undid other pieces of code without error, but somehow removing the section I highlighted above and undoing it, crashes every time.

**Atom Version**: 0.198.0
**System**: Microsoft Windows 8.1
**Thrown From**: [atom-typescript](https://github.com/TypeStrong/atom-typescript) package, v4.1.7

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At C:\Users\Aedaeum\.atom\packages\atom-typescript\dist\main\atom\typescriptGrammar.js:40

TypeError: Cannot read property 'length' of undefined
  at TypeScriptSemanticGrammar.tokenizeLine (C:\Users\Aedaeum\.atom\packages\atom-typescript\dist\main\atom\typescriptGrammar.js:40:24)
  at TokenizedBuffer.module.exports.TokenizedBuffer.buildTokenizedLineForRowWithText (C:\Users\Aedaeum\AppData\Local\atom\app-0.198.0\resources\app.asar\src\tokenized-buffer.js:491:28)
  at TokenizedBuffer.module.exports.TokenizedBuffer.buildTokenizedLineForRow (C:\Users\Aedaeum\AppData\Local\atom\app-0.198.0\resources\app.asar\src\tokenized-buffer.js:480:19)
  at TokenizedBuffer.module.exports.TokenizedBuffer.retokenizeWhitespaceRowsIfIndentLevelChanged (C:\Users\Aedaeum\AppData\Local\atom\app-0.198.0\resources\app.asar\src\tokenized-buffer.js:371:43)
  at TokenizedBuffer.module.exports.TokenizedBuffer.handleBufferChange (C:\Users\Aedaeum\AppData\Local\atom\app-0.198.0\resources\app.asar\src\tokenized-buffer.js:347:18)
  at C:\Users\Aedaeum\AppData\Local\atom\app-0.198.0\resources\app.asar\src\tokenized-buffer.js:55:24
  at Emitter.module.exports.Emitter.emit (C:\Users\Aedaeum\AppData\Local\atom\app-0.198.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at TextBuffer.module.exports.TextBuffer.applyPatch (C:\Users\Aedaeum\AppData\Local\atom\app-0.198.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:550:20)
  at BufferPatch.module.exports.BufferPatch.applyTo (C:\Users\Aedaeum\AppData\Local\atom\app-0.198.0\resources\app.asar\node_modules\text-buffer\lib\buffer-patch.js:57:21)
  at Transaction.module.exports.Transaction.applyTo (C:\Users\Aedaeum\AppData\Local\atom\app-0.198.0\resources\app.asar\node_modules\text-buffer\lib\transaction.js:70:15)
  at History.module.exports.History.undo (C:\Users\Aedaeum\AppData\Local\atom\app-0.198.0\resources\app.asar\node_modules\text-buffer\lib\history.js:91:24)
  at TextBuffer.module.exports.TextBuffer.undo (C:\Users\Aedaeum\AppData\Local\atom\app-0.198.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:639:27)
  at TextEditor.module.exports.TextEditor.undo (C:\Users\Aedaeum\AppData\Local\atom\app-0.198.0\resources\app.asar\src\text-editor.js:1147:19)
  at TextEditor.atom.commands.add.stopEventPropagation.core:undo (C:\Users\Aedaeum\AppData\Local\atom\app-0.198.0\resources\app.asar\src\text-editor-element.js:318:19)
  at atom-text-editor.newCommandListeners.(anonymous function) (C:\Users\Aedaeum\AppData\Local\atom\app-0.198.0\resources\app.asar\src\text-editor-element.js:286:32)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Aedaeum\AppData\Local\atom\app-0.198.0\resources\app.asar\src\command-registry.js:238:29)
  at C:\Users\Aedaeum\AppData\Local\atom\app-0.198.0\resources\app.asar\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\Aedaeum\AppData\Local\atom\app-0.198.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:519:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\Aedaeum\AppData\Local\atom\app-0.198.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:354:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\Aedaeum\AppData\Local\atom\app-0.198.0\resources\app.asar\src\window-event-handler.js:178:20)

```

### Commands

```
     -9:28.2.0 core:copy (atom-text-editor.editor.is-focused)
  2x -9:25.3.0 editor:newline (atom-text-editor.editor.is-focused)
     -9:24.9.0 core:paste (atom-text-editor.editor.is-focused)
     -9:22.6.0 editor:newline (atom-text-editor.editor.is-focused)
 13x -9:15 core:backspace (atom-text-editor.editor.is-focused)
     -9:00.6.0 core:save (atom-text-editor.editor.is-focused)
     -9:00.6.0 linter:lint (atom-text-editor.editor.is-focused)
     -0:08.7.0 core:delete (atom-text-editor.editor.is-focused)
  2x -0:04.0 core:undo (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "resize-indent",
      "typescript-atomizer",
      "language-stylus",
      "atom-color-highlight",
      "language-mustache",
      "archive-view",
      "bookmarks",
      "valign",
      "grammar-selector"
    ],
    "themes": [
      "flatland-dark-ui",
      "subtle-syntax"
    ]
  },
  "atom-typescript": {}
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
atom-typescript, v4.1.7
autocomplete-css, v0.7.2
autocomplete-html, v0.7.1
autocomplete-plus, v2.13.1
file-icons, v1.5.5
flatland-dark-ui, v0.2.4
keybinding-cheatsheet, v0.0.9
language-jade, v0.4.0
linter, v0.12.2
minimap, v4.8.0
project-manager, v1.15.5
project-palette-finder, v2.4.17
subtle-syntax, v0.0.0
tab-length, v0.1.0
tabs-to-spaces, v0.10.0

# Dev
No dev packages
```

**Comment by basarat** [comment]
More info for repro : if you select from *top to bottom* and delete and undo then nothing bad happens. But if you select from *bottom to top* and then delete and undo then this happens. 

Probably a bug in atom. I'll investigate further.

**Comment by basarat** [comment]
`4.2.2` :hospital:

**Comment by Aedaeum** [comment]
You're so fast! :heart:
