### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getBoundingClientRect' of undefined

### ISSUE THREAD

**Issue by FalloutPL** [TypeStrong/atom-typescript#379]
### Repro 

1. Open a d.ts in the editor.
2. Delete the same file in the tree view.

**Atom Version**: 0.206.0
**System**: Windows 7 x64
**Thrown From**: [atom-typescript](https://github.com/TypeStrong/atom-typescript) package, v4.5.7

### Stack Trace

Uncaught TypeError: Cannot read property 'getBoundingClientRect' of undefined

```
At C:\Users\Dom\.atom\packages\atom-typescript\dist\main\atom\tooltipManager.js:106

TypeError: Cannot read property 'getBoundingClientRect' of undefined
  at pixelPositionFromMouseEvent (C:\Users\Dom\.atom\packages\atom-typescript\dist\main\atom\tooltipManager.js:106:68)
  at showExpressionType (C:\Users\Dom\.atom\packages\atom-typescript\dist\main\atom\tooltipManager.js:54:23)
  at C:\Users\Dom\.atom\packages\atom-typescript\dist\main\atom\tooltipManager.js:42:59

```

### Commands

```
  2x -0:26.3.0 core:move-left (atom-text-editor.editor.is-focused)
  2x -0:25.9.0 core:delete (atom-text-editor.editor.is-focused)
     -0:25.5.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:25.1.0 core:move-right (atom-text-editor.editor.is-focused)
  2x -0:24.9.0 core:delete (atom-text-editor.editor.is-focused)
     -0:24.5.0 core:move-down (atom-text-editor.editor.is-focused)
  2x -0:24.4.0 core:move-right (atom-text-editor.editor.is-focused)
  2x -0:23.9.0 core:delete (atom-text-editor.editor.is-focused)
     -0:23.6.0 core:save (atom-text-editor.editor.is-focused)
     -0:23.6.0 linter:lint (atom-text-editor.editor.is-focused)
     -0:19.8.0 core:close (atom-text-editor.editor.is-focused)
     -0:15.5.0 core:move-down (atom-text-editor.editor.is-focused)
  2x -0:15.3.0 core:delete (atom-text-editor.editor.is-focused)
     -0:14.9.0 core:save (atom-text-editor.editor.is-focused)
     -0:14.9.0 linter:lint (atom-text-editor.editor.is-focused)
     -0:13.3.0 core:close (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "typescript-atomizer"
    ]
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
atom-typescript, v4.5.7
last-cursor-position, v0.9.0
linter, v0.12.6

# Dev
No dev packages
```

**Comment by nycdotnet** [comment]
I had this happen when doing close all tabs.

**Comment by atsu85** [comment]
I got this problem when closing tabs one-by-one

**Comment by shamb** [comment]
Steps to repro
1. Open a d.ts in the editor.
2. Delete the same file in the tree view.

**Comment by basarat** [comment]
@shamb thanks. I've updated original issue report with your repro steps

**Comment by andresgutierrez** [comment]
+1

**Comment by basarat** [comment]
closed with https://github.com/TypeStrong/atom-typescript/pull/424
