### ISSUE TITLE
Could not find file logged to the console if there is an invalid file reference

### ISSUE THREAD

**Issue by petrsimon** [TypeStrong/atom-typescript#399]
If you have a reference tag to a non existent file our code tries to read it. It should actually do an fs.existsSync test and bail earlier. Code is in `tsconfig.ts`

---
# Original issue report for historical reasons

After one of the previous updates (around 4.5.13), Typescript suddenly stopped working. Finally I opened the console and found the error bellow. I tried to run `sync` as advised in the readme, but that throws these errors as well.

```
Error: Could not find file: '/path/to/myfile.ts'.
    at getValidSourceFile (evalmachine.<anonymous>:37146:23)
    at Object.getSyntacticDiagnostics (evalmachine.<anonymous>:37284:52)
    at getDiagnositcsByFilePath (/Users/petr/.atom/packages/atom-typescript/dist/main/lang/projectService.js:242:47)
    at Object.errorsForFile (/Users/petr/.atom/packages/atom-typescript/dist/main/lang/projectService.js:259:34)
    at Child.RequesterResponder.processRequest (/Users/petr/.atom/packages/atom-typescript/dist/worker/lib/workerLib.js:50:60)
    at process.<anonymous> (/Users/petr/.atom/packages/atom-typescript/dist/worker/lib/workerLib.js:222:23)
    at emitTwo (events.js:87:13)
    at process.emit (events.js:169:7)
    at handleMessage (child_process.js:306:10)
    at Pipe.channel.onread (child_process.js:334:11)
```

I tried to run completely fresh atom installation, but that did not help.

**Comment by basarat** [comment]
If you don't mind can you provide the actual `/path/to/myfile.ts`. That might give more context

**Comment by petrsimon** [comment]
Sure. The path has changed, so I followed the faq, but sync threw the same error (only visible in console).
`/Users/petr/dev/project/mobile/app/src/services/Platform.ts`

**Comment by basarat** [comment]
And restart fixed it?

**Comment by petrsimon** [comment]
Nope. Same error after restart, tried running sync and restarting couple of times.

**Comment by petrsimon** [comment]
Now I'm also getting this error, which did not show up before:
```
Error: Invalid Path
    at Object.getProjectSync (/Users/petr/.atom/packages/atom-typescript/dist/main/tsconfig/tsconfig.js:162:15)
    at getOrCreateProjectFile (/Users/petr/.atom/packages/atom-typescript/dist/main/lang/projectCache.js:73:36)
    at Object.getOrCreateProject (/Users/petr/.atom/packages/atom-typescript/dist/main/lang/projectCache.js:138:27)
    at Object.editText (/Users/petr/.atom/packages/atom-typescript/dist/main/lang/projectService.js:233:30)
    at Child.RequesterResponder.processRequest (/Users/petr/.atom/packages/atom-typescript/dist/worker/lib/workerLib.js:50:60)
    at process.<anonymous> (/Users/petr/.atom/packages/atom-typescript/dist/worker/lib/workerLib.js:222:23)
    at emitTwo (events.js:87:13)
    at process.emit (events.js:169:7)
    at handleMessage (child_process.js:306:10)
    at Pipe.channel.onread (child_process.js:334:11)
```

**Comment by basarat** [comment]
is this file linked to from a `reference` or an `import` or `tsconfig.json` by any chance?

**Comment by petrsimon** [comment]
It's caused by this tsconfig. I delete it, Atom generated new one and now it all works fine.
```
{
    "compilerOptions": {
        "target": "es5",
        "outDir": "../build",
        "removeComments": true
    },

    "files": [ "*.ts"]
}
```

**Comment by basarat** [comment]
> the file was referenced

That would cause it. I'll change the title of the issue and mark it up for grabs. Thanks :rose:

**Comment by petrsimon** [comment]
Thanks for you time!
