### ISSUE TITLE
Cannot find module 'ntypescript'

### ISSUE THREAD

**Issue by rogergl** [TypeStrong/atom-typescript#417]
This only happens if I clone the github repo.

Error: Cannot find module 'ntypescript'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.require.resolve (module.js:380:19)
    at Object.makeTsGlobal (/Users/roger/Documents/atom-typescript/dist/typescript/makeTypeScriptGlobal.js:20:49)
    at Object.<anonymous> (/Users/roger/Documents/atom-typescript/dist/main/atomts.js:3:24)
    at Module._compile (module.js:452:26)
    at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/babel.js:162:21)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)

**Comment by basarat** [comment]
> This only happens if I clone the github repo.

You need to run `npm install` now. Sorry about that : https://github.com/TypeStrong/atom-typescript/blob/master/CONTRIBUTING.md#setup-dev-machine

Relevant commit https://github.com/TypeStrong/atom-typescript/commit/f6b6cba49e12e2309298de7639a7fa4621f63da6
