### ISSUE TITLE
Uncaught TypeError: Cannot read property 'scopeName' of undefined

### ISSUE THREAD

**Issue by ivanvoznyakovsky** [TypeStrong/atom-typescript#419]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.3
**Thrown From**: [atom-typescript](https://github.com/TypeStrong/atom-typescript) package, v4.6.9

### Stack Trace

Uncaught TypeError: Cannot read property 'scopeName' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:130

TypeError: Cannot read property 'scopeName' of undefined
  at TokenizedBuffer.module.exports.TokenizedBuffer.setGrammar (/Applications/Atom.app/Contents/Resources/app.asar/src/tokenized-buffer.js:130:30)
  at DisplayBuffer.module.exports.DisplayBuffer.setGrammar (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1151:35)
  at TextEditor.module.exports.TextEditor.setGrammar (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2264:33)
  at ts-view.TsView.createdCallback (/Users/ivanvoznyakovsky/.atom/packages/atom-typescript/dist/main/atom/components/ts-view.js:22:16)
  at Function.jQuery.extend.buildFragment (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:5114:20)
  at Function.jQuery.parseHTML (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:8817:18)
  at LineMessageView.jQuery.fn.init (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:2762:33)
  at LineMessageView.View (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:158:24)
  at LineMessageView.View (/Users/ivanvoznyakovsky/.atom/packages/atom-typescript/dist/main/atom/views/view.js:10:16)
  at new LineMessageView (/Users/ivanvoznyakovsky/.atom/packages/atom-typescript/dist/main/atom/views/lineMessageView.js:11:16)
  at /Users/ivanvoznyakovsky/.atom/packages/atom-typescript/dist/main/atom/views/mainPanelView.js:404:48
  at Array.forEach (native)
  at Object.errorView.setErrors (/Users/ivanvoznyakovsky/.atom/packages/atom-typescript/dist/main/atom/views/mainPanelView.js:402:47)
  at /Users/ivanvoznyakovsky/.atom/packages/atom-typescript/dist/main/atomts.js:87:82

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
atom-alignment, v0.12.1
atom-typescript, v4.6.9
autocomplete-paths, v1.0.2
color-picker, v2.0.7
editorconfig, v1.0.0
emmet, v2.3.10
file-icons, v1.5.8
highlight-line, v0.11.0
linter, v1.0.9
minimap, v4.10.0
minimap-git-diff, v4.1.3
minimap-highlight-selected, v4.3.0
project-manager, v1.15.10

# Dev
No dev packages
```

**Comment by basarat** [comment]
My recent integration of the `atom-text-editor` into error view seems to have triggered this. I can't reproduce but I've been meaning to disable this integration for errors / build errors anyways, so I'll do that now :rose:
