### ISSUE TITLE
Error: No Project Found at Object.getProjectSync

### ISSUE THREAD

**Issue by Grokling** [TypeStrong/atom-typescript#436]
Brand new installation of atom-typescript(5.0.9), one.ts file in an otherwise empty directory.

```Error: No Project Found
    at Object.getProjectSync (/home/grokling/.atom/packages/atom-typescript/dist/main/tsconfig/tsconfig.js:177:36)
    at getOrCreateProjectFile (/home/grokling/.atom/packages/atom-typescript/dist/main/lang/projectCache.js:73:36)
    at Object.getOrCreateProject (/home/grokling/.atom/packages/atom-typescript/dist/main/lang/projectCache.js:140:27)
    at getDiagnositcsByFilePath (/home/grokling/.atom/packages/atom-typescript/dist/main/lang/projectService.js:242:34)
    at Object.errorsForFile (/home/grokling/.atom/packages/atom-typescript/dist/main/lang/projectService.js:260:34)
    at Child.RequesterResponder.processRequest (/home/grokling/.atom/packages/atom-typescript/dist/worker/lib/workerLib.js:49:60)
    at process.<anonymous> (/home/grokling/.atom/packages/atom-typescript/dist/worker/lib/workerLib.js:221:23)
    at emitTwo (events.js:87:13)
    at process.emit (events.js:169:7)
    at handleMessage (child_process.js:306:10)```

**Comment by basarat** [comment]
Having a full blown modal was unfortunate, I've removed that :rose: 

fwiw we no longer create a tsconfig, but do provide a command to do so, and also show you an error if one is not found. https://github.com/TypeStrong/atom-typescript/blob/master/docs/CHANGELOG.md#v500 

Motivation : People got annoyed that random `tsconfig.json`'s kept popping up. 

Fix in `v5.0.10`
