### ISSUE TITLE
Uncaught TypeError: Cannot read property 'updateFileStatus' of undefined

### ISSUE THREAD

**Issue by alexmsmartins** [TypeStrong/atom-typescript#439]
[Enter steps to reproduce below:]

1. Clicked to go back to a tab where a new .ts file was being edited.
2. Everytime I clicked, an error popup from atom appeared stopping me from getting the code to paste here.

**Atom Version**: 1.0.0
**System**: Ubuntu 14.04.2
**Thrown From**: [atom-typescript](https://github.com/TypeStrong/atom-typescript) package, v5.0.10

### Stack Trace

Uncaught TypeError: Cannot read property 'updateFileStatus' of undefined

```
At /home/alexandre/.atom/packages/atom-typescript/dist/main/atomts.js:49

TypeError: Cannot read property 'updateFileStatus' of undefined
  at /home/alexandre/.atom/packages/atom-typescript/dist/main/atomts.js:49:36
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at /usr/share/atom/resources/app.asar/src/pane-container.js:343:34
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (/usr/share/atom/resources/app.asar/src/pane.js:234:22)
  at Pane.module.exports.Pane.activateItem (/usr/share/atom/resources/app.asar/src/pane.js:298:21)
  at Pane.module.exports.Pane.activateItemAtIndex (/usr/share/atom/resources/app.asar/src/pane.js:292:19)
  at Pane.module.exports.Pane.activatePreviousItem (/usr/share/atom/resources/app.asar/src/pane.js:263:21)
  at Pane.module.exports.Pane.removeItem (/usr/share/atom/resources/app.asar/src/pane.js:372:16)
  at Pane.module.exports.Pane.destroyItem (/usr/share/atom/resources/app.asar/src/pane.js:442:16)
  at Pane.module.exports.Pane.destroyActiveItem (/usr/share/atom/resources/app.asar/src/pane.js:419:12)
  at Workspace.module.exports.Workspace.destroyActivePaneItem (/usr/share/atom/resources/app.asar/src/workspace.js:600:35)
  at Workspace.module.exports.Workspace.destroyActivePaneItemOrEmptyPane (/usr/share/atom/resources/app.asar/src/workspace.js:639:21)
  at atom-workspace.atom.commands.add.core:close (/usr/share/atom/resources/app.asar/src/workspace-element.js:308:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:241:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:180:20)

```

### Commands

```
     -2:59.8.0 core:cancel (div.settings-view.pane-item)
     -0:00.7.0 core:close (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
atom-typescript, v5.0.10
coffee-navigator, v0.0.16
coffee-porter, v0.8.1
language-scala-plus, v1.2.2
linter, v1.0.6
linter-coffeescript, v0.2.1
linter-scalac, v0.3.4
minimap, v4.10.2
scala-format, v0.1.8

# Dev
No dev packages
```

**Comment by helarqjsc** [comment]
By "new .ts file" do you mean that it was unsaved?

**Comment by helarqjsc** [comment]
I assume it happens when this:
https://github.com/TypeStrong/atom-typescript/blob/master/lib/main/atomts.ts#L111
gets called before this:
https://github.com/TypeStrong/atom-typescript/blob/master/lib/main/atomts.ts#L141
I don't how it can happen or how to reproduce it, though.

**Comment by alexmsmartins** [comment]
I am sorry it took so long for me to answer.
By new, I only meant I did not close Atom after starting to edit it. But I did save it.

It is a pity you cannot reproduce it. I do not know how to help you do it.

**Comment by basarat** [comment]
I just published a release with this fix. If you update atom typescript it should be fixed.
