### ISSUE TITLE
Uncaught Error: Could not resolve 'linter' to a package path

### ISSUE THREAD

**Issue by yoav-zibin** [TypeStrong/atom-typescript#477]
I just opened Atom after installing typescript (I think the issue is that there isn't any package path, i.e., no project was opened)

**Atom Version**: 0.165.0
**System**: linux 3.13.0-57-generic
**Thrown From**: [atom-typescript](https://github.com/TypeStrong/atom-typescript) package, v4.5.0

### Stack Trace

Uncaught Error: Could not resolve 'linter' to a package path

```
At /usr/share/atom/resources/app/src/package-manager.js:347

Error: Could not resolve 'linter' to a package path
  at PackageManager.module.exports.PackageManager.loadPackage (/usr/share/atom/resources/app/src/package-manager.js:347:15)
  at /usr/local/google/home/yzibin/.atom/packages/atom-typescript/dist/main/atomts.js:133:31
  at counter (/usr/local/google/home/yzibin/.atom/packages/atom-typescript/node_modules/atom-package-dependencies/index.js:14:15)
  at /usr/local/google/home/yzibin/.atom/packages/atom-typescript/node_modules/atom-package-dependencies/index.js:67:7
  at /usr/local/google/home/yzibin/.atom/packages/atom-typescript/node_modules/atom-package-dependencies/node_modules/shelljs/src/exec.js:107:7
  at ChildProcess.exithandler (child_process.js:736:7)
  at ChildProcess.emit (events.js:110:17)
  at maybeClose (child_process.js:1013:16)
  at Socket.<anonymous> (child_process.js:1181:11)
  at Socket.emit (events.js:107:17)
  at Pipe.close (net.js:461:12)

```

### Commands

```
```

### Config

```
{}
```

### Installed Packages

```coffee
# User
.bin, vundefined
atom-typescript, v4.5.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by basarat** [comment]
That's a REALLY old atom / atomts version. Please upgrade both to latest 🌹
