### ISSUE TITLE
Error opening a TypeScript file that is intentionally not included in the glob

### ISSUE THREAD

**Issue by nycdotnet** [TypeStrong/atom-typescript#479]
I'm working on grunt-ts today.  I've set up the tsconfig.json with this filesGlob:

```
    "filesGlob": [
        "./defs/**/*.ts",
        "./tasks/**/*.ts",
        "./test/*.ts"
    ],
```

If I open one of the TypeScript files in the tasks-internal folder (which is intentionally NOT included in the glob), I get this big red error:

```
Error: Could not find file: 'C:/Users/Steve/Documents/GitHub/grunt-ts/tasks-internal/modules/amdLoader.ts'.
    at getValidSourceFile (evalmachine.<anonymous>:41795:23)
    at Object.getSyntacticDiagnostics (evalmachine.<anonymous>:41947:52)
    at getDiagnositcsByFilePath (C:\Users\Steve\Documents\GitHub\atom-typescript\dist\main\lang\projectService.js:251:47)
    at errorsForFile (C:\Users\Steve\Documents\GitHub\atom-typescript\dist\main\lang\projectService.js:268:34)
    at Object.errorsForFile (C:\Users\Steve\Documents\GitHub\atom-typescript\dist\worker\parent.js:37:34)
    at Object.exports.provider.lint (C:\Users\Steve\Documents\GitHub\atom-typescript\dist\linter.js:16:23)
    at C:\Users\Steve\.atom\packages\linter\lib\editor-linter.coffee:110:37
    at currentLinter (C:\Users\Steve\.atom\packages\linter\lib\editor-linter.coffee:109:20)
    at C:\Users\Steve\.atom\packages\linter\lib\editor-linter.coffee:132:34
    at Set.forEach (native)
```

I'm assuming this has something to do with the language service not being aware of this file - which makes sense and is intentional - but I don't think I should get an error just by opening it.  I think it's fine if atom-typescript doesn't actually compile it or even provide code completion.

**Comment by basarat** [comment]
Duplicate of https://github.com/TypeStrong/atom-typescript/issues/368

**Comment by nycdotnet** [comment]
Indeed.  My apologies.  Thanks.
