### ISSUE TITLE
Uncaught error: This socket is closed

### ISSUE THREAD

**Issue by csnover** [TypeStrong/atom-typescript#49]
Repro:

1. Load a TypeScript file.
2. Type a character.

Trace:

```
Error: This socket is closed.
  at Socket._writeGeneric (net.js:647:19)
  at Socket._write (net.js:700:8)
  at doWrite (_stream_writable.js:303:12)
  at writeOrBuffer (_stream_writable.js:290:5)
  at Socket.Writable.write (_stream_writable.js:219:11)
  at Socket.write (net.js:625:40)
  at query (/Users/[…]/.atom/packages/atom-typescript/lib/worker/parent.js:82:17)
  at Object.exports.updateText (/Users/[…]/.atom/packages/atom-typescript/lib/worker/parent.js:85:47)
  at /Users/[…]/.atom/packages/atom-typescript/lib/main/atomts.js:47:28
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/service-hub/node_modules/event-kit/lib/emitter.js:82:11)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/text-buffer/lib/text-buffer.js:1151:25
```

Bisect:

```
e9f06aa49dd01b5c31f7ad25dee2d11ff494e394 is the first bad commit
commit e9f06aa49dd01b5c31f7ad25dee2d11ff494e394
Author: Basarat Syed <basaratali@gmail.com>
Date:   Wed Feb 4 17:39:29 2015 +1100

    update text on the child process

:040000 040000 019b276474bafb4998bd0ee7579929272486962f 9b12283e787159dcede8da58006e2e2919fca1bd M	lib
```

Environment:

Atom 0.177.0
Mac OS 10.9.5
Node v0.10.33

**Comment by csnover** [comment]
I’m not sure how to debug the child process inside of Atom and I don’t have time right now to mess with it. I suspect it is just crashing for some reason.

**Comment by csnover** [comment]
Oh, the PATH environment variable in Atom is missing the path to my installed copy of Node, but the spawn failure isn’t caught since it’s actually asynchronous (yay node APIs :\) and the code isn’t listening to `child.on('error')` for the eventual `ENOENT` code.

**Comment by csnover** [comment]
Error handling needs to be refactored to inform the UI of all failures and not just log things, but this is OK for now. Still odd to me that v0.25.0 did not trigger this issue and yet still somehow worked.
