### ISSUE TITLE
Cannot read property 'kind' of undefined

### ISSUE THREAD

**Issue by cmc19** [TypeStrong/atom-typescript#502]
Building my project fails with the following message dumped to the console: 

`\dist\worker\lib\workerLib.js:89`

```
TypeError: Cannot read property 'kind' of undefined
    at emitSerializedTypeNode (C:\Users\ccarisch\.atom\packages\atom-typescript\node_modules\ntypescript\bin\ntypescript.js:32938)
    at emitSerializedTypeOfNode (C:\Users\ccarisch\.atom\packages\atom-typescript\node_modules\ntypescript\bin\ntypescript.js:32922)
    at emitSerializedParameterTypesOfNode (C:\Users\ccarisch\.atom\packages\atom-typescript\node_modules\ntypescript\bin\ntypescript.js:33069)
    at emitSerializedTypeMetadata (C:\Users\ccarisch\.atom\packages\atom-typescript\node_modules\ntypescript\bin\ntypescript.js:33105)
    at emitDecoratorsOfConstructor (C:\Users\ccarisch\.atom\packages\atom-typescript\node_modules\ntypescript\bin\ntypescript.js:32719)
    at emitDecoratorsOfClass (C:\Users\ccarisch\.atom\packages\atom-typescript\node_modules\ntypescript\bin\ntypescript.js:32686)
    at emitClassLikeDeclarationBelowES6 (C:\Users\ccarisch\.atom\packages\atom-typescript\node_modules\ntypescript\bin\ntypescript.js:32644)
    at emitClassLikeDeclaration (C:\Users\ccarisch\.atom\packages\atom-typescript\node_modules\ntypescript\bin\ntypescript.js:32435)
    at emitClassDeclaration (C:\Users\ccarisch\.atom\packages\atom-typescript\node_modules\ntypescript\bin\ntypescript.js:32431)
    at emitJavaScriptWorker (C:\Users\ccarisch\.atom\packages\atom-typescript\node_modules\ntypescript\bin\ntypescript.js:34691)
```

Line 88 of `workerLib.js` logs the following object:

```
{"method":"build","message":"Cannot read property 'kind' of undefined","stack":"TypeError: Cannot read property 'kind' of undefined\n    at emitSerializedTypeNode (C:\\Users\\ccarisch\\.atom\\packages\\atom-typescript\\node_modules\\ntypescript\\bin\\ntypescript.js:32938:29)\n    at emitSerializedTypeOfNode (C:\\Users\\ccarisch\\.atom\\packages\\atom-typescript\\node_modules\\ntypescript\\bin\\ntypescript.js:32922:25)\n    at emitSerializedParameterTypesOfNode (C:\\Users\\ccarisch\\.atom\\packages\\atom-typescript\\node_modules\\ntypescript\\bin\\ntypescript.js:33069:37)\n    at emitSerializedTypeMetadata (C:\\Users\\ccarisch\\.atom\\packages\\atom-typescript\\node_modules\\ntypescript\\bin\\ntypescript.js:33105:25)\n    at emitDecoratorsOfConstructor (C:\\Users\\ccarisch\\.atom\\packages\\atom-typescript\\node_modules\\ntypescript\\bin\\ntypescript.js:32719:17)\n    at emitDecoratorsOfClass (C:\\Users\\ccarisch\\.atom\\packages\\atom-typescript\\node_modules\\ntypescript\\bin\\ntypescript.js:32686:17)\n    at emitClassLikeDeclarationBelowES6 (C:\\Users\\ccarisch\\.atom\\packages\\atom-typescript\\node_modules\\ntypescript\\bin\\ntypescript.js:32644:17)\n    at emitClassLikeDeclaration (C:\\Users\\ccarisch\\.atom\\packages\\atom-typescript\\node_modules\\ntypescript\\bin\\ntypescript.js:32435:21)\n    at emitClassDeclaration (C:\\Users\\ccarisch\\.atom\\packages\\atom-typescript\\node_modules\\ntypescript\\bin\\ntypescript.js:32431:24)\n    at emitJavaScriptWorker (C:\\Users\\ccarisch\\.atom\\packages\\atom-typescript\\node_modules\\ntypescript\\bin\\ntypescript.js:34691:32)","details":{}}
```

**Comment by basarat** [comment]
@cmc19 More info please: 

* what's the `.ts` source code. 
* what's the `target` setting in tsconfig.json

Thanks :rose:

**Comment by cmc19** [comment]
The target was not set. I changed it to ES5, however that did not change the error. 

I don't know what ts file is causing this error. This project contains about 20 of them.

**Comment by nycdotnet** [comment]
Your issue almost sounds like a TypeScript compiler error (meaning a bug in the compiler).  Can you compile your code from the command-line referencing the tsconfig.json file?

**Comment by cmc19** [comment]
Yep; The command line TSC produces the correct output.

**Comment by basarat** [comment]
Agree that it feels like a TypeScript bug (in that we have an `undefined` added as an AST node) 

> Yep; The command line TSC produces the correct output.

Try it with ntypescript : https://github.com/TypeStrong/ntypescript using `ntsc` (this is newer than the command line version you might have) 

> I don't know what ts file is causing this error. This project contains about 20 of them.

`console.error(filePath)` here : https://github.com/TypeStrong/atom-typescript/blob/84d378ebc6fcab3ed391a29d2c878ab92c7de686/lib/main/lang/modules/building.ts#L29 to see the last file that does get processed. Thanks ! :rose:
