### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by drumtj** [TypeStrong/atom-typescript#512]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.3
**System**: Unknown Windows Version
**Thrown From**: [atom-typescript](https://github.com/TypeStrong/atom-typescript) package, v5.2.4
### Stack Trace

Uncaught TypeError: Cannot read property '0' of undefined

```
At C:\Users\tj\.atom\packages\atom-typescript\dist\main\atom\views\rView.js:48

TypeError: Cannot read property '0' of undefined
  at RView.Object.defineProperty.get [as rootDomElement] (C:\Users\tj\.atom\packages\atom-typescript\dist\main\atom\views\rView.js:48:36)
  at new RView (C:\Users\tj\.atom\packages\atom-typescript\dist\main\atom\views\rView.js:44:64)
  at Object.atomUtils.registerOpener.onOpen (C:\Users\tj\.atom\packages\atom-typescript\dist\main\atom\commands\commands.js:390:42)
  at C:\Users\tj\.atom\packages\atom-typescript\dist\main\atom\atomUtils.js:204:23
  at Workspace.module.exports.Workspace.openURIInPane (C:\Users\tj\AppData\Local\atom\app-1.0.3\resources\app.asar\src\workspace.js:446:22)
  at Workspace.module.exports.Workspace.open (C:\Users\tj\AppData\Local\atom\app-1.0.3\resources\app.asar\src\workspace.js:379:19)
  at atom-workspace.<anonymous> (C:\Users\tj\.atom\packages\atom-typescript\dist\main\atom\atomUtils.js:192:24)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\tj\AppData\Local\atom\app-1.0.3\resources\app.asar\src\command-registry.js:241:29)
  at C:\Users\tj\AppData\Local\atom\app-1.0.3\resources\app.asar\src\command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (C:\Users\tj\AppData\Local\atom\app-1.0.3\resources\app.asar\node_modules\command-palette\lib\command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (C:\Users\tj\AppData\Local\atom\app-1.0.3\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (C:\Users\tj\AppData\Local\atom\app-1.0.3\resources\app.asar\node_modules\atom-space-pen-views\lib\select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\tj\AppData\Local\atom\app-1.0.3\resources\app.asar\src\command-registry.js:241:29)
  at C:\Users\tj\AppData\Local\atom\app-1.0.3\resources\app.asar\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\tj\AppData\Local\atom\app-1.0.3\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\tj\AppData\Local\atom\app-1.0.3\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\tj\AppData\Local\atom\app-1.0.3\resources\app.asar\src\window-event-handler.js:177:20)

```
### Commands

```
  5x -1:07.9.0 core:move-down (atom-text-editor.editor.mini.is-focused)
  2x -1:06.7.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -1:05.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:05.3.0 typescript:ast-full (atom-text-editor.editor)
     -0:54.6.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:49.5.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:49.3.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -0:49.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:49.1.0 typescript:ast (atom-text-editor.editor)
  2x -1:43.3.0 linter:lint (atom-text-editor.editor.is-focused)
     -0:37.1.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  5x -0:33.3.0 core:move-down (atom-text-editor.editor.mini.is-focused)
  2x -0:27.3.0 linter:lint (atom-text-editor.editor)
  7x -0:26.8.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:08.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:08.4.0 typescript:testing-r-view (atom-text-editor.editor)
```
### Config

``` json
{
  "core": {},
  "atom-typescript": {}
}
```
### Installed Packages

``` coffee
# User
.bin, vundefined
atom-typescript, v5.2.4
autoclose-html, v0.18.0
color-picker, v2.0.11
file-icons, v1.6.2
less-autocompile, v1.0.0
linter, v1.3.0
linter-tslint, v0.3.0
minimap, v4.12.1
Remote-FTP, v0.7.1
sge-app, v0.0.12

# Dev
No dev packages
```

**Comment by basarat** [comment]
Basically you tried to run the `rView` command?

**Comment by louy** [comment]
I had the same issue. yep the **rView** command.

**Comment by louy** [comment]
I guess you need to be in a React component or something. Still it shouldn't throw an error.
