### ISSUE TITLE
Uncaught SyntaxError: Failed to execute 'querySelectorAll' on 'Element': 'path.link[data-target=-...

### ISSUE THREAD

**Issue by stepancar** [TypeStrong/atom-typescript#513]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.3
**System**: Unknown Windows Version
**Thrown From**: [atom-typescript](https://github.com/TypeStrong/atom-typescript) package, v5.2.4

### Stack Trace

Uncaught SyntaxError: Failed to execute 'querySelectorAll' on 'Element': 'path.link[data-target=------------TypeScriptCommon-autoGenerated-GeneratedApiServicesAndClasses-d-ts]' is not a valid selector.

```
At C:\Users\Mikhailiuk\.atom\packages\atom-typescript\node_modules\d3\d3.js:0

Error: Failed to execute 'querySelectorAll' on 'Element': 'path.link[data-target=------------TypeScriptCommon-autoGenerated-GeneratedApiServicesAndClasses-d-ts]' is not a valid selector.
    at Error (native)
    at d3_selectAll (C:\Users\Mikhailiuk\.atom\packages\atom-typescript\node_modules\d3\d3.js:564:14)
    at SVGGElement.<anonymous> (C:\Users\Mikhailiuk\.atom\packages\atom-typescript\node_modules\d3\d3.js:620:14)
    at Array.d3_selectionPrototype.selectAll (C:\Users\Mikhailiuk\.atom\packages\atom-typescript\node_modules\d3\d3.js:611:55)
    at SVGPathElement.<anonymous> (C:\Users\Mikhailiuk\.atom\packages\atom-typescript\dist\main\atom\views\dependencyView.js:247:43)
    at C:\Users\Mikhailiuk\.atom\packages\atom-typescript\node_modules\d3\d3.js:962:16
    at d3_selection_each (C:\Users\Mikhailiuk\.atom\packages\atom-typescript\node_modules\d3\d3.js:968:30)
    at Array.d3_selectionPrototype.each (C:\Users\Mikhailiuk\.atom\packages\atom-typescript\node_modules\d3\d3.js:961:12)
    at updateNodeTransparencies (C:\Users\Mikhailiuk\.atom\packages\atom-typescript\dist\main\atom\views\dependencyView.js:233:15)
    at onNodeMouseOver (C:\Users\Mikhailiuk\.atom\packages\atom-typescript\dist\main\atom\views\dependencyView.js:205:9)
```

### Commands

```
     -2:13.1.0 core:move-down (atom-text-editor.editor.is-focused)
     -2:10.9.0 core:move-left (atom-text-editor.editor.is-focused)
     -2:10.4.0 core:move-right (atom-text-editor.editor.is-focused)
     -2:09.8.0 core:move-left (atom-text-editor.editor.is-focused)
 68x -2:09.3.0 core:move-right (atom-text-editor.editor.is-focused)
     -1:46.6.0 core:save (atom-text-editor.editor.is-focused)
     -1:46.5.0 linter:lint (atom-text-editor.editor.is-focused)
     -0:45.2.0 core:save (atom-text-editor.editor.is-focused)
     -0:45.2.0 linter:lint (atom-text-editor.editor.is-focused)
     -0:44.1.0 core:save (atom-text-editor.editor.is-focused)
     -0:44.1.0 linter:lint (atom-text-editor.editor.is-focused)
     -0:42.4.0 command-palette:toggle (atom-text-editor.editor.is-focused)
 14x -0:38.6.0 core:move-up (atom-text-editor.editor.mini.is-focused)
  5x -0:35.6.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:34.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:34.7.0 typescript:dependency-view (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      "bower_components node_packages"
    ]
  },
  "atom-typescript": {}
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
atom-typescript, v5.2.4
linter, v1.2.4

# Dev
No dev packages
```

**Comment by stepancar** [comment]
@basarat, do you want any additional information? 
Thank you!

**Comment by basarat** [comment]
> do you want any additional information

Yes please. Quick test : Dependency view worked fine on the project I am working on

![image](https://cloud.githubusercontent.com/assets/874898/9052662/8069a0d8-3aad-11e5-9ed3-c3ffdf4347a6.png)

Can we have a repro :rose:

**Comment by stepancar** [comment]
I'm sorry. I cant provide you my repo:(
But i observed my project and think that problem is the i have ts project which relates to another ts project in another dir. I catch this error only when i hover mouse pinter to node which represents module from another project. You can see that exception in selector which contains long relative paths.

if you want - i'll create any open repo
Thank you!

**Comment by stepancar** [comment]
Hello, @basarat !
I created [simple example](https://www.dropbox.com/s/jg4hrrgq4wez98v/dependencyViewCrashExample.zip?dl=0) which reproduce this issue.
unpack this zip then open  topDir/testProject/ folder in atom. navigate to app.tsx open typescript dependency view. Then mouse pointer hover to one from elements.
Thank you!

**Comment by basarat** [comment]
`5.2.9` 
@stepancar thanks for the repro :rose: !
