### ISSUE TITLE
Uncaught TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by snowcxt** [TypeStrong/atom-typescript#528]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.7
**System**: Microsoft Windows 8.1 Enterprise
**Thrown From**: [atom-typescript](https://github.com/TypeStrong/atom-typescript) package, v5.3.0

### Stack Trace

Uncaught TypeError: Cannot read property '1' of null

```
At C:\Users\tcui\.atom\packages\atom-typescript\dist\main\atom\autoCompleteProvider.js:146

TypeError: Cannot read property '1' of null
  at Object.exports.provider.onDidInsertSuggestion (C:\Users\tcui\.atom\packages\atom-typescript\dist\main\atom\autoCompleteProvider.js:146:35)
  at AutocompleteManager.module.exports.AutocompleteManager.confirm (C:\Users\tcui\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:485:28)
  at C:\Users\tcui\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\autocomplete-plus\lib\autocomplete-manager.js:3:61
  at Emitter.module.exports.Emitter.emit (C:\Users\tcui\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at SuggestionList.module.exports.SuggestionList.confirm (C:\Users\tcui\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\autocomplete-plus\lib\suggestion-list.js:135:27)
  at SuggestionList.confirm (C:\Users\tcui\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\autocomplete-plus\lib\suggestion-list.js:3:61)
  at autocomplete-suggestion-list.SuggestionListElement.confirmSelection (C:\Users\tcui\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\autocomplete-plus\lib\suggestion-list-element.js:251:27)
  at Emitter.module.exports.Emitter.emit (C:\Users\tcui\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\event-kit\lib\emitter.js:82:11)
  at SuggestionList.module.exports.SuggestionList.confirmSelection (C:\Users\tcui\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\autocomplete-plus\lib\suggestion-list.js:139:27)
  at atom-text-editor.<anonymous> (C:\Users\tcui\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\autocomplete-plus\lib\suggestion-list.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\tcui\AppData\Local\atom\app-1.0.7\resources\app.asar\src\command-registry.js:241:29)
  at C:\Users\tcui\AppData\Local\atom\app-1.0.7\resources\app.asar\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\tcui\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\tcui\AppData\Local\atom\app-1.0.7\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\tcui\AppData\Local\atom\app-1.0.7\resources\app.asar\src\window-event-handler.js:177:20)

```

### Commands

```
     -1:10.6.0 linter:lint (atom-text-editor.editor.is-focused)
     -0:52.3.0 core:copy (atom-text-editor.editor.is-focused)
     -0:51.4.0 core:paste (atom-text-editor.editor.is-focused)
     -0:50.9.0 core:save (atom-text-editor.editor.is-focused)
     -0:50.9.0 linter:lint (atom-text-editor.editor.is-focused)
     -0:49.9.0 core:save (atom-text-editor.editor.is-focused)
     -0:49.9.0 linter:lint (atom-text-editor.editor.is-focused)
     -0:14.2.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:14.1.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
  3x -0:12.3.0 core:move-right (atom-text-editor.editor.is-focused)
 12x -0:10.7.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:06.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:03.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:01.6.0 core:save (atom-text-editor.editor.is-focused)
     -0:01.6.0 linter:lint (atom-text-editor.editor.is-focused)
     -0:00.6.0 typescript:format-code (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "one-light-syntax"
    ],
    "disabledPackages": [
      "linter-jshint"
    ],
    "excludeVcsIgnoredPaths": false
  },
  "atom-typescript": {}
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
angularjs, v0.3.0
atom-beautify, v0.28.11
atom-compile-less, v0.12.0
atom-jade, v0.3.0
atom-material-ui, v0.5.18
atom-typescript, v5.3.0
language-ejs, v0.2.0
language-sql, v0.17.0
linter, v1.3.4
pigments, v0.11.0

# Dev
No dev packages
```

**Comment by basarat** [comment]
A repro file + steps would be highly appreciated :rose:

**Comment by cfv1984** [comment]
What I did to make this happen is simply create this structure: 
````
ts
-> src
    -> utilities.ts
   video.ts

````

video.ts looks like this: 
````
import $ = require('././src/utilities')
```

and utilities.ts looks like this: 
```
class Util{
  constructor(){ }  
}

export = new Util;

```

and I get this error.

**Comment by basarat** [comment]
> Thrown From: atom-typescript package, v5.3.0

That is *very old*. Please update to latest :rose: Comment if error still exits :rose:

**Comment by cfv1984** [comment]
Got it from doing an apm install atom-typescript.

**Comment by basarat** [comment]
Please try again https://github.com/TypeStrong/atom-typescript/blob/master/docs/faq.md#failed-to-update :rose: the version on apm is currently 8.1 :rose:
