### ISSUE TITLE
Plugin seems busted after Atom updated

### ISSUE THREAD

**Issue by rimig** [TypeStrong/atom-typescript#587]
atom-typescript 6.0.10
atom 1.0.13

Plugin was working great this morning but just restarted atom (looks like it updated) and now it's failing to load. Atom says it contains native modules compiled for an earlier version of Atom.

I tried uninstalling and installing again both through apm and within Atom. No luck.

When I try rebuilding in the app it shows this:

```
In file included from ../fsevents.cc:6:
In file included from ../node_modules/nan/nan.h:74:
In file included from ../node_modules/nan/nan_new.h:181:
../node_modules/nan/nan_implementation_12_inl.h:172:66: error: too many arguments to function call, expected at most 2, have 4
  return v8::Signature::New(v8::Isolate::GetCurrent(), receiver, argc, argv);
         ~~~~~~~~~~~~~~~~~~                                      ^~~~~~~~~~
/Users/rimig/.atom/.node-gyp/.node-gyp/0.30.6/deps/v8/include/v8.h:4515:3: note: 'New' declared here
  static Local<Signature> New(
  ^
1 error generated.
make: *** [Release/obj.target/fse/fsevents.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
```

I just started using Atom and it's great, just need to straighten this issue out.

**Comment by rimig** [comment]
I lost patience after going deep into debugging what node-gyp was doing. I reinstalled Atom and the plugin and things are working now.
