### ISSUE TITLE
atom-typescript 6.0.9 cannot be loaded on Atom 1.0.15

### ISSUE THREAD

**Issue by joanna16d** [TypeStrong/atom-typescript#604]
The package is incompatible with Atom 1.0.15 which is the latest version. Some installed packages could not be loaded because they contain native modules that were compiled for an earlier version of Atom. Rebuild packages failed with the following errors: 
```
2015-09-23 11:44:43.344 xcodebuild[2469:77854] [MT] PluginLoading: Required plug-in compatibility UUID 7FDF5C7A-131F-4ABB-9EDC-8C5F8F0B8A90 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Unity4XC.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2015-09-23 11:46:13.104 xcodebuild[2672:78669] [MT] PluginLoading: Required plug-in compatibility UUID 7FDF5C7A-131F-4ABB-9EDC-8C5F8F0B8A90 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Unity4XC.xcplugin' not present in DVTPlugInCompatibilityUUIDs
make: *** No rule to make target `../binding.gyp', needed by `Makefile'.  Stop.
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/joannareyes/.atom/packages/atom-typescript/node_modules/grunt-ts/node_modules/chokidar/node_modules/fsevents
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
```

**Comment by basarat** [comment]
From your log: 

> cwd /Users/joannareyes/.atom/packages/atom-typescript/node_modules/grunt-ts/n

This package no longer ships with `grunt` or `grunt-ts`. Follow : https://github.com/TypeStrong/atom-typescript/issues/600 for details. 

# Fix 

Use latest atom-typescript. If that doesn't work, try deleting `packages` directory and reinstalling. 

Closing as it is already fixed at our end :rose:

Feel free to discuss further if I am mistaken.

**Comment by joanna16d** [comment]
Got it, thanks.
