### ISSUE TITLE
Atom 1.1.0 atom-typescript installation problem

### ISSUE THREAD

**Issue by universalien** [TypeStrong/atom-typescript#704]
Atom 1.1.0 on Windows 8.1

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: EPERM, open 'C:\Users\LOKALH~1\AppData\Local\Temp\apm-install-dir-115103-3428-af9cky\node_modules\atom-typescript\node_modules\babel\node_modules\babel-core\node_modules\core-js\library\modules\core.log.js'

Cannot find module 'jquery'
Hide Stack Trace
Error: Cannot find module 'jquery'
    at Module._resolveFilename (module.js:334:15)
    at Function.Module._resolveFilename (C:\Users\lokalhorst\AppData\Local\atom\app-1.1.0\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:284:25)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (C:\Users\lokalhorst\.atom\packages\atom-typescript\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:9:18)
    at Object.<anonymous> (C:\Users\lokalhorst\.atom\packages\atom-typescript\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:634:4)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .js] (C:\Users\lokalhorst\AppData\Local\atom\app-1.1.0\resources\app.asar\src\compile-cache.js:169:21)
    at Module.load (module.js:353:32)

**Comment by vnabet** [comment]
Same here with the atom-typescript 7.7.2 version update. (EPERM error)
It was fixed with an atom-typescript uninstall/re-install

**Comment by basarat** [comment]
> it was fixed with an atom-typescript uninstall/re-install

since this is windows, sounds like https://github.com/TypeStrong/atom-typescript/blob/master/docs/faq.md#failed-to-update 

@universalien please comment if uninstall / install doesn't work for you :rose:

**Comment by basarat** [comment]
Potential dupe https://github.com/TypeStrong/atom-typescript/issues/195
