### ISSUE TITLE
Uncaught TypeError: deprecationSite.getFileName is not a function

### ISSUE THREAD

**Issue by tallstreet** [TypeStrong/atom-typescript#721]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.0
**System**: Mac OS X 10.11.2
**Thrown From**: [atom-typescript](https://github.com/TypeStrong/atom-typescript) package, v7.9.0

### Stack Trace

Uncaught TypeError: deprecationSite.getFileName is not a function

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/grim/lib/grim.js:56

TypeError: deprecationSite.getFileName is not a function
  at Object.global.__grim__.deprecate (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/grim/lib/grim.js:56:36)
  at TextEditor.module.exports.TextEditor.screenPositionForPixelPosition (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2929:12)
  at HTMLDivElement.<anonymous> (/Users/gary.roberts/.atom/packages/atom-typescript/dist/main/atom/tooltipManager.js:34:31)
  at HTMLDivElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at HTMLDivElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```

### Commands

```
     -0:45.8.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
atom-typescript, v7.9.0
line-ending-converter, v1.3.2
linter, v1.11.1
linter-eslint, v4.0.0
nuclide-flow, v0.0.32
react, v0.12.10

# Dev
No dev packages
```

**Comment by basarat** [comment]
We don't seem to have such a call in our code : https://github.com/TypeStrong/atom-typescript/search?utf8=%E2%9C%93&q=getFileName+ 

Considering it came from the command `settings-view:check-for-package-updates` recon its bad atom reporting. Closing for now. Please leave a comment if it continues to bother :rose:
