### ISSUE TITLE
Error on click inside editor window

### ISSUE THREAD

**Issue by janjilek** [TypeStrong/atom-typescript#774]
Hello,
I receive this exception everytime when I click inside editor window. So this plugin is unusable for me right now :-(

**Atom Version**: 1.3.0
**System**: Mac OS X 10.10.4
**Thrown From**: [atom-typescript](https://github.com/TypeStrong/atom-typescript) package, v7.14.2

### Stack Trace

Uncaught TypeError: editor.displayBuffer.getScrollTop is not a function

```
At /Users/janjilek/.atom/packages/atom-typescript/dist/main/atom/tooltipManager.js:49

TypeError: editor.displayBuffer.getScrollTop is not a function
    at showExpressionType (/Users/janjilek/.atom/packages/atom-typescript/dist/main/atom/tooltipManager.js:49:45)
    at /Users/janjilek/.atom/packages/atom-typescript/dist/main/atom/tooltipManager.js:40:59
```

### Commands

```
     -9:14.3.0 settings-view:open (atom-text-editor.editor.is-focused)
     -9:06.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-monokai.theme-one-dark-ui)
     -5:31 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -5:31 editor:newline (atom-text-editor.editor.is-focused)
  5x -5:26.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -5:24.4.0 core:move-right (atom-text-editor.editor.is-focused)
     -5:23.4.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -5:23.4.0 editor:newline (atom-text-editor.editor.is-focused)
     -5:14.3.0 core:move-right (atom-text-editor.editor.is-focused)
     -5:10.2.0 core:save (atom-text-editor.editor.is-focused)
  3x -5:06.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -4:53.5.0 core:save (atom-text-editor.editor.is-focused)
     -4:52.1.0 core:copy (atom-text-editor.editor.is-focused)
  2x -4:51.2.0 core:save (atom-text-editor.editor.is-focused)
  2x -4:14.7.0 linter:lint (atom-text-editor.editor.is-focused)
 10x -0:53.1.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "monokai"
    ],
    "disabledPackages": [
      ".bin"
    ],
    "excludeVcsIgnoredPaths": false
  },
  "atom-typescript": {}
}
```

### Installed Packages

```coffee
# User
api-docs, v0.0.3
atom-tsd, v0.9.0
atom-typescript, v7.14.2
atomatigit, v1.5.5
autocomplete-paths, v1.0.2
docblockr, v0.7.3
docs-snippets, v0.8.0
language-diff, v0.4.0
language-matlab, v0.1.1
last-cursor-position, v0.9.0
linter, v1.11.3
linter-tslint, v0.5.0
monokai, v0.18.0
npm-docs, v0.2.0

# Dev
No dev packages
```

**Comment by basarat** [comment]
Please update to latest atom version and report back if it doesn't fix it :rose:

![image](https://cloud.githubusercontent.com/assets/874898/11732357/8c10dc8a-9ff7-11e5-850b-e83dc7e56c14.png)
