### ISSUE TITLE
autocomplete does not work

### ISSUE THREAD

**Issue by doliver3** [TypeStrong/atom-typescript#784]
Autocomplete does not work. I'm on Mac El Capitan. 

I type the example lines in your example screen shot of autocomplete, and yet there is no dropdown for autocomplete for me.
var foo = 123;
var bar = foo.toString();

Also Command + Space which is what you say triggers auto-complete is the keyboard shortcut to launch the spotlight search on a Mac so that command is impossible to invoke with Command + Space. 

The other aspects of the typescript editor are working. It compiles and prompts for errors, but there is no autocomplete/intellisense happening anywhere. I have something with a type that should have autocomplete, then I press period after it, and nothing at all happens.

**Comment by basarat** [comment]
@doliver3 which version of atom?

**Comment by doliver3** [comment]
1.3.2

**Comment by basarat** [comment]
Any errors in the atom Dev console?

**Comment by laurelnaiad** [comment]
@doliver3, you might try launching atom via sudo.

```bash
cd <youprojdir>
sudo atom ./ 
```

If my suspicions are correct, this will make autocomplete more functional more often for you. For me, sudo-ing it help autocomplete to work properly, although it still eventually stops, at which point reloadiing the atom window is necessary to get it back again.

**Comment by Xarkam** [comment]
Hello, I have same problem
Console log give this but it's only for typescript project not found
```
Object
C:\Users\benja\.atom\packages\atom-typescript\dist\worker\lib\workerLib.js:89 Error: No Project Found
    at Object.getProjectSync (C:\Users\benja\.atom\packages\atom-typescript\dist\main\tsconfig\tsconfig.js:201:32)
    at getOrCreateProjectFile (C:\Users\benja\.atom\packages\atom-typescript\dist\main\lang\projectCache.js:74:36)
    at Object.getOrCreateProject (C:\Users\benja\.atom\packages\atom-typescript\dist\main\lang\projectCache.js:141:27)
    at Object.getProjectFileDetails (C:\Users\benja\.atom\packages\atom-typescript\dist\main\lang\projectService.js:332:34)
    at Child.RequesterResponder.processRequest (C:\Users\benja\.atom\packages\atom-typescript\dist\worker\lib\workerLib.js:49:60)
    at process.<anonymous> (C:\Users\benja\.atom\packages\atom-typescript\dist\worker\lib\workerLib.js:227:23)
    at emitTwo (events.js:87:13)
    at process.emit (events.js:172:7)
    at handleMessage (internal/child_process.js:685:10)
    at Pipe.channel.onread (internal/child_process.js:440:11)
C:\Users\benja\.atom\packages\atom-typescript\dist\worker\lib\workerLib.js:88 Object
C:\Users\benja\.atom\packages\atom-typescript\dist\worker\lib\workerLib.js:89 Error: No Project Found
    at Object.getProjectSync (C:\Users\benja\.atom\packages\atom-typescript\dist\main\tsconfig\tsconfig.js:201:32)
    at getOrCreateProjectFile (C:\Users\benja\.atom\packages\atom-typescript\dist\main\lang\projectCache.js:74:36)
    at Object.getOrCreateProject (C:\Users\benja\.atom\packages\atom-typescript\dist\main\lang\projectCache.js:141:27)
    at Object.updateText (C:\Users\benja\.atom\packages\atom-typescript\dist\main\lang\projectService.js:222:30)
    at Child.RequesterResponder.processRequest (C:\Users\benja\.atom\packages\atom-typescript\dist\worker\lib\workerLib.js:49:60)
    at process.<anonymous> (C:\Users\benja\.atom\packages\atom-typescript\dist\worker\lib\workerLib.js:227:23)
    at emitTwo (events.js:87:13)
    at process.emit (events.js:172:7)
    at handleMessage (internal/child_process.js:685:10)
    at Pipe.channel.onread (internal/child_process.js:440:11)
index.html:1 Uncaught (in promise) Objectdetails: Objectmessage: "No Project Found"method: "updateText"stack: "Error: No Project Found↵    at Object.getProjectSync (C:\Users\benja\.atom\packages\atom-typescript\dist\main\tsconfig\tsconfig.js:201:32)↵    at getOrCreateProjectFile (C:\Users\benja\.atom\packages\atom-typescript\dist\main\lang\projectCache.js:74:36)↵    at Object.getOrCreateProject (C:\Users\benja\.atom\packages\atom-typescript\dist\main\lang\projectCache.js:141:27)↵    at Object.updateText (C:\Users\benja\.atom\packages\atom-typescript\dist\main\lang\projectService.js:222:30)↵    at Child.RequesterResponder.processRequest (C:\Users\benja\.atom\packages\atom-typescript\dist\worker\lib\workerLib.js:49:60)↵    at process.<anonymous> (C:\Users\benja\.atom\packages\atom-typescript\dist\worker\lib\workerLib.js:227:23)↵    at emitTwo (events.js:87:13)↵    at process.emit (events.js:172:7)↵    at handleMessage (internal/child_process.js:685:10)↵    at Pipe.channel.onread (internal/child_process.js:440:11)"__proto__: Object
C:\Users\benja\.atom\packages\atom-typescript\dist\worker\lib\workerLib.js:88 Object
C:\Users\benja\.atom\packages\atom-typescript\dist\worker\lib\workerLib.js:89 Error: No Project Found
    at Object.getProjectSync (C:\Users\benja\.atom\packages\atom-typescript\dist\main\tsconfig\tsconfig.js:201:32)
    at getOrCreateProjectFile (C:\Users\benja\.atom\packages\atom-typescript\dist\main\lang\projectCache.js:74:36)
    at Object.getOrCreateProject (C:\Users\benja\.atom\packages\atom-typescript\dist\main\lang\projectCache.js:141:27)
    at Object.getOutputJsStatus (C:\Users\benja\.atom\packages\atom-typescript\dist\main\lang\projectService.js:602:34)
    at Child.RequesterResponder.processRequest (C:\Users\benja\.atom\packages\atom-typescript\dist\worker\lib\workerLib.js:49:60)
    at process.<anonymous> (C:\Users\benja\.atom\packages\atom-typescript\dist\worker\lib\workerLib.js:227:23)
    at emitTwo (events.js:87:13)
    at process.emit (events.js:172:7)
    at handleMessage (internal/child_process.js:685:10)
    at Pipe.channel.onread (internal/child_process.js:440:11)
```

My atom packages list : https://gist.github.com/Xarkam/f2d51d7ff4c4a6852b6c (for possible conflict)

Version use is 8.1.0
Used on Windows 10

Thanks.

**Comment by laurelnaiad** [comment]
Have you tried launching atom under sudo?

**Comment by basarat** [comment]
> Console log give this but it's only for typescript project not found

@Xarkam Is there an project *above the directory tree* for the file `foo.ts` that is being opened? :rose:

**Comment by Xarkam** [comment]
Yes but is webstorm project. In fact, I don't use a Atom Project (with project package).

I don't use a typescript config because I use a gulp proccess.

**Comment by basarat** [comment]
@Xarkam atom typescript needs tsconfig. The error is right and should be showing in the UI status bar as well. 

Closing issue as there hasn't been something actionable here for a while 🌹

**Comment by tigrus** [comment]
Had issues with autocomplete for typescript. 
Problem was in tsconfig.json file. 

Here is solution: 
http://stackoverflow.com/questions/32891385/atom-autocomplete-not-working
