### ISSUE TITLE
Uncaught TypeError: editor.displayBuffer.getScrollTop is not a function

### ISSUE THREAD

**Issue by kbh1245** [TypeStrong/atom-typescript#796]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Microsoft Windows 7 Enterprise 
**Thrown From**: [atom-typescript](https://github.com/TypeStrong/atom-typescript) package, v7.6.2
### Stack Trace

Uncaught TypeError: editor.displayBuffer.getScrollTop is not a function

```
At C:\Users\A175976\.atom\packages\atom-typescript\dist\main\atom\tooltipManager.js:49

TypeError: editor.displayBuffer.getScrollTop is not a function
    at showExpressionType (C:\Users\A175976\.atom\packages\atom-typescript\dist\main\atom\tooltipManager.js:49:45)
    at C:\Users\A175976\.atom\packages\atom-typescript\dist\main\atom\tooltipManager.js:40:59
```
### Commands

```
     -1:37.3.0 core:copy (atom-text-editor.editor.is-focused)
     -1:35.4.0 core:paste (atom-text-editor.editor.is-focused)
  7x -1:32 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:02.4.0 editor:newline (atom-text-editor.editor.is-focused)
  3x -0:57.8.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -0:56.1.0 core:move-down (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:55.6.0 core:move-up (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:55.3.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:54.5.0 core:move-right (atom-text-editor.editor.is-focused)
  2x -0:52.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:51.4.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:40.9.0 core:copy (atom-text-editor.editor.is-focused)
     -0:40 core:paste (atom-text-editor.editor.is-focused)
     -0:21.2.0 core:copy (atom-text-editor.editor.is-focused)
     -0:18.2.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:17.8.0 core:paste (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
.bin, vundefined
atom-typescript, v7.6.2
linter, v1.9.1

# Dev
No dev packages
```

**Comment by danieldram** [comment]
Gosh... I am getting this issue to, it won't stop popping up. 
<img width="1280" alt="screen shot 2016-02-14 at 2 48 04 pm" src="https://cloud.githubusercontent.com/assets/4514000/13036963/fbee8290-d329-11e5-8688-0c88a51db14c.png">

**Comment by nycdotnet** [comment]
Can you confirm that you're using the latest version of Atom and atom-typescript?  Just to be sure we're starting with something clean, we've had reports like this in the past and deleting the atom-typescript folder and reinstalling it seemed to clear it up.

**Comment by Xstoudi** [comment]
Same problem here.
I updated from 5.2.7 to 8.2 and it fixed it.
