### ISSUE TITLE
Error when building: TypeError: services.getNonBoundSourceFile is not a function at Object.emitFile 

### ISSUE THREAD

**Issue by 2426021684** [TypeStrong/atom-typescript#902]
TypeError: services.getNonBoundSourceFile is not a function
    at Object.emitFile (/Users/user/Code/atom-typescript/dist/main/lang/modules/building.js:29:31)
    at /Users/user/Code/atom-typescript/dist/main/lang/projectService.js:56:31
    at Array.map (native)
    at Object.build (/Users/user/Code/atom-typescript/dist/main/lang/projectService.js:55:31)
    at Child.RequesterResponder.processRequest (/Users/user/Code/atom-typescript/dist/worker/lib/workerLib.js:50:60)
    at process.<anonymous> (/Users/user/Code/atom-typescript/dist/worker/lib/workerLib.js:229:23)
    at emitTwo (events.js:87:13)
    at process.emit (events.js:172:7)
    at handleMessage (internal/child_process.js:685:10)
    at Pipe.channel.onread (internal/child_process.js:440:11)

**Comment by 2426021684** [comment]
Never mind I did something really stupid
