### ISSUE TITLE
Uncaught TypeError: Cannot read property 'null' of undefined

### ISSUE THREAD

**Issue by brentoneill** [TypeStrong/atom-typescript#972]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [atom-typescript](https://github.com/TypeStrong/atom-typescript) package, v8.11.0
### Stack Trace

Uncaught TypeError: Cannot read property 'null' of undefined

```
At /Users/brentoneill/.atom/packages/atom-typescript/node_modules/react/lib/ReactMount.js:636

TypeError: Cannot read property 'null' of undefined
    at Object.ReactMount.findReactContainerForID (/Users/brentoneill/.atom/packages/atom-typescript/node_modules/react/lib/ReactMount.js:636:50)
    at findParent (/Users/brentoneill/.atom/packages/atom-typescript/node_modules/react/lib/ReactEventListener.js:39:30)
    at handleTopLevelImpl (/Users/brentoneill/.atom/packages/atom-typescript/node_modules/react/lib/ReactEventListener.js:74:16)
    at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/Users/brentoneill/.atom/packages/atom-typescript/node_modules/react/lib/Transaction.js:134:20)
    at Object.ReactDefaultBatchingStrategy.batchedUpdates (/Users/brentoneill/.atom/packages/atom-typescript/node_modules/react/lib/ReactDefaultBatchingStrategy.js:66:19)
    at Object.batchedUpdates (/Users/brentoneill/.atom/packages/atom-typescript/node_modules/react/lib/ReactUpdates.js:110:20)
    at ReactEventListener.dispatchEvent (/Users/brentoneill/.atom/packages/atom-typescript/node_modules/react/lib/ReactEventListener.js:174:20)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "autoprefixer"
    ],
    "themes": [
      "atom-dark-ui",
      "babel-react-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
angularjs, v0.3.4
atom-typescript, v8.11.0
babel-react-syntax, v1.2.0
emmet, v2.4.3
emmet-snippets-compatibility, v1.0.6
formatter-json, v1.0.1
json-schema, v0.1.15
language-dust, v0.1.0
linter, v1.11.4
linter-json-lint, v0.1.1
minimap, v4.23.5
pigments, v0.26.3
pretty-json, v1.2.0
react-es6-snippets, v0.3.0

# Dev
No dev packages
```

**Comment by 0815fox** [comment]
In my case this happened, when I opened a .js file. From that point onwards, the same error message pops up everytime I click into the editor - even after closing the js-File. Maybe extremely long the source-Mapping-Line at the end of my file caused that issue?
